// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
)

// AgentRequest defines model for AgentRequest.
type AgentRequest struct {
	CaCrt     []openapi_types.File `json:"ca_crt"`
	ClientCrt []openapi_types.File `json:"client_crt"`
	ClientKey []openapi_types.File `json:"client_key"`
}

// AgentResponse defines model for AgentResponse.
type AgentResponse struct {
	CustomerId string `json:"customer_id"`
	Endpoint   string `json:"endpoint"`
}

// ClimonDeleteRequest defines model for ClimonDeleteRequest.
type ClimonDeleteRequest struct {
	// ClusterName Cluster in which to be deleted, default in-build cluster
	ClusterName *string `json:"cluster_name,omitempty"`
	CustomerId  string  `json:"customer_id"`

	// Namespace Namespace chart to be installed
	Namespace string `json:"namespace"`

	// PluginName Plugin name
	PluginName string `json:"plugin_name"`

	// ReleaseName Release name to be used for install
	ReleaseName string `json:"release_name"`

	// Timeout Timeout for the application installation
	Timeout int `json:"timeout"`
}

// ClimonPostRequest defines model for ClimonPostRequest.
type ClimonPostRequest struct {
	// ChartName Chart name in Repository
	ChartName string `json:"chart_name"`

	// ClusterName Cluster in which to be installed, default in-build cluster
	ClusterName *string `json:"cluster_name,omitempty"`

	// Namespace Namespace chart to be installed
	Namespace string `json:"namespace"`

	// PluginName Plugin name
	PluginName string `json:"plugin_name"`

	// ReleaseName Release name to be used for install
	ReleaseName string `json:"release_name"`

	// RepoName Repository name
	RepoName string `json:"repo_name"`

	// RepoUrl Repository URL
	RepoUrl string `json:"repo_url"`

	// Timeout Timeout for the application installation
	Timeout int `json:"timeout"`

	// Version Version of the chart
	Version *string `json:"version,omitempty"`
}

// ClusterRequest defines model for ClusterRequest.
type ClusterRequest struct {
	ClusterName string `json:"cluster_name"`
	CustomerId  string `json:"customer_id"`
	PluginName  string `json:"plugin_name"`
}

// DeployerDeleteRequest defines model for DeployerDeleteRequest.
type DeployerDeleteRequest struct {
	// ClusterName Cluster in which to be deleted, default in-build cluster
	ClusterName *string `json:"cluster_name,omitempty"`

	// Namespace Namespace chart to be installed
	Namespace string `json:"namespace"`

	// PluginName Plugin name
	PluginName string `json:"plugin_name"`

	// ReleaseName Release name to be used for install
	ReleaseName string `json:"release_name"`

	// Timeout Timeout for the application installation
	Timeout int `json:"timeout"`
}

// DeployerPostRequest defines model for DeployerPostRequest.
type DeployerPostRequest struct {
	// ChartName Chart name in Repository
	ChartName string `json:"chart_name"`

	// ClusterName Cluster in which to be installed, default in-build cluster
	ClusterName *string `json:"cluster_name,omitempty"`

	// Namespace Namespace chart to be installed
	Namespace string `json:"namespace"`

	// PluginName Plugin name
	PluginName string `json:"plugin_name"`

	// ReleaseName Release name to be used for install
	ReleaseName string `json:"release_name"`

	// RepoName Repository name
	RepoName string `json:"repo_name"`

	// RepoUrl Repository URL
	RepoUrl string `json:"repo_url"`

	// Timeout Timeout for the application installation
	Timeout int `json:"timeout"`

	// Version Version of the chart
	Version *string `json:"version,omitempty"`
}

// ProjectDeleteRequest defines model for ProjectDeleteRequest.
type ProjectDeleteRequest struct {
	// PluginName Plugin name
	PluginName string `json:"plugin_name"`

	// ProjectName Project name to be created in plugin
	ProjectName string `json:"project_name"`
}

// ProjectPostRequest defines model for ProjectPostRequest.
type ProjectPostRequest struct {
	// PluginName Plugin name
	PluginName string `json:"plugin_name"`

	// ProjectName Project name to be created in plugin
	ProjectName string `json:"project_name"`
}

// RepositoryDeleteRequest defines model for RepositoryDeleteRequest.
type RepositoryDeleteRequest struct {
	// PluginName Plugin name
	PluginName string `json:"plugin_name"`

	// RepoName Repository to added to plugin
	RepoName string `json:"repo_name"`
}

// RepositoryPostRequest defines model for RepositoryPostRequest.
type RepositoryPostRequest struct {
	// PluginName Plugin name
	PluginName string `json:"plugin_name"`

	// RepoName Repository to added to plugin
	RepoName string `json:"repo_name"`

	// RepoUrl Repository URL
	RepoUrl string `json:"repo_url"`
}

// Response Configuration request response
type Response struct {
	Message string `json:"message"`
	Status  string `json:"status"`
}

// StoreAgentCredRequest defines model for StoreAgentCredRequest.
type StoreAgentCredRequest struct {
	Credname   *string `json:"credname,omitempty"`
	CustomerId *string `json:"customer_id,omitempty"`
	Password   *string `json:"password,omitempty"`
	Username   *string `json:"username,omitempty"`
}

// StoreCredRequest defines model for StoreCredRequest.
type StoreCredRequest struct {
	Credname *string `json:"credname,omitempty"`
	Password *string `json:"password,omitempty"`
	Username *string `json:"username,omitempty"`
}

// DeleteClimonJSONRequestBody defines body for DeleteClimon for application/json ContentType.
type DeleteClimonJSONRequestBody = ClimonDeleteRequest

// PostClimonJSONRequestBody defines body for PostClimon for application/json ContentType.
type PostClimonJSONRequestBody = ClimonPostRequest

// PutClimonJSONRequestBody defines body for PutClimon for application/json ContentType.
type PutClimonJSONRequestBody = ClimonPostRequest

// DeleteConfigatorClusterJSONRequestBody defines body for DeleteConfigatorCluster for application/json ContentType.
type DeleteConfigatorClusterJSONRequestBody = ClusterRequest

// PostConfigatorClusterJSONRequestBody defines body for PostConfigatorCluster for application/json ContentType.
type PostConfigatorClusterJSONRequestBody = ClusterRequest

// DeleteConfigatorProjectJSONRequestBody defines body for DeleteConfigatorProject for application/json ContentType.
type DeleteConfigatorProjectJSONRequestBody = ProjectDeleteRequest

// PostConfigatorProjectJSONRequestBody defines body for PostConfigatorProject for application/json ContentType.
type PostConfigatorProjectJSONRequestBody = ProjectPostRequest

// PutConfigatorProjectJSONRequestBody defines body for PutConfigatorProject for application/json ContentType.
type PutConfigatorProjectJSONRequestBody = ProjectPostRequest

// DeleteConfigatorRepositoryJSONRequestBody defines body for DeleteConfigatorRepository for application/json ContentType.
type DeleteConfigatorRepositoryJSONRequestBody = RepositoryDeleteRequest

// PostConfigatorRepositoryJSONRequestBody defines body for PostConfigatorRepository for application/json ContentType.
type PostConfigatorRepositoryJSONRequestBody = RepositoryPostRequest

// PutConfigatorRepositoryJSONRequestBody defines body for PutConfigatorRepository for application/json ContentType.
type PutConfigatorRepositoryJSONRequestBody = RepositoryPostRequest

// DeleteDeployerJSONRequestBody defines body for DeleteDeployer for application/json ContentType.
type DeleteDeployerJSONRequestBody = DeployerDeleteRequest

// PostDeployerJSONRequestBody defines body for PostDeployer for application/json ContentType.
type PostDeployerJSONRequestBody = DeployerPostRequest

// PutDeployerJSONRequestBody defines body for PutDeployer for application/json ContentType.
type PutDeployerJSONRequestBody = DeployerPostRequest

// PostRegisterAgentMultipartRequestBody defines body for PostRegisterAgent for multipart/form-data ContentType.
type PostRegisterAgentMultipartRequestBody = AgentRequest

// PutRegisterAgentJSONRequestBody defines body for PutRegisterAgent for application/json ContentType.
type PutRegisterAgentJSONRequestBody = AgentRequest

// PostStoreAgentCredJSONRequestBody defines body for PostStoreAgentCred for application/json ContentType.
type PostStoreAgentCredJSONRequestBody = StoreAgentCredRequest

// PostStoreCredJSONRequestBody defines body for PostStoreCred for application/json ContentType.
type PostStoreCredJSONRequestBody = StoreCredRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List of APIs provided by the service
	// (GET /api-docs)
	GetApiDocs(c *gin.Context)
	// deploy the application
	// (DELETE /climon)
	DeleteClimon(c *gin.Context)
	// deploy the application
	// (POST /climon)
	PostClimon(c *gin.Context)
	// deploy the application
	// (PUT /climon)
	PutClimon(c *gin.Context)
	// Delete the application
	// (DELETE /configator/cluster)
	DeleteConfigatorCluster(c *gin.Context)
	// deploy the application
	// (POST /configator/cluster)
	PostConfigatorCluster(c *gin.Context)
	// deploy the application
	// (DELETE /configator/project)
	DeleteConfigatorProject(c *gin.Context)
	// deploy the application
	// (POST /configator/project)
	PostConfigatorProject(c *gin.Context)
	// deploy the application
	// (PUT /configator/project)
	PutConfigatorProject(c *gin.Context)
	// deploy the application
	// (DELETE /configator/repository)
	DeleteConfigatorRepository(c *gin.Context)
	// deploy the application
	// (POST /configator/repository)
	PostConfigatorRepository(c *gin.Context)
	// deploy the application
	// (PUT /configator/repository)
	PutConfigatorRepository(c *gin.Context)
	// deploy the application
	// (DELETE /deployer)
	DeleteDeployer(c *gin.Context)
	// deploy the application
	// (POST /deployer)
	PostDeployer(c *gin.Context)
	// deploy the application
	// (PUT /deployer)
	PutDeployer(c *gin.Context)
	// Register agent
	// (GET /register/agent)
	GetRegisterAgent(c *gin.Context)
	// Register agent
	// (POST /register/agent)
	PostRegisterAgent(c *gin.Context)
	// Register agent
	// (PUT /register/agent)
	PutRegisterAgent(c *gin.Context)
	// Kubernetes readiness and liveness probe endpoint
	// (GET /status)
	GetStatus(c *gin.Context)
	// to store the credentials in agent vault
	// (POST /store/agent/cred)
	PostStoreAgentCred(c *gin.Context)
	// Register agent
	// (GET /store/cred)
	GetStoreCred(c *gin.Context)
	// to store the credentials in agent vault
	// (POST /store/cred)
	PostStoreCred(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetApiDocs operation middleware
func (siw *ServerInterfaceWrapper) GetApiDocs(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.GetApiDocs(c)
}

// DeleteClimon operation middleware
func (siw *ServerInterfaceWrapper) DeleteClimon(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.DeleteClimon(c)
}

// PostClimon operation middleware
func (siw *ServerInterfaceWrapper) PostClimon(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.PostClimon(c)
}

// PutClimon operation middleware
func (siw *ServerInterfaceWrapper) PutClimon(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.PutClimon(c)
}

// DeleteConfigatorCluster operation middleware
func (siw *ServerInterfaceWrapper) DeleteConfigatorCluster(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.DeleteConfigatorCluster(c)
}

// PostConfigatorCluster operation middleware
func (siw *ServerInterfaceWrapper) PostConfigatorCluster(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.PostConfigatorCluster(c)
}

// DeleteConfigatorProject operation middleware
func (siw *ServerInterfaceWrapper) DeleteConfigatorProject(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.DeleteConfigatorProject(c)
}

// PostConfigatorProject operation middleware
func (siw *ServerInterfaceWrapper) PostConfigatorProject(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.PostConfigatorProject(c)
}

// PutConfigatorProject operation middleware
func (siw *ServerInterfaceWrapper) PutConfigatorProject(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.PutConfigatorProject(c)
}

// DeleteConfigatorRepository operation middleware
func (siw *ServerInterfaceWrapper) DeleteConfigatorRepository(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.DeleteConfigatorRepository(c)
}

// PostConfigatorRepository operation middleware
func (siw *ServerInterfaceWrapper) PostConfigatorRepository(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.PostConfigatorRepository(c)
}

// PutConfigatorRepository operation middleware
func (siw *ServerInterfaceWrapper) PutConfigatorRepository(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.PutConfigatorRepository(c)
}

// DeleteDeployer operation middleware
func (siw *ServerInterfaceWrapper) DeleteDeployer(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.DeleteDeployer(c)
}

// PostDeployer operation middleware
func (siw *ServerInterfaceWrapper) PostDeployer(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.PostDeployer(c)
}

// PutDeployer operation middleware
func (siw *ServerInterfaceWrapper) PutDeployer(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.PutDeployer(c)
}

// GetRegisterAgent operation middleware
func (siw *ServerInterfaceWrapper) GetRegisterAgent(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.GetRegisterAgent(c)
}

// PostRegisterAgent operation middleware
func (siw *ServerInterfaceWrapper) PostRegisterAgent(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.PostRegisterAgent(c)
}

// PutRegisterAgent operation middleware
func (siw *ServerInterfaceWrapper) PutRegisterAgent(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.PutRegisterAgent(c)
}

// GetStatus operation middleware
func (siw *ServerInterfaceWrapper) GetStatus(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.GetStatus(c)
}

// PostStoreAgentCred operation middleware
func (siw *ServerInterfaceWrapper) PostStoreAgentCred(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.PostStoreAgentCred(c)
}

// GetStoreCred operation middleware
func (siw *ServerInterfaceWrapper) GetStoreCred(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.GetStoreCred(c)
}

// PostStoreCred operation middleware
func (siw *ServerInterfaceWrapper) PostStoreCred(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.PostStoreCred(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router *gin.Engine, si ServerInterface) *gin.Engine {
	return RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router *gin.Engine, si ServerInterface, options GinServerOptions) *gin.Engine {

	errorHandler := options.ErrorHandler

	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/api-docs", wrapper.GetApiDocs)

	router.DELETE(options.BaseURL+"/climon", wrapper.DeleteClimon)

	router.POST(options.BaseURL+"/climon", wrapper.PostClimon)

	router.PUT(options.BaseURL+"/climon", wrapper.PutClimon)

	router.DELETE(options.BaseURL+"/configator/cluster", wrapper.DeleteConfigatorCluster)

	router.POST(options.BaseURL+"/configator/cluster", wrapper.PostConfigatorCluster)

	router.DELETE(options.BaseURL+"/configator/project", wrapper.DeleteConfigatorProject)

	router.POST(options.BaseURL+"/configator/project", wrapper.PostConfigatorProject)

	router.PUT(options.BaseURL+"/configator/project", wrapper.PutConfigatorProject)

	router.DELETE(options.BaseURL+"/configator/repository", wrapper.DeleteConfigatorRepository)

	router.POST(options.BaseURL+"/configator/repository", wrapper.PostConfigatorRepository)

	router.PUT(options.BaseURL+"/configator/repository", wrapper.PutConfigatorRepository)

	router.DELETE(options.BaseURL+"/deployer", wrapper.DeleteDeployer)

	router.POST(options.BaseURL+"/deployer", wrapper.PostDeployer)

	router.PUT(options.BaseURL+"/deployer", wrapper.PutDeployer)

	router.GET(options.BaseURL+"/register/agent", wrapper.GetRegisterAgent)

	router.POST(options.BaseURL+"/register/agent", wrapper.PostRegisterAgent)

	router.PUT(options.BaseURL+"/register/agent", wrapper.PutRegisterAgent)

	router.GET(options.BaseURL+"/status", wrapper.GetStatus)

	router.POST(options.BaseURL+"/store/agent/cred", wrapper.PostStoreAgentCred)

	router.GET(options.BaseURL+"/store/cred", wrapper.GetStoreCred)

	router.POST(options.BaseURL+"/store/cred", wrapper.PostStoreCred)

	return router
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+yawW7jNhPHX4Xg9x2dOO3efEuTogh20Q3sbS9FENDi2OZWIrlDygsj8LsXJCVZkiXL",
	"cmI33vpmmSI589N/htRQLzRSiVYSpDV09EJNtICE+Z+3c5B2DN9SMNZda1Qa0ArwrRF7jtD/Lywk/q+Z",
	"woRZOqJTIRmu6IDalQY6osaikHO6Lv5giGzlrqNYgLRvONLfsHrdSOsBRfiWCgROR3/lblYsrUz2NKBW",
	"2NiN4IERIcOcQsnNbGr6FSLrZsuoGq2kgQasqbEqAXwW3F1uGQuSayWkbWisW14aqdRvy17MbWkw9i4W",
	"iZL3EIOFdiXEqbGAz5Il3iEOJkKhPYARvQutREjyfSGiBbGKTIFwPyYfEA4zlsYO29U0FTEn2XBNT6oL",
	"jrPAaBY1mPF73kSiBUObWSGksSyOgTfNpuN0LmSLW4++kfjGhr4IMTADLZ3HodX3zixJDXAyU5ib1ChU",
	"kYBK7fZ4X0KD728XQJjWsYi8BPPxanoU0sIcsEM0ZQJlujX/NpaVxHUPOlYr4oQSDMGgH6LZKlaMt8vt",
	"UZkdacc9vTap+SfroQpJxqCVEVY1B/1Boi3k0k+2P7gsEbRqHTF/BjtM0uo5xXhn5z/Gn04VEAO6BDR+",
	"mPqof4YGomZ+UP/Ets2qRVQ1hjasSp4Pyqo+TZx5re6d0Xsn4ppG+yxUVV4VS0pe3yk5E/MUYZebAQ3g",
	"u1m/LuvTa9enU69IuYQua9JlTbqsSceMtEdU7mdHrn6N0HSYoa1zaC0LLUJgFriLuDBvT7CVCfsuXpk9",
	"OxPPf4fGJu6OKJD9koZVhHEO3P04CMRmmsMpHE0Wb8fgNWm0f77qj3JTgamts1n3auYqVUmqsBMwhs2b",
	"t8nGMpua7h1wdt+gGOypweKJVQi+ZHOHwNs3Iwj88H07M+a7wubG1AC27+hz+saZSQxECNbQNj8Od+H4",
	"JrpbhZypbWlMGJsQA7gEJJ81SDL+dfKF3D4+EKMhErNsOaebqdp7TGo9ihWe/nR9c33jvFEaJNOCjuiH",
	"65vrD056zC48oiHT4oqryF/MwUMsltsHTkf0N7C3Wty7W5zYgnr97T/f3Gy79vmjR2TSJGG4oiP6SRjr",
	"dhW3jw+GaFRL4eJ9uvLbDOeR8JsBy+bGh2g6jUVEn9wgw8jXccIkLltvWxeyeKj30BAMYOwvivvqbaSk",
	"hVDjLO2Shl9NGDTUqN2v/yPM6Ij+b7gpYg+zCvawqXa5XofQ26bxJlMWScVP0wGYh01SbStYQppRfHKi",
	"V6bhEbtF4AQIy2vN2QJMm/ilF3z74PMh7VdFZhUO87fK7vAu+twVL6LH4VwpZ70nyAHETsiBTEeUX0ju",
	"IdecZE2v2YtHH71mrz9Hotz4qntWrHOk+6r2JDzPNtFWaLYtVBeWPVnWsgBuSq89EkGlYHsM3m2FjbOC",
	"XmK7b0Y4Idiz1XIda2dquEDtCdXlCJ4d8XSnhfww6Ehwm48rzwpuwXJ3GjgRyLPVaBVjS9hfIO4N0YU5",
	"wly494Mhm2eGtpXNxtmdvtZKX+lv8SHiLser3wRuf5LYTSO3mbDM6JyCv74Kzgc3O2Jz2/s2bSVpbIVm",
	"aIczhckVZ5bt/6wrH5e26+qt3W6Jpf2dPlzd/4bHTvibQ4g2wU/y44due0waRWDMLI03p7s1Cz+mU0AJ",
	"FgxBYFxIMIYwyUksluAvNKopkOKL1PLmXSyZhcJwhRDCdRj5k5KXHbqtHo8c6Rk2n8G8p7RoFQnHG/5r",
	"AAQO0goWGyJkkAxZsjQuQ/e3V5DnsNv1kp3gnCQ5bp0XrU+bEKveHklTP6Cc3Dj+4Mv9/UL9OTAd0vXT",
	"+p8AAAD//2qPeyd0MAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
