// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
)

// AgentRequest defines model for AgentRequest.
type AgentRequest struct {
	CustomerId string `json:"customer_id"`
	Endpoint   string `json:"endpoint"`
}

// DeployPayload defines model for DeployPayload.
type DeployPayload struct {
	// Operation Operation
	Operation string               `json:"operation"`
	Payload   DeployRequestPayload `json:"payload"`
}

// DeployRequestPayload defines model for DeployRequestPayload.
type DeployRequestPayload struct {
	// Action Action to be performed
	Action string `json:"action"`

	// Data Data for the action
	Data map[string]interface{} `json:"data"`

	// PluginName Plugin name for the operation
	PluginName string `json:"plugin_name"`
}

// PostDeployJSONRequestBody defines body for PostDeploy for application/json ContentType.
type PostDeployJSONRequestBody = DeployPayload

// PostRegisterAgentJSONRequestBody defines body for PostRegisterAgent for application/json ContentType.
type PostRegisterAgentJSONRequestBody = AgentRequest

// PutRegisterAgentJSONRequestBody defines body for PutRegisterAgent for application/json ContentType.
type PutRegisterAgentJSONRequestBody = AgentRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List of APIs provided by the service
	// (GET /api-docs)
	GetApiDocs(c *gin.Context)
	// deploy the application
	// (POST /deploy)
	PostDeploy(c *gin.Context)
	// Register agent
	// (GET /register/agent)
	GetRegisterAgent(c *gin.Context)
	// Register agent
	// (POST /register/agent)
	PostRegisterAgent(c *gin.Context)
	// Register agent
	// (PUT /register/agent)
	PutRegisterAgent(c *gin.Context)
	// Kubernetes readiness and liveness probe endpoint
	// (GET /status)
	GetStatus(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetApiDocs operation middleware
func (siw *ServerInterfaceWrapper) GetApiDocs(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.GetApiDocs(c)
}

// PostDeploy operation middleware
func (siw *ServerInterfaceWrapper) PostDeploy(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.PostDeploy(c)
}

// GetRegisterAgent operation middleware
func (siw *ServerInterfaceWrapper) GetRegisterAgent(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.GetRegisterAgent(c)
}

// PostRegisterAgent operation middleware
func (siw *ServerInterfaceWrapper) PostRegisterAgent(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.PostRegisterAgent(c)
}

// PutRegisterAgent operation middleware
func (siw *ServerInterfaceWrapper) PutRegisterAgent(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.PutRegisterAgent(c)
}

// GetStatus operation middleware
func (siw *ServerInterfaceWrapper) GetStatus(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.GetStatus(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router *gin.Engine, si ServerInterface) *gin.Engine {
	return RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router *gin.Engine, si ServerInterface, options GinServerOptions) *gin.Engine {

	errorHandler := options.ErrorHandler

	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/api-docs", wrapper.GetApiDocs)

	router.POST(options.BaseURL+"/deploy", wrapper.PostDeploy)

	router.GET(options.BaseURL+"/register/agent", wrapper.GetRegisterAgent)

	router.POST(options.BaseURL+"/register/agent", wrapper.PostRegisterAgent)

	router.PUT(options.BaseURL+"/register/agent", wrapper.PutRegisterAgent)

	router.GET(options.BaseURL+"/status", wrapper.GetStatus)

	return router
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9xWTW/jOAz9KwJ3j9k4u735lkUHg6IDNGh6GxSFIjGpCltSRTpAEOS/DyQ5n7bbdI5z",
	"s0qRfO/xUc0WlKu9s2iZoNwCqVesZfqcrtDyI743SBzPPjiPgQ2mqGqIXY3hxeh45I1HKIE4GLuC3QjQ",
	"au+M5Z7gbgQB3xsTUEP586zSSd7zCNhwFRMTEmHs0oVasnEWRvuabvGGimPDW/SV28zkpnJSd/HG75xb",
	"bkEjqWB8PsLDITTq8vDHgn8HXEIJfxVHyYpWryJ3b9Xag7hk6k4a7eue0Mw1xD4yyPGiS4eqVP08p+nv",
	"gp1YoPAYopyo+0hrybKbfytZiqULgl9RtE16QPqqWRn7YmWN3RqzFBQxeCjlhvW/EPC09AgOEBLcrpCH",
	"uiJkxYaljY2iv7qA51LOBWFYYxAPHq14/DZ/EtPZnSCPyiyNOkBvuw9nzC8y1hgod/l3PBlPonjOo5Xe",
	"QAk348n4JhmFX9NYC+nNP9qpdFghn7n6TkMJ35Gn3tzGK1E38s5StsR/k0mP7++TwNTUtQwbKOGHIRZu",
	"GbGS8MGtjUYtFps0pcjIqKg7yxWlaTSLyih4jkUKnTRPZnTUg23miPNcIM8Uif93OmUoZxnzUyG9r1qB",
	"ijfKLkarnI52iMWPpm+znvIkO4mJWtrO63b3uLTZdV9WLyuQl+MIZkivgCtDjKGQq5b60Egf25vpFRwY",
	"7CcKHnUwjDV9JsjZy787LIsMQW7yrnwixR6ykC3mjgSjD2zSJfwVt1w383OKvzvyq3g2fTSbP4plNDSx",
	"5ObDt2meb1yDgRqlkGjZVCf/Hc5R3TcLDBYZSQSU2lgkEtJqUZk1poMPboHi8IPiBHcwa8kYgceS6amO",
	"gS00oYISCtg9734FAAD//wAGPtsaCQAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
