// Code generated by protoc-gen-go. DO NOT EDIT.
// source: agent.proto

package agentpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StatusCode int32

const (
	StatusCode_OK               StatusCode = 0
	StatusCode_INTERNRAL_ERROR  StatusCode = 1
	StatusCode_INVALID_ARGUMENT StatusCode = 2
	StatusCode_NOT_FOUND        StatusCode = 3
)

var StatusCode_name = map[int32]string{
	0: "OK",
	1: "INTERNRAL_ERROR",
	2: "INVALID_ARGUMENT",
	3: "NOT_FOUND",
}

var StatusCode_value = map[string]int32{
	"OK":               0,
	"INTERNRAL_ERROR":  1,
	"INVALID_ARGUMENT": 2,
	"NOT_FOUND":        3,
}

func (x StatusCode) String() string {
	return proto.EnumName(StatusCode_name, int32(x))
}

func (StatusCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{0}
}

type SecretAccess int32

const (
	SecretAccess_READ  SecretAccess = 0
	SecretAccess_WRITE SecretAccess = 1
)

var SecretAccess_name = map[int32]string{
	0: "READ",
	1: "WRITE",
}

var SecretAccess_value = map[string]int32{
	"READ":  0,
	"WRITE": 1,
}

func (x SecretAccess) String() string {
	return proto.EnumName(SecretAccess_name, int32(x))
}

func (SecretAccess) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{1}
}

type PingRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingRequest) Reset()         { *m = PingRequest{} }
func (m *PingRequest) String() string { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()    {}
func (*PingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{0}
}

func (m *PingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingRequest.Unmarshal(m, b)
}
func (m *PingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingRequest.Marshal(b, m, deterministic)
}
func (m *PingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingRequest.Merge(m, src)
}
func (m *PingRequest) XXX_Size() int {
	return xxx_messageInfo_PingRequest.Size(m)
}
func (m *PingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PingRequest proto.InternalMessageInfo

type PingResponse struct {
	Status               StatusCode `protobuf:"varint,1,opt,name=status,proto3,enum=agentpb.StatusCode" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PingResponse) Reset()         { *m = PingResponse{} }
func (m *PingResponse) String() string { return proto.CompactTextString(m) }
func (*PingResponse) ProtoMessage()    {}
func (*PingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{1}
}

func (m *PingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingResponse.Unmarshal(m, b)
}
func (m *PingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingResponse.Marshal(b, m, deterministic)
}
func (m *PingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingResponse.Merge(m, src)
}
func (m *PingResponse) XXX_Size() int {
	return xxx_messageInfo_PingResponse.Size(m)
}
func (m *PingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PingResponse proto.InternalMessageInfo

func (m *PingResponse) GetStatus() StatusCode {
	if m != nil {
		return m.Status
	}
	return StatusCode_OK
}

type StoreCredentialRequest struct {
	CredentialType       string            `protobuf:"bytes,1,opt,name=credentialType,proto3" json:"credentialType,omitempty"`
	CredEntityName       string            `protobuf:"bytes,2,opt,name=credEntityName,proto3" json:"credEntityName,omitempty"`
	CredIdentifier       string            `protobuf:"bytes,3,opt,name=credIdentifier,proto3" json:"credIdentifier,omitempty"`
	Credential           map[string]string `protobuf:"bytes,4,rep,name=credential,proto3" json:"credential,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *StoreCredentialRequest) Reset()         { *m = StoreCredentialRequest{} }
func (m *StoreCredentialRequest) String() string { return proto.CompactTextString(m) }
func (*StoreCredentialRequest) ProtoMessage()    {}
func (*StoreCredentialRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{2}
}

func (m *StoreCredentialRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoreCredentialRequest.Unmarshal(m, b)
}
func (m *StoreCredentialRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoreCredentialRequest.Marshal(b, m, deterministic)
}
func (m *StoreCredentialRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoreCredentialRequest.Merge(m, src)
}
func (m *StoreCredentialRequest) XXX_Size() int {
	return xxx_messageInfo_StoreCredentialRequest.Size(m)
}
func (m *StoreCredentialRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StoreCredentialRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StoreCredentialRequest proto.InternalMessageInfo

func (m *StoreCredentialRequest) GetCredentialType() string {
	if m != nil {
		return m.CredentialType
	}
	return ""
}

func (m *StoreCredentialRequest) GetCredEntityName() string {
	if m != nil {
		return m.CredEntityName
	}
	return ""
}

func (m *StoreCredentialRequest) GetCredIdentifier() string {
	if m != nil {
		return m.CredIdentifier
	}
	return ""
}

func (m *StoreCredentialRequest) GetCredential() map[string]string {
	if m != nil {
		return m.Credential
	}
	return nil
}

type StoreCredentialResponse struct {
	Status               StatusCode `protobuf:"varint,1,opt,name=status,proto3,enum=agentpb.StatusCode" json:"status,omitempty"`
	StatusMessage        string     `protobuf:"bytes,2,opt,name=statusMessage,proto3" json:"statusMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *StoreCredentialResponse) Reset()         { *m = StoreCredentialResponse{} }
func (m *StoreCredentialResponse) String() string { return proto.CompactTextString(m) }
func (*StoreCredentialResponse) ProtoMessage()    {}
func (*StoreCredentialResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{3}
}

func (m *StoreCredentialResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoreCredentialResponse.Unmarshal(m, b)
}
func (m *StoreCredentialResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoreCredentialResponse.Marshal(b, m, deterministic)
}
func (m *StoreCredentialResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoreCredentialResponse.Merge(m, src)
}
func (m *StoreCredentialResponse) XXX_Size() int {
	return xxx_messageInfo_StoreCredentialResponse.Size(m)
}
func (m *StoreCredentialResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StoreCredentialResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StoreCredentialResponse proto.InternalMessageInfo

func (m *StoreCredentialResponse) GetStatus() StatusCode {
	if m != nil {
		return m.Status
	}
	return StatusCode_OK
}

func (m *StoreCredentialResponse) GetStatusMessage() string {
	if m != nil {
		return m.StatusMessage
	}
	return ""
}

type ClusterRequest struct {
	PluginName           string   `protobuf:"bytes,1,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`
	ClusterName          string   `protobuf:"bytes,2,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClusterRequest) Reset()         { *m = ClusterRequest{} }
func (m *ClusterRequest) String() string { return proto.CompactTextString(m) }
func (*ClusterRequest) ProtoMessage()    {}
func (*ClusterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{4}
}

func (m *ClusterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterRequest.Unmarshal(m, b)
}
func (m *ClusterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterRequest.Marshal(b, m, deterministic)
}
func (m *ClusterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterRequest.Merge(m, src)
}
func (m *ClusterRequest) XXX_Size() int {
	return xxx_messageInfo_ClusterRequest.Size(m)
}
func (m *ClusterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterRequest proto.InternalMessageInfo

func (m *ClusterRequest) GetPluginName() string {
	if m != nil {
		return m.PluginName
	}
	return ""
}

func (m *ClusterRequest) GetClusterName() string {
	if m != nil {
		return m.ClusterName
	}
	return ""
}

type RepositoryAddRequest struct {
	PluginName           string   `protobuf:"bytes,1,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`
	RepoName             string   `protobuf:"bytes,2,opt,name=repo_name,json=repoName,proto3" json:"repo_name,omitempty"`
	RepoUrl              string   `protobuf:"bytes,3,opt,name=repo_url,json=repoUrl,proto3" json:"repo_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RepositoryAddRequest) Reset()         { *m = RepositoryAddRequest{} }
func (m *RepositoryAddRequest) String() string { return proto.CompactTextString(m) }
func (*RepositoryAddRequest) ProtoMessage()    {}
func (*RepositoryAddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{5}
}

func (m *RepositoryAddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RepositoryAddRequest.Unmarshal(m, b)
}
func (m *RepositoryAddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RepositoryAddRequest.Marshal(b, m, deterministic)
}
func (m *RepositoryAddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RepositoryAddRequest.Merge(m, src)
}
func (m *RepositoryAddRequest) XXX_Size() int {
	return xxx_messageInfo_RepositoryAddRequest.Size(m)
}
func (m *RepositoryAddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RepositoryAddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RepositoryAddRequest proto.InternalMessageInfo

func (m *RepositoryAddRequest) GetPluginName() string {
	if m != nil {
		return m.PluginName
	}
	return ""
}

func (m *RepositoryAddRequest) GetRepoName() string {
	if m != nil {
		return m.RepoName
	}
	return ""
}

func (m *RepositoryAddRequest) GetRepoUrl() string {
	if m != nil {
		return m.RepoUrl
	}
	return ""
}

type RepositoryDeleteRequest struct {
	PluginName           string   `protobuf:"bytes,1,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`
	RepoName             string   `protobuf:"bytes,2,opt,name=repo_name,json=repoName,proto3" json:"repo_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RepositoryDeleteRequest) Reset()         { *m = RepositoryDeleteRequest{} }
func (m *RepositoryDeleteRequest) String() string { return proto.CompactTextString(m) }
func (*RepositoryDeleteRequest) ProtoMessage()    {}
func (*RepositoryDeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{6}
}

func (m *RepositoryDeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RepositoryDeleteRequest.Unmarshal(m, b)
}
func (m *RepositoryDeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RepositoryDeleteRequest.Marshal(b, m, deterministic)
}
func (m *RepositoryDeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RepositoryDeleteRequest.Merge(m, src)
}
func (m *RepositoryDeleteRequest) XXX_Size() int {
	return xxx_messageInfo_RepositoryDeleteRequest.Size(m)
}
func (m *RepositoryDeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RepositoryDeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RepositoryDeleteRequest proto.InternalMessageInfo

func (m *RepositoryDeleteRequest) GetPluginName() string {
	if m != nil {
		return m.PluginName
	}
	return ""
}

func (m *RepositoryDeleteRequest) GetRepoName() string {
	if m != nil {
		return m.RepoName
	}
	return ""
}

type ProjectAddRequest struct {
	PluginName           string   `protobuf:"bytes,1,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`
	ProjectName          string   `protobuf:"bytes,2,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProjectAddRequest) Reset()         { *m = ProjectAddRequest{} }
func (m *ProjectAddRequest) String() string { return proto.CompactTextString(m) }
func (*ProjectAddRequest) ProtoMessage()    {}
func (*ProjectAddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{7}
}

func (m *ProjectAddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProjectAddRequest.Unmarshal(m, b)
}
func (m *ProjectAddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProjectAddRequest.Marshal(b, m, deterministic)
}
func (m *ProjectAddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProjectAddRequest.Merge(m, src)
}
func (m *ProjectAddRequest) XXX_Size() int {
	return xxx_messageInfo_ProjectAddRequest.Size(m)
}
func (m *ProjectAddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProjectAddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProjectAddRequest proto.InternalMessageInfo

func (m *ProjectAddRequest) GetPluginName() string {
	if m != nil {
		return m.PluginName
	}
	return ""
}

func (m *ProjectAddRequest) GetProjectName() string {
	if m != nil {
		return m.ProjectName
	}
	return ""
}

type ProjectDeleteRequest struct {
	PluginName           string   `protobuf:"bytes,1,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`
	ProjectName          string   `protobuf:"bytes,2,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProjectDeleteRequest) Reset()         { *m = ProjectDeleteRequest{} }
func (m *ProjectDeleteRequest) String() string { return proto.CompactTextString(m) }
func (*ProjectDeleteRequest) ProtoMessage()    {}
func (*ProjectDeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{8}
}

func (m *ProjectDeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProjectDeleteRequest.Unmarshal(m, b)
}
func (m *ProjectDeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProjectDeleteRequest.Marshal(b, m, deterministic)
}
func (m *ProjectDeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProjectDeleteRequest.Merge(m, src)
}
func (m *ProjectDeleteRequest) XXX_Size() int {
	return xxx_messageInfo_ProjectDeleteRequest.Size(m)
}
func (m *ProjectDeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProjectDeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProjectDeleteRequest proto.InternalMessageInfo

func (m *ProjectDeleteRequest) GetPluginName() string {
	if m != nil {
		return m.PluginName
	}
	return ""
}

func (m *ProjectDeleteRequest) GetProjectName() string {
	if m != nil {
		return m.ProjectName
	}
	return ""
}

type JobResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RunID                string   `protobuf:"bytes,2,opt,name=runID,proto3" json:"runID,omitempty"`
	WorkflowName         string   `protobuf:"bytes,3,opt,name=workflowName,proto3" json:"workflowName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobResponse) Reset()         { *m = JobResponse{} }
func (m *JobResponse) String() string { return proto.CompactTextString(m) }
func (*JobResponse) ProtoMessage()    {}
func (*JobResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{9}
}

func (m *JobResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobResponse.Unmarshal(m, b)
}
func (m *JobResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobResponse.Marshal(b, m, deterministic)
}
func (m *JobResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobResponse.Merge(m, src)
}
func (m *JobResponse) XXX_Size() int {
	return xxx_messageInfo_JobResponse.Size(m)
}
func (m *JobResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JobResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JobResponse proto.InternalMessageInfo

func (m *JobResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *JobResponse) GetRunID() string {
	if m != nil {
		return m.RunID
	}
	return ""
}

func (m *JobResponse) GetWorkflowName() string {
	if m != nil {
		return m.WorkflowName
	}
	return ""
}

type SyncAppRequest struct {
	Data                 *SyncAppData `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SyncAppRequest) Reset()         { *m = SyncAppRequest{} }
func (m *SyncAppRequest) String() string { return proto.CompactTextString(m) }
func (*SyncAppRequest) ProtoMessage()    {}
func (*SyncAppRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{10}
}

func (m *SyncAppRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncAppRequest.Unmarshal(m, b)
}
func (m *SyncAppRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncAppRequest.Marshal(b, m, deterministic)
}
func (m *SyncAppRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncAppRequest.Merge(m, src)
}
func (m *SyncAppRequest) XXX_Size() int {
	return xxx_messageInfo_SyncAppRequest.Size(m)
}
func (m *SyncAppRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncAppRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SyncAppRequest proto.InternalMessageInfo

func (m *SyncAppRequest) GetData() *SyncAppData {
	if m != nil {
		return m.Data
	}
	return nil
}

type SyncAppResponse struct {
	Status               StatusCode `protobuf:"varint,1,opt,name=status,proto3,enum=agentpb.StatusCode" json:"status,omitempty"`
	StatusMessage        string     `protobuf:"bytes,2,opt,name=statusMessage,proto3" json:"statusMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SyncAppResponse) Reset()         { *m = SyncAppResponse{} }
func (m *SyncAppResponse) String() string { return proto.CompactTextString(m) }
func (*SyncAppResponse) ProtoMessage()    {}
func (*SyncAppResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{11}
}

func (m *SyncAppResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncAppResponse.Unmarshal(m, b)
}
func (m *SyncAppResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncAppResponse.Marshal(b, m, deterministic)
}
func (m *SyncAppResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncAppResponse.Merge(m, src)
}
func (m *SyncAppResponse) XXX_Size() int {
	return xxx_messageInfo_SyncAppResponse.Size(m)
}
func (m *SyncAppResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncAppResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SyncAppResponse proto.InternalMessageInfo

func (m *SyncAppResponse) GetStatus() StatusCode {
	if m != nil {
		return m.Status
	}
	return StatusCode_OK
}

func (m *SyncAppResponse) GetStatusMessage() string {
	if m != nil {
		return m.StatusMessage
	}
	return ""
}

type GetClusterAppsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetClusterAppsRequest) Reset()         { *m = GetClusterAppsRequest{} }
func (m *GetClusterAppsRequest) String() string { return proto.CompactTextString(m) }
func (*GetClusterAppsRequest) ProtoMessage()    {}
func (*GetClusterAppsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{12}
}

func (m *GetClusterAppsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetClusterAppsRequest.Unmarshal(m, b)
}
func (m *GetClusterAppsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetClusterAppsRequest.Marshal(b, m, deterministic)
}
func (m *GetClusterAppsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetClusterAppsRequest.Merge(m, src)
}
func (m *GetClusterAppsRequest) XXX_Size() int {
	return xxx_messageInfo_GetClusterAppsRequest.Size(m)
}
func (m *GetClusterAppsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetClusterAppsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetClusterAppsRequest proto.InternalMessageInfo

type GetClusterAppsResponse struct {
	Status               StatusCode `protobuf:"varint,1,opt,name=status,proto3,enum=agentpb.StatusCode" json:"status,omitempty"`
	StatusMessage        string     `protobuf:"bytes,2,opt,name=statusMessage,proto3" json:"statusMessage,omitempty"`
	AppData              []*AppData `protobuf:"bytes,3,rep,name=appData,proto3" json:"appData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetClusterAppsResponse) Reset()         { *m = GetClusterAppsResponse{} }
func (m *GetClusterAppsResponse) String() string { return proto.CompactTextString(m) }
func (*GetClusterAppsResponse) ProtoMessage()    {}
func (*GetClusterAppsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{13}
}

func (m *GetClusterAppsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetClusterAppsResponse.Unmarshal(m, b)
}
func (m *GetClusterAppsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetClusterAppsResponse.Marshal(b, m, deterministic)
}
func (m *GetClusterAppsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetClusterAppsResponse.Merge(m, src)
}
func (m *GetClusterAppsResponse) XXX_Size() int {
	return xxx_messageInfo_GetClusterAppsResponse.Size(m)
}
func (m *GetClusterAppsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetClusterAppsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetClusterAppsResponse proto.InternalMessageInfo

func (m *GetClusterAppsResponse) GetStatus() StatusCode {
	if m != nil {
		return m.Status
	}
	return StatusCode_OK
}

func (m *GetClusterAppsResponse) GetStatusMessage() string {
	if m != nil {
		return m.StatusMessage
	}
	return ""
}

func (m *GetClusterAppsResponse) GetAppData() []*AppData {
	if m != nil {
		return m.AppData
	}
	return nil
}

type GetClusterAppLaunchesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetClusterAppLaunchesRequest) Reset()         { *m = GetClusterAppLaunchesRequest{} }
func (m *GetClusterAppLaunchesRequest) String() string { return proto.CompactTextString(m) }
func (*GetClusterAppLaunchesRequest) ProtoMessage()    {}
func (*GetClusterAppLaunchesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{14}
}

func (m *GetClusterAppLaunchesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetClusterAppLaunchesRequest.Unmarshal(m, b)
}
func (m *GetClusterAppLaunchesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetClusterAppLaunchesRequest.Marshal(b, m, deterministic)
}
func (m *GetClusterAppLaunchesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetClusterAppLaunchesRequest.Merge(m, src)
}
func (m *GetClusterAppLaunchesRequest) XXX_Size() int {
	return xxx_messageInfo_GetClusterAppLaunchesRequest.Size(m)
}
func (m *GetClusterAppLaunchesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetClusterAppLaunchesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetClusterAppLaunchesRequest proto.InternalMessageInfo

type GetClusterAppLaunchesResponse struct {
	Status               StatusCode         `protobuf:"varint,1,opt,name=status,proto3,enum=agentpb.StatusCode" json:"status,omitempty"`
	StatusMessage        string             `protobuf:"bytes,2,opt,name=statusMessage,proto3" json:"statusMessage,omitempty"`
	LaunchConfigList     []*AppLaunchConfig `protobuf:"bytes,3,rep,name=launchConfigList,proto3" json:"launchConfigList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetClusterAppLaunchesResponse) Reset()         { *m = GetClusterAppLaunchesResponse{} }
func (m *GetClusterAppLaunchesResponse) String() string { return proto.CompactTextString(m) }
func (*GetClusterAppLaunchesResponse) ProtoMessage()    {}
func (*GetClusterAppLaunchesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{15}
}

func (m *GetClusterAppLaunchesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetClusterAppLaunchesResponse.Unmarshal(m, b)
}
func (m *GetClusterAppLaunchesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetClusterAppLaunchesResponse.Marshal(b, m, deterministic)
}
func (m *GetClusterAppLaunchesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetClusterAppLaunchesResponse.Merge(m, src)
}
func (m *GetClusterAppLaunchesResponse) XXX_Size() int {
	return xxx_messageInfo_GetClusterAppLaunchesResponse.Size(m)
}
func (m *GetClusterAppLaunchesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetClusterAppLaunchesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetClusterAppLaunchesResponse proto.InternalMessageInfo

func (m *GetClusterAppLaunchesResponse) GetStatus() StatusCode {
	if m != nil {
		return m.Status
	}
	return StatusCode_OK
}

func (m *GetClusterAppLaunchesResponse) GetStatusMessage() string {
	if m != nil {
		return m.StatusMessage
	}
	return ""
}

func (m *GetClusterAppLaunchesResponse) GetLaunchConfigList() []*AppLaunchConfig {
	if m != nil {
		return m.LaunchConfigList
	}
	return nil
}

type ConfigureAppSSORequest struct {
	ReleaseName          string   `protobuf:"bytes,1,opt,name=releaseName,proto3" json:"releaseName,omitempty"`
	ClientId             string   `protobuf:"bytes,2,opt,name=clientId,proto3" json:"clientId,omitempty"`
	ClientSecret         string   `protobuf:"bytes,3,opt,name=clientSecret,proto3" json:"clientSecret,omitempty"`
	OAuthBaseURL         string   `protobuf:"bytes,4,opt,name=oAuthBaseURL,proto3" json:"oAuthBaseURL,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigureAppSSORequest) Reset()         { *m = ConfigureAppSSORequest{} }
func (m *ConfigureAppSSORequest) String() string { return proto.CompactTextString(m) }
func (*ConfigureAppSSORequest) ProtoMessage()    {}
func (*ConfigureAppSSORequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{16}
}

func (m *ConfigureAppSSORequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigureAppSSORequest.Unmarshal(m, b)
}
func (m *ConfigureAppSSORequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigureAppSSORequest.Marshal(b, m, deterministic)
}
func (m *ConfigureAppSSORequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigureAppSSORequest.Merge(m, src)
}
func (m *ConfigureAppSSORequest) XXX_Size() int {
	return xxx_messageInfo_ConfigureAppSSORequest.Size(m)
}
func (m *ConfigureAppSSORequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigureAppSSORequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigureAppSSORequest proto.InternalMessageInfo

func (m *ConfigureAppSSORequest) GetReleaseName() string {
	if m != nil {
		return m.ReleaseName
	}
	return ""
}

func (m *ConfigureAppSSORequest) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *ConfigureAppSSORequest) GetClientSecret() string {
	if m != nil {
		return m.ClientSecret
	}
	return ""
}

func (m *ConfigureAppSSORequest) GetOAuthBaseURL() string {
	if m != nil {
		return m.OAuthBaseURL
	}
	return ""
}

type ConfigureAppSSOResponse struct {
	Status               StatusCode `protobuf:"varint,1,opt,name=status,proto3,enum=agentpb.StatusCode" json:"status,omitempty"`
	StatusMessage        string     `protobuf:"bytes,2,opt,name=statusMessage,proto3" json:"statusMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ConfigureAppSSOResponse) Reset()         { *m = ConfigureAppSSOResponse{} }
func (m *ConfigureAppSSOResponse) String() string { return proto.CompactTextString(m) }
func (*ConfigureAppSSOResponse) ProtoMessage()    {}
func (*ConfigureAppSSOResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{17}
}

func (m *ConfigureAppSSOResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigureAppSSOResponse.Unmarshal(m, b)
}
func (m *ConfigureAppSSOResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigureAppSSOResponse.Marshal(b, m, deterministic)
}
func (m *ConfigureAppSSOResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigureAppSSOResponse.Merge(m, src)
}
func (m *ConfigureAppSSOResponse) XXX_Size() int {
	return xxx_messageInfo_ConfigureAppSSOResponse.Size(m)
}
func (m *ConfigureAppSSOResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigureAppSSOResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigureAppSSOResponse proto.InternalMessageInfo

func (m *ConfigureAppSSOResponse) GetStatus() StatusCode {
	if m != nil {
		return m.Status
	}
	return StatusCode_OK
}

func (m *ConfigureAppSSOResponse) GetStatusMessage() string {
	if m != nil {
		return m.StatusMessage
	}
	return ""
}

type GetClusterAppConfigRequest struct {
	ReleaseName          string   `protobuf:"bytes,1,opt,name=releaseName,proto3" json:"releaseName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetClusterAppConfigRequest) Reset()         { *m = GetClusterAppConfigRequest{} }
func (m *GetClusterAppConfigRequest) String() string { return proto.CompactTextString(m) }
func (*GetClusterAppConfigRequest) ProtoMessage()    {}
func (*GetClusterAppConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{18}
}

func (m *GetClusterAppConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetClusterAppConfigRequest.Unmarshal(m, b)
}
func (m *GetClusterAppConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetClusterAppConfigRequest.Marshal(b, m, deterministic)
}
func (m *GetClusterAppConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetClusterAppConfigRequest.Merge(m, src)
}
func (m *GetClusterAppConfigRequest) XXX_Size() int {
	return xxx_messageInfo_GetClusterAppConfigRequest.Size(m)
}
func (m *GetClusterAppConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetClusterAppConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetClusterAppConfigRequest proto.InternalMessageInfo

func (m *GetClusterAppConfigRequest) GetReleaseName() string {
	if m != nil {
		return m.ReleaseName
	}
	return ""
}

type GetClusterAppConfigResponse struct {
	Status               StatusCode `protobuf:"varint,1,opt,name=status,proto3,enum=agentpb.StatusCode" json:"status,omitempty"`
	StatusMessage        string     `protobuf:"bytes,2,opt,name=statusMessage,proto3" json:"statusMessage,omitempty"`
	AppConfig            *AppConfig `protobuf:"bytes,3,opt,name=appConfig,proto3" json:"appConfig,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetClusterAppConfigResponse) Reset()         { *m = GetClusterAppConfigResponse{} }
func (m *GetClusterAppConfigResponse) String() string { return proto.CompactTextString(m) }
func (*GetClusterAppConfigResponse) ProtoMessage()    {}
func (*GetClusterAppConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{19}
}

func (m *GetClusterAppConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetClusterAppConfigResponse.Unmarshal(m, b)
}
func (m *GetClusterAppConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetClusterAppConfigResponse.Marshal(b, m, deterministic)
}
func (m *GetClusterAppConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetClusterAppConfigResponse.Merge(m, src)
}
func (m *GetClusterAppConfigResponse) XXX_Size() int {
	return xxx_messageInfo_GetClusterAppConfigResponse.Size(m)
}
func (m *GetClusterAppConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetClusterAppConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetClusterAppConfigResponse proto.InternalMessageInfo

func (m *GetClusterAppConfigResponse) GetStatus() StatusCode {
	if m != nil {
		return m.Status
	}
	return StatusCode_OK
}

func (m *GetClusterAppConfigResponse) GetStatusMessage() string {
	if m != nil {
		return m.StatusMessage
	}
	return ""
}

func (m *GetClusterAppConfigResponse) GetAppConfig() *AppConfig {
	if m != nil {
		return m.AppConfig
	}
	return nil
}

type GetClusterAppValuesRequest struct {
	ReleaseName          string   `protobuf:"bytes,1,opt,name=releaseName,proto3" json:"releaseName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetClusterAppValuesRequest) Reset()         { *m = GetClusterAppValuesRequest{} }
func (m *GetClusterAppValuesRequest) String() string { return proto.CompactTextString(m) }
func (*GetClusterAppValuesRequest) ProtoMessage()    {}
func (*GetClusterAppValuesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{20}
}

func (m *GetClusterAppValuesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetClusterAppValuesRequest.Unmarshal(m, b)
}
func (m *GetClusterAppValuesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetClusterAppValuesRequest.Marshal(b, m, deterministic)
}
func (m *GetClusterAppValuesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetClusterAppValuesRequest.Merge(m, src)
}
func (m *GetClusterAppValuesRequest) XXX_Size() int {
	return xxx_messageInfo_GetClusterAppValuesRequest.Size(m)
}
func (m *GetClusterAppValuesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetClusterAppValuesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetClusterAppValuesRequest proto.InternalMessageInfo

func (m *GetClusterAppValuesRequest) GetReleaseName() string {
	if m != nil {
		return m.ReleaseName
	}
	return ""
}

type GetClusterAppValuesResponse struct {
	Status               StatusCode `protobuf:"varint,1,opt,name=status,proto3,enum=agentpb.StatusCode" json:"status,omitempty"`
	StatusMessage        string     `protobuf:"bytes,2,opt,name=statusMessage,proto3" json:"statusMessage,omitempty"`
	Values               *AppValues `protobuf:"bytes,3,opt,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetClusterAppValuesResponse) Reset()         { *m = GetClusterAppValuesResponse{} }
func (m *GetClusterAppValuesResponse) String() string { return proto.CompactTextString(m) }
func (*GetClusterAppValuesResponse) ProtoMessage()    {}
func (*GetClusterAppValuesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{21}
}

func (m *GetClusterAppValuesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetClusterAppValuesResponse.Unmarshal(m, b)
}
func (m *GetClusterAppValuesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetClusterAppValuesResponse.Marshal(b, m, deterministic)
}
func (m *GetClusterAppValuesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetClusterAppValuesResponse.Merge(m, src)
}
func (m *GetClusterAppValuesResponse) XXX_Size() int {
	return xxx_messageInfo_GetClusterAppValuesResponse.Size(m)
}
func (m *GetClusterAppValuesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetClusterAppValuesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetClusterAppValuesResponse proto.InternalMessageInfo

func (m *GetClusterAppValuesResponse) GetStatus() StatusCode {
	if m != nil {
		return m.Status
	}
	return StatusCode_OK
}

func (m *GetClusterAppValuesResponse) GetStatusMessage() string {
	if m != nil {
		return m.StatusMessage
	}
	return ""
}

func (m *GetClusterAppValuesResponse) GetValues() *AppValues {
	if m != nil {
		return m.Values
	}
	return nil
}

type GetClusterGlobalValuesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetClusterGlobalValuesRequest) Reset()         { *m = GetClusterGlobalValuesRequest{} }
func (m *GetClusterGlobalValuesRequest) String() string { return proto.CompactTextString(m) }
func (*GetClusterGlobalValuesRequest) ProtoMessage()    {}
func (*GetClusterGlobalValuesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{22}
}

func (m *GetClusterGlobalValuesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetClusterGlobalValuesRequest.Unmarshal(m, b)
}
func (m *GetClusterGlobalValuesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetClusterGlobalValuesRequest.Marshal(b, m, deterministic)
}
func (m *GetClusterGlobalValuesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetClusterGlobalValuesRequest.Merge(m, src)
}
func (m *GetClusterGlobalValuesRequest) XXX_Size() int {
	return xxx_messageInfo_GetClusterGlobalValuesRequest.Size(m)
}
func (m *GetClusterGlobalValuesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetClusterGlobalValuesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetClusterGlobalValuesRequest proto.InternalMessageInfo

type GetClusterGlobalValuesResponse struct {
	Status               StatusCode `protobuf:"varint,1,opt,name=status,proto3,enum=agentpb.StatusCode" json:"status,omitempty"`
	StatusMessage        string     `protobuf:"bytes,2,opt,name=statusMessage,proto3" json:"statusMessage,omitempty"`
	GlobalValues         []byte     `protobuf:"bytes,3,opt,name=globalValues,proto3" json:"globalValues,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetClusterGlobalValuesResponse) Reset()         { *m = GetClusterGlobalValuesResponse{} }
func (m *GetClusterGlobalValuesResponse) String() string { return proto.CompactTextString(m) }
func (*GetClusterGlobalValuesResponse) ProtoMessage()    {}
func (*GetClusterGlobalValuesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{23}
}

func (m *GetClusterGlobalValuesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetClusterGlobalValuesResponse.Unmarshal(m, b)
}
func (m *GetClusterGlobalValuesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetClusterGlobalValuesResponse.Marshal(b, m, deterministic)
}
func (m *GetClusterGlobalValuesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetClusterGlobalValuesResponse.Merge(m, src)
}
func (m *GetClusterGlobalValuesResponse) XXX_Size() int {
	return xxx_messageInfo_GetClusterGlobalValuesResponse.Size(m)
}
func (m *GetClusterGlobalValuesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetClusterGlobalValuesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetClusterGlobalValuesResponse proto.InternalMessageInfo

func (m *GetClusterGlobalValuesResponse) GetStatus() StatusCode {
	if m != nil {
		return m.Status
	}
	return StatusCode_OK
}

func (m *GetClusterGlobalValuesResponse) GetStatusMessage() string {
	if m != nil {
		return m.StatusMessage
	}
	return ""
}

func (m *GetClusterGlobalValuesResponse) GetGlobalValues() []byte {
	if m != nil {
		return m.GlobalValues
	}
	return nil
}

type InstallAppRequest struct {
	AppConfig            *AppConfig `protobuf:"bytes,1,opt,name=appConfig,proto3" json:"appConfig,omitempty"`
	AppValues            *AppValues `protobuf:"bytes,2,opt,name=appValues,proto3" json:"appValues,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *InstallAppRequest) Reset()         { *m = InstallAppRequest{} }
func (m *InstallAppRequest) String() string { return proto.CompactTextString(m) }
func (*InstallAppRequest) ProtoMessage()    {}
func (*InstallAppRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{24}
}

func (m *InstallAppRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstallAppRequest.Unmarshal(m, b)
}
func (m *InstallAppRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstallAppRequest.Marshal(b, m, deterministic)
}
func (m *InstallAppRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstallAppRequest.Merge(m, src)
}
func (m *InstallAppRequest) XXX_Size() int {
	return xxx_messageInfo_InstallAppRequest.Size(m)
}
func (m *InstallAppRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InstallAppRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InstallAppRequest proto.InternalMessageInfo

func (m *InstallAppRequest) GetAppConfig() *AppConfig {
	if m != nil {
		return m.AppConfig
	}
	return nil
}

func (m *InstallAppRequest) GetAppValues() *AppValues {
	if m != nil {
		return m.AppValues
	}
	return nil
}

type InstallAppResponse struct {
	Status               StatusCode `protobuf:"varint,1,opt,name=status,proto3,enum=agentpb.StatusCode" json:"status,omitempty"`
	StatusMessage        string     `protobuf:"bytes,2,opt,name=statusMessage,proto3" json:"statusMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *InstallAppResponse) Reset()         { *m = InstallAppResponse{} }
func (m *InstallAppResponse) String() string { return proto.CompactTextString(m) }
func (*InstallAppResponse) ProtoMessage()    {}
func (*InstallAppResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{25}
}

func (m *InstallAppResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstallAppResponse.Unmarshal(m, b)
}
func (m *InstallAppResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstallAppResponse.Marshal(b, m, deterministic)
}
func (m *InstallAppResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstallAppResponse.Merge(m, src)
}
func (m *InstallAppResponse) XXX_Size() int {
	return xxx_messageInfo_InstallAppResponse.Size(m)
}
func (m *InstallAppResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InstallAppResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InstallAppResponse proto.InternalMessageInfo

func (m *InstallAppResponse) GetStatus() StatusCode {
	if m != nil {
		return m.Status
	}
	return StatusCode_OK
}

func (m *InstallAppResponse) GetStatusMessage() string {
	if m != nil {
		return m.StatusMessage
	}
	return ""
}

type UnInstallAppRequest struct {
	ReleaseName          string   `protobuf:"bytes,2,opt,name=releaseName,proto3" json:"releaseName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnInstallAppRequest) Reset()         { *m = UnInstallAppRequest{} }
func (m *UnInstallAppRequest) String() string { return proto.CompactTextString(m) }
func (*UnInstallAppRequest) ProtoMessage()    {}
func (*UnInstallAppRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{26}
}

func (m *UnInstallAppRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnInstallAppRequest.Unmarshal(m, b)
}
func (m *UnInstallAppRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnInstallAppRequest.Marshal(b, m, deterministic)
}
func (m *UnInstallAppRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnInstallAppRequest.Merge(m, src)
}
func (m *UnInstallAppRequest) XXX_Size() int {
	return xxx_messageInfo_UnInstallAppRequest.Size(m)
}
func (m *UnInstallAppRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnInstallAppRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnInstallAppRequest proto.InternalMessageInfo

func (m *UnInstallAppRequest) GetReleaseName() string {
	if m != nil {
		return m.ReleaseName
	}
	return ""
}

type UnInstallAppResponse struct {
	Status               StatusCode `protobuf:"varint,1,opt,name=status,proto3,enum=agentpb.StatusCode" json:"status,omitempty"`
	StatusMessage        string     `protobuf:"bytes,2,opt,name=statusMessage,proto3" json:"statusMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *UnInstallAppResponse) Reset()         { *m = UnInstallAppResponse{} }
func (m *UnInstallAppResponse) String() string { return proto.CompactTextString(m) }
func (*UnInstallAppResponse) ProtoMessage()    {}
func (*UnInstallAppResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{27}
}

func (m *UnInstallAppResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnInstallAppResponse.Unmarshal(m, b)
}
func (m *UnInstallAppResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnInstallAppResponse.Marshal(b, m, deterministic)
}
func (m *UnInstallAppResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnInstallAppResponse.Merge(m, src)
}
func (m *UnInstallAppResponse) XXX_Size() int {
	return xxx_messageInfo_UnInstallAppResponse.Size(m)
}
func (m *UnInstallAppResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UnInstallAppResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UnInstallAppResponse proto.InternalMessageInfo

func (m *UnInstallAppResponse) GetStatus() StatusCode {
	if m != nil {
		return m.Status
	}
	return StatusCode_OK
}

func (m *UnInstallAppResponse) GetStatusMessage() string {
	if m != nil {
		return m.StatusMessage
	}
	return ""
}

type SyncAppData struct {
	Config               *AppConfig `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	Values               *AppValues `protobuf:"bytes,2,opt,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SyncAppData) Reset()         { *m = SyncAppData{} }
func (m *SyncAppData) String() string { return proto.CompactTextString(m) }
func (*SyncAppData) ProtoMessage()    {}
func (*SyncAppData) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{28}
}

func (m *SyncAppData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncAppData.Unmarshal(m, b)
}
func (m *SyncAppData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncAppData.Marshal(b, m, deterministic)
}
func (m *SyncAppData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncAppData.Merge(m, src)
}
func (m *SyncAppData) XXX_Size() int {
	return xxx_messageInfo_SyncAppData.Size(m)
}
func (m *SyncAppData) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncAppData.DiscardUnknown(m)
}

var xxx_messageInfo_SyncAppData proto.InternalMessageInfo

func (m *SyncAppData) GetConfig() *AppConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *SyncAppData) GetValues() *AppValues {
	if m != nil {
		return m.Values
	}
	return nil
}

type AppData struct {
	Config               *AppConfig `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	Status               *AppStatus `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AppData) Reset()         { *m = AppData{} }
func (m *AppData) String() string { return proto.CompactTextString(m) }
func (*AppData) ProtoMessage()    {}
func (*AppData) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{29}
}

func (m *AppData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppData.Unmarshal(m, b)
}
func (m *AppData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppData.Marshal(b, m, deterministic)
}
func (m *AppData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppData.Merge(m, src)
}
func (m *AppData) XXX_Size() int {
	return xxx_messageInfo_AppData.Size(m)
}
func (m *AppData) XXX_DiscardUnknown() {
	xxx_messageInfo_AppData.DiscardUnknown(m)
}

var xxx_messageInfo_AppData proto.InternalMessageInfo

func (m *AppData) GetConfig() *AppConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *AppData) GetStatus() *AppStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type AppStatus struct {
	RuntimeStatus        string   `protobuf:"bytes,1,opt,name=runtimeStatus,proto3" json:"runtimeStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppStatus) Reset()         { *m = AppStatus{} }
func (m *AppStatus) String() string { return proto.CompactTextString(m) }
func (*AppStatus) ProtoMessage()    {}
func (*AppStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{30}
}

func (m *AppStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppStatus.Unmarshal(m, b)
}
func (m *AppStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppStatus.Marshal(b, m, deterministic)
}
func (m *AppStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppStatus.Merge(m, src)
}
func (m *AppStatus) XXX_Size() int {
	return xxx_messageInfo_AppStatus.Size(m)
}
func (m *AppStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_AppStatus.DiscardUnknown(m)
}

var xxx_messageInfo_AppStatus proto.InternalMessageInfo

func (m *AppStatus) GetRuntimeStatus() string {
	if m != nil {
		return m.RuntimeStatus
	}
	return ""
}

type AppConfig struct {
	ReleaseName          string   `protobuf:"bytes,1,opt,name=releaseName,proto3" json:"releaseName,omitempty"`
	AppName              string   `protobuf:"bytes,2,opt,name=appName,proto3" json:"appName,omitempty"`
	Version              string   `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Category             string   `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Description          string   `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	ChartName            string   `protobuf:"bytes,6,opt,name=chartName,proto3" json:"chartName,omitempty"`
	RepoName             string   `protobuf:"bytes,7,opt,name=repoName,proto3" json:"repoName,omitempty"`
	RepoURL              string   `protobuf:"bytes,8,opt,name=repoURL,proto3" json:"repoURL,omitempty"`
	Namespace            string   `protobuf:"bytes,9,opt,name=namespace,proto3" json:"namespace,omitempty"`
	CreateNamespace      bool     `protobuf:"varint,10,opt,name=createNamespace,proto3" json:"createNamespace,omitempty"`
	PrivilegedNamespace  bool     `protobuf:"varint,11,opt,name=privilegedNamespace,proto3" json:"privilegedNamespace,omitempty"`
	Icon                 []byte   `protobuf:"bytes,12,opt,name=icon,proto3" json:"icon,omitempty"`
	LaunchURL            string   `protobuf:"bytes,13,opt,name=launchURL,proto3" json:"launchURL,omitempty"`
	LaunchUIDescription  string   `protobuf:"bytes,14,opt,name=launchUIDescription,proto3" json:"launchUIDescription,omitempty"`
	InstallStatus        string   `protobuf:"bytes,15,opt,name=installStatus,proto3" json:"installStatus,omitempty"`
	RuntimeStatus        string   `protobuf:"bytes,16,opt,name=runtimeStatus,proto3" json:"runtimeStatus,omitempty"`
	DefualtApp           bool     `protobuf:"varint,17,opt,name=defualtApp,proto3" json:"defualtApp,omitempty"`
	LastUpdateTime       string   `protobuf:"bytes,18,opt,name=lastUpdateTime,proto3" json:"lastUpdateTime,omitempty"`
	PluginName           string   `protobuf:"bytes,19,opt,name=pluginName,proto3" json:"pluginName,omitempty"`
	PluginDescription    string   `protobuf:"bytes,20,opt,name=pluginDescription,proto3" json:"pluginDescription,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppConfig) Reset()         { *m = AppConfig{} }
func (m *AppConfig) String() string { return proto.CompactTextString(m) }
func (*AppConfig) ProtoMessage()    {}
func (*AppConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{31}
}

func (m *AppConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppConfig.Unmarshal(m, b)
}
func (m *AppConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppConfig.Marshal(b, m, deterministic)
}
func (m *AppConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppConfig.Merge(m, src)
}
func (m *AppConfig) XXX_Size() int {
	return xxx_messageInfo_AppConfig.Size(m)
}
func (m *AppConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_AppConfig.DiscardUnknown(m)
}

var xxx_messageInfo_AppConfig proto.InternalMessageInfo

func (m *AppConfig) GetReleaseName() string {
	if m != nil {
		return m.ReleaseName
	}
	return ""
}

func (m *AppConfig) GetAppName() string {
	if m != nil {
		return m.AppName
	}
	return ""
}

func (m *AppConfig) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *AppConfig) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *AppConfig) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *AppConfig) GetChartName() string {
	if m != nil {
		return m.ChartName
	}
	return ""
}

func (m *AppConfig) GetRepoName() string {
	if m != nil {
		return m.RepoName
	}
	return ""
}

func (m *AppConfig) GetRepoURL() string {
	if m != nil {
		return m.RepoURL
	}
	return ""
}

func (m *AppConfig) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *AppConfig) GetCreateNamespace() bool {
	if m != nil {
		return m.CreateNamespace
	}
	return false
}

func (m *AppConfig) GetPrivilegedNamespace() bool {
	if m != nil {
		return m.PrivilegedNamespace
	}
	return false
}

func (m *AppConfig) GetIcon() []byte {
	if m != nil {
		return m.Icon
	}
	return nil
}

func (m *AppConfig) GetLaunchURL() string {
	if m != nil {
		return m.LaunchURL
	}
	return ""
}

func (m *AppConfig) GetLaunchUIDescription() string {
	if m != nil {
		return m.LaunchUIDescription
	}
	return ""
}

func (m *AppConfig) GetInstallStatus() string {
	if m != nil {
		return m.InstallStatus
	}
	return ""
}

func (m *AppConfig) GetRuntimeStatus() string {
	if m != nil {
		return m.RuntimeStatus
	}
	return ""
}

func (m *AppConfig) GetDefualtApp() bool {
	if m != nil {
		return m.DefualtApp
	}
	return false
}

func (m *AppConfig) GetLastUpdateTime() string {
	if m != nil {
		return m.LastUpdateTime
	}
	return ""
}

func (m *AppConfig) GetPluginName() string {
	if m != nil {
		return m.PluginName
	}
	return ""
}

func (m *AppConfig) GetPluginDescription() string {
	if m != nil {
		return m.PluginDescription
	}
	return ""
}

type AppValues struct {
	OverrideValues       []byte   `protobuf:"bytes,1,opt,name=overrideValues,proto3" json:"overrideValues,omitempty"`
	LaunchUIValues       []byte   `protobuf:"bytes,2,opt,name=launchUIValues,proto3" json:"launchUIValues,omitempty"`
	TemplateValues       []byte   `protobuf:"bytes,3,opt,name=templateValues,proto3" json:"templateValues,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppValues) Reset()         { *m = AppValues{} }
func (m *AppValues) String() string { return proto.CompactTextString(m) }
func (*AppValues) ProtoMessage()    {}
func (*AppValues) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{32}
}

func (m *AppValues) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppValues.Unmarshal(m, b)
}
func (m *AppValues) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppValues.Marshal(b, m, deterministic)
}
func (m *AppValues) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppValues.Merge(m, src)
}
func (m *AppValues) XXX_Size() int {
	return xxx_messageInfo_AppValues.Size(m)
}
func (m *AppValues) XXX_DiscardUnknown() {
	xxx_messageInfo_AppValues.DiscardUnknown(m)
}

var xxx_messageInfo_AppValues proto.InternalMessageInfo

func (m *AppValues) GetOverrideValues() []byte {
	if m != nil {
		return m.OverrideValues
	}
	return nil
}

func (m *AppValues) GetLaunchUIValues() []byte {
	if m != nil {
		return m.LaunchUIValues
	}
	return nil
}

func (m *AppValues) GetTemplateValues() []byte {
	if m != nil {
		return m.TemplateValues
	}
	return nil
}

type AppLaunchConfig struct {
	ReleaseName          string   `protobuf:"bytes,1,opt,name=releaseName,proto3" json:"releaseName,omitempty"`
	Category             string   `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Icon                 []byte   `protobuf:"bytes,4,opt,name=icon,proto3" json:"icon,omitempty"`
	LaunchURL            string   `protobuf:"bytes,5,opt,name=launchURL,proto3" json:"launchURL,omitempty"`
	LaunchUIDescription  string   `protobuf:"bytes,6,opt,name=launchUIDescription,proto3" json:"launchUIDescription,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppLaunchConfig) Reset()         { *m = AppLaunchConfig{} }
func (m *AppLaunchConfig) String() string { return proto.CompactTextString(m) }
func (*AppLaunchConfig) ProtoMessage()    {}
func (*AppLaunchConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{33}
}

func (m *AppLaunchConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppLaunchConfig.Unmarshal(m, b)
}
func (m *AppLaunchConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppLaunchConfig.Marshal(b, m, deterministic)
}
func (m *AppLaunchConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppLaunchConfig.Merge(m, src)
}
func (m *AppLaunchConfig) XXX_Size() int {
	return xxx_messageInfo_AppLaunchConfig.Size(m)
}
func (m *AppLaunchConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_AppLaunchConfig.DiscardUnknown(m)
}

var xxx_messageInfo_AppLaunchConfig proto.InternalMessageInfo

func (m *AppLaunchConfig) GetReleaseName() string {
	if m != nil {
		return m.ReleaseName
	}
	return ""
}

func (m *AppLaunchConfig) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *AppLaunchConfig) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *AppLaunchConfig) GetIcon() []byte {
	if m != nil {
		return m.Icon
	}
	return nil
}

func (m *AppLaunchConfig) GetLaunchURL() string {
	if m != nil {
		return m.LaunchURL
	}
	return ""
}

func (m *AppLaunchConfig) GetLaunchUIDescription() string {
	if m != nil {
		return m.LaunchUIDescription
	}
	return ""
}

type UpgradeAppRequest struct {
	AppConfig            *AppConfig `protobuf:"bytes,1,opt,name=appConfig,proto3" json:"appConfig,omitempty"`
	AppValues            *AppValues `protobuf:"bytes,2,opt,name=appValues,proto3" json:"appValues,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *UpgradeAppRequest) Reset()         { *m = UpgradeAppRequest{} }
func (m *UpgradeAppRequest) String() string { return proto.CompactTextString(m) }
func (*UpgradeAppRequest) ProtoMessage()    {}
func (*UpgradeAppRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{34}
}

func (m *UpgradeAppRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpgradeAppRequest.Unmarshal(m, b)
}
func (m *UpgradeAppRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpgradeAppRequest.Marshal(b, m, deterministic)
}
func (m *UpgradeAppRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpgradeAppRequest.Merge(m, src)
}
func (m *UpgradeAppRequest) XXX_Size() int {
	return xxx_messageInfo_UpgradeAppRequest.Size(m)
}
func (m *UpgradeAppRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpgradeAppRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpgradeAppRequest proto.InternalMessageInfo

func (m *UpgradeAppRequest) GetAppConfig() *AppConfig {
	if m != nil {
		return m.AppConfig
	}
	return nil
}

func (m *UpgradeAppRequest) GetAppValues() *AppValues {
	if m != nil {
		return m.AppValues
	}
	return nil
}

type UpgradeAppResponse struct {
	Status               StatusCode `protobuf:"varint,1,opt,name=status,proto3,enum=agentpb.StatusCode" json:"status,omitempty"`
	StatusMessage        string     `protobuf:"bytes,2,opt,name=statusMessage,proto3" json:"statusMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *UpgradeAppResponse) Reset()         { *m = UpgradeAppResponse{} }
func (m *UpgradeAppResponse) String() string { return proto.CompactTextString(m) }
func (*UpgradeAppResponse) ProtoMessage()    {}
func (*UpgradeAppResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{35}
}

func (m *UpgradeAppResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpgradeAppResponse.Unmarshal(m, b)
}
func (m *UpgradeAppResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpgradeAppResponse.Marshal(b, m, deterministic)
}
func (m *UpgradeAppResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpgradeAppResponse.Merge(m, src)
}
func (m *UpgradeAppResponse) XXX_Size() int {
	return xxx_messageInfo_UpgradeAppResponse.Size(m)
}
func (m *UpgradeAppResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpgradeAppResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpgradeAppResponse proto.InternalMessageInfo

func (m *UpgradeAppResponse) GetStatus() StatusCode {
	if m != nil {
		return m.Status
	}
	return StatusCode_OK
}

func (m *UpgradeAppResponse) GetStatusMessage() string {
	if m != nil {
		return m.StatusMessage
	}
	return ""
}

type UpdateAppValuesRequest struct {
	ReleaseName          string   `protobuf:"bytes,1,opt,name=releaseName,proto3" json:"releaseName,omitempty"`
	OverrideValues       []byte   `protobuf:"bytes,3,opt,name=overrideValues,proto3" json:"overrideValues,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateAppValuesRequest) Reset()         { *m = UpdateAppValuesRequest{} }
func (m *UpdateAppValuesRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateAppValuesRequest) ProtoMessage()    {}
func (*UpdateAppValuesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{36}
}

func (m *UpdateAppValuesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAppValuesRequest.Unmarshal(m, b)
}
func (m *UpdateAppValuesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAppValuesRequest.Marshal(b, m, deterministic)
}
func (m *UpdateAppValuesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAppValuesRequest.Merge(m, src)
}
func (m *UpdateAppValuesRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateAppValuesRequest.Size(m)
}
func (m *UpdateAppValuesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAppValuesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAppValuesRequest proto.InternalMessageInfo

func (m *UpdateAppValuesRequest) GetReleaseName() string {
	if m != nil {
		return m.ReleaseName
	}
	return ""
}

func (m *UpdateAppValuesRequest) GetOverrideValues() []byte {
	if m != nil {
		return m.OverrideValues
	}
	return nil
}

type UpdateAppValuesResponse struct {
	Status               StatusCode `protobuf:"varint,1,opt,name=status,proto3,enum=agentpb.StatusCode" json:"status,omitempty"`
	StatusMessage        string     `protobuf:"bytes,2,opt,name=statusMessage,proto3" json:"statusMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *UpdateAppValuesResponse) Reset()         { *m = UpdateAppValuesResponse{} }
func (m *UpdateAppValuesResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateAppValuesResponse) ProtoMessage()    {}
func (*UpdateAppValuesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{37}
}

func (m *UpdateAppValuesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAppValuesResponse.Unmarshal(m, b)
}
func (m *UpdateAppValuesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAppValuesResponse.Marshal(b, m, deterministic)
}
func (m *UpdateAppValuesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAppValuesResponse.Merge(m, src)
}
func (m *UpdateAppValuesResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateAppValuesResponse.Size(m)
}
func (m *UpdateAppValuesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAppValuesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAppValuesResponse proto.InternalMessageInfo

func (m *UpdateAppValuesResponse) GetStatus() StatusCode {
	if m != nil {
		return m.Status
	}
	return StatusCode_OK
}

func (m *UpdateAppValuesResponse) GetStatusMessage() string {
	if m != nil {
		return m.StatusMessage
	}
	return ""
}

type ConfigureVaultSecretRequest struct {
	SecretPath           string   `protobuf:"bytes,1,opt,name=secretPath,proto3" json:"secretPath,omitempty"`
	Namespace            string   `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	SecretName           string   `protobuf:"bytes,3,opt,name=secretName,proto3" json:"secretName,omitempty"`
	ManagedClusterId     string   `protobuf:"bytes,4,opt,name=managedClusterId,proto3" json:"managedClusterId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigureVaultSecretRequest) Reset()         { *m = ConfigureVaultSecretRequest{} }
func (m *ConfigureVaultSecretRequest) String() string { return proto.CompactTextString(m) }
func (*ConfigureVaultSecretRequest) ProtoMessage()    {}
func (*ConfigureVaultSecretRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{38}
}

func (m *ConfigureVaultSecretRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigureVaultSecretRequest.Unmarshal(m, b)
}
func (m *ConfigureVaultSecretRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigureVaultSecretRequest.Marshal(b, m, deterministic)
}
func (m *ConfigureVaultSecretRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigureVaultSecretRequest.Merge(m, src)
}
func (m *ConfigureVaultSecretRequest) XXX_Size() int {
	return xxx_messageInfo_ConfigureVaultSecretRequest.Size(m)
}
func (m *ConfigureVaultSecretRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigureVaultSecretRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigureVaultSecretRequest proto.InternalMessageInfo

func (m *ConfigureVaultSecretRequest) GetSecretPath() string {
	if m != nil {
		return m.SecretPath
	}
	return ""
}

func (m *ConfigureVaultSecretRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *ConfigureVaultSecretRequest) GetSecretName() string {
	if m != nil {
		return m.SecretName
	}
	return ""
}

func (m *ConfigureVaultSecretRequest) GetManagedClusterId() string {
	if m != nil {
		return m.ManagedClusterId
	}
	return ""
}

type SecretPolicy struct {
	SecretPath           string       `protobuf:"bytes,1,opt,name=secretPath,proto3" json:"secretPath,omitempty"`
	Access               SecretAccess `protobuf:"varint,2,opt,name=access,proto3,enum=agentpb.SecretAccess" json:"access,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SecretPolicy) Reset()         { *m = SecretPolicy{} }
func (m *SecretPolicy) String() string { return proto.CompactTextString(m) }
func (*SecretPolicy) ProtoMessage()    {}
func (*SecretPolicy) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{39}
}

func (m *SecretPolicy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SecretPolicy.Unmarshal(m, b)
}
func (m *SecretPolicy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SecretPolicy.Marshal(b, m, deterministic)
}
func (m *SecretPolicy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SecretPolicy.Merge(m, src)
}
func (m *SecretPolicy) XXX_Size() int {
	return xxx_messageInfo_SecretPolicy.Size(m)
}
func (m *SecretPolicy) XXX_DiscardUnknown() {
	xxx_messageInfo_SecretPolicy.DiscardUnknown(m)
}

var xxx_messageInfo_SecretPolicy proto.InternalMessageInfo

func (m *SecretPolicy) GetSecretPath() string {
	if m != nil {
		return m.SecretPath
	}
	return ""
}

func (m *SecretPolicy) GetAccess() SecretAccess {
	if m != nil {
		return m.Access
	}
	return SecretAccess_READ
}

type ConfigureVaultSecretResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigureVaultSecretResponse) Reset()         { *m = ConfigureVaultSecretResponse{} }
func (m *ConfigureVaultSecretResponse) String() string { return proto.CompactTextString(m) }
func (*ConfigureVaultSecretResponse) ProtoMessage()    {}
func (*ConfigureVaultSecretResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{40}
}

func (m *ConfigureVaultSecretResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigureVaultSecretResponse.Unmarshal(m, b)
}
func (m *ConfigureVaultSecretResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigureVaultSecretResponse.Marshal(b, m, deterministic)
}
func (m *ConfigureVaultSecretResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigureVaultSecretResponse.Merge(m, src)
}
func (m *ConfigureVaultSecretResponse) XXX_Size() int {
	return xxx_messageInfo_ConfigureVaultSecretResponse.Size(m)
}
func (m *ConfigureVaultSecretResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigureVaultSecretResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigureVaultSecretResponse proto.InternalMessageInfo

type CreateVaultRoleRequest struct {
	RoleName             string          `protobuf:"bytes,1,opt,name=roleName,proto3" json:"roleName,omitempty"`
	SecretPolicy         []*SecretPolicy `protobuf:"bytes,2,rep,name=secretPolicy,proto3" json:"secretPolicy,omitempty"`
	ManagedClusterId     string          `protobuf:"bytes,3,opt,name=managedClusterId,proto3" json:"managedClusterId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CreateVaultRoleRequest) Reset()         { *m = CreateVaultRoleRequest{} }
func (m *CreateVaultRoleRequest) String() string { return proto.CompactTextString(m) }
func (*CreateVaultRoleRequest) ProtoMessage()    {}
func (*CreateVaultRoleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{41}
}

func (m *CreateVaultRoleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateVaultRoleRequest.Unmarshal(m, b)
}
func (m *CreateVaultRoleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateVaultRoleRequest.Marshal(b, m, deterministic)
}
func (m *CreateVaultRoleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateVaultRoleRequest.Merge(m, src)
}
func (m *CreateVaultRoleRequest) XXX_Size() int {
	return xxx_messageInfo_CreateVaultRoleRequest.Size(m)
}
func (m *CreateVaultRoleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateVaultRoleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateVaultRoleRequest proto.InternalMessageInfo

func (m *CreateVaultRoleRequest) GetRoleName() string {
	if m != nil {
		return m.RoleName
	}
	return ""
}

func (m *CreateVaultRoleRequest) GetSecretPolicy() []*SecretPolicy {
	if m != nil {
		return m.SecretPolicy
	}
	return nil
}

func (m *CreateVaultRoleRequest) GetManagedClusterId() string {
	if m != nil {
		return m.ManagedClusterId
	}
	return ""
}

type CreateVaultRoleResponse struct {
	Status               StatusCode `protobuf:"varint,1,opt,name=status,proto3,enum=agentpb.StatusCode" json:"status,omitempty"`
	StatusMessage        string     `protobuf:"bytes,2,opt,name=statusMessage,proto3" json:"statusMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CreateVaultRoleResponse) Reset()         { *m = CreateVaultRoleResponse{} }
func (m *CreateVaultRoleResponse) String() string { return proto.CompactTextString(m) }
func (*CreateVaultRoleResponse) ProtoMessage()    {}
func (*CreateVaultRoleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{42}
}

func (m *CreateVaultRoleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateVaultRoleResponse.Unmarshal(m, b)
}
func (m *CreateVaultRoleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateVaultRoleResponse.Marshal(b, m, deterministic)
}
func (m *CreateVaultRoleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateVaultRoleResponse.Merge(m, src)
}
func (m *CreateVaultRoleResponse) XXX_Size() int {
	return xxx_messageInfo_CreateVaultRoleResponse.Size(m)
}
func (m *CreateVaultRoleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateVaultRoleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateVaultRoleResponse proto.InternalMessageInfo

func (m *CreateVaultRoleResponse) GetStatus() StatusCode {
	if m != nil {
		return m.Status
	}
	return StatusCode_OK
}

func (m *CreateVaultRoleResponse) GetStatusMessage() string {
	if m != nil {
		return m.StatusMessage
	}
	return ""
}

type UpdateVaultRoleRequest struct {
	RoleName             string          `protobuf:"bytes,1,opt,name=roleName,proto3" json:"roleName,omitempty"`
	SecretPolicy         []*SecretPolicy `protobuf:"bytes,2,rep,name=secretPolicy,proto3" json:"secretPolicy,omitempty"`
	ManagedClusterId     string          `protobuf:"bytes,3,opt,name=managedClusterId,proto3" json:"managedClusterId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UpdateVaultRoleRequest) Reset()         { *m = UpdateVaultRoleRequest{} }
func (m *UpdateVaultRoleRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateVaultRoleRequest) ProtoMessage()    {}
func (*UpdateVaultRoleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{43}
}

func (m *UpdateVaultRoleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateVaultRoleRequest.Unmarshal(m, b)
}
func (m *UpdateVaultRoleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateVaultRoleRequest.Marshal(b, m, deterministic)
}
func (m *UpdateVaultRoleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateVaultRoleRequest.Merge(m, src)
}
func (m *UpdateVaultRoleRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateVaultRoleRequest.Size(m)
}
func (m *UpdateVaultRoleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateVaultRoleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateVaultRoleRequest proto.InternalMessageInfo

func (m *UpdateVaultRoleRequest) GetRoleName() string {
	if m != nil {
		return m.RoleName
	}
	return ""
}

func (m *UpdateVaultRoleRequest) GetSecretPolicy() []*SecretPolicy {
	if m != nil {
		return m.SecretPolicy
	}
	return nil
}

func (m *UpdateVaultRoleRequest) GetManagedClusterId() string {
	if m != nil {
		return m.ManagedClusterId
	}
	return ""
}

type UpdateVaultRoleResponse struct {
	Status               StatusCode `protobuf:"varint,1,opt,name=status,proto3,enum=agentpb.StatusCode" json:"status,omitempty"`
	StatusMessage        string     `protobuf:"bytes,2,opt,name=statusMessage,proto3" json:"statusMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *UpdateVaultRoleResponse) Reset()         { *m = UpdateVaultRoleResponse{} }
func (m *UpdateVaultRoleResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateVaultRoleResponse) ProtoMessage()    {}
func (*UpdateVaultRoleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{44}
}

func (m *UpdateVaultRoleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateVaultRoleResponse.Unmarshal(m, b)
}
func (m *UpdateVaultRoleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateVaultRoleResponse.Marshal(b, m, deterministic)
}
func (m *UpdateVaultRoleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateVaultRoleResponse.Merge(m, src)
}
func (m *UpdateVaultRoleResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateVaultRoleResponse.Size(m)
}
func (m *UpdateVaultRoleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateVaultRoleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateVaultRoleResponse proto.InternalMessageInfo

func (m *UpdateVaultRoleResponse) GetStatus() StatusCode {
	if m != nil {
		return m.Status
	}
	return StatusCode_OK
}

func (m *UpdateVaultRoleResponse) GetStatusMessage() string {
	if m != nil {
		return m.StatusMessage
	}
	return ""
}

type DeleteVaultRoleRequest struct {
	RoleName             string   `protobuf:"bytes,1,opt,name=roleName,proto3" json:"roleName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteVaultRoleRequest) Reset()         { *m = DeleteVaultRoleRequest{} }
func (m *DeleteVaultRoleRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteVaultRoleRequest) ProtoMessage()    {}
func (*DeleteVaultRoleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{45}
}

func (m *DeleteVaultRoleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteVaultRoleRequest.Unmarshal(m, b)
}
func (m *DeleteVaultRoleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteVaultRoleRequest.Marshal(b, m, deterministic)
}
func (m *DeleteVaultRoleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteVaultRoleRequest.Merge(m, src)
}
func (m *DeleteVaultRoleRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteVaultRoleRequest.Size(m)
}
func (m *DeleteVaultRoleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteVaultRoleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteVaultRoleRequest proto.InternalMessageInfo

func (m *DeleteVaultRoleRequest) GetRoleName() string {
	if m != nil {
		return m.RoleName
	}
	return ""
}

type DeleteVaultRoleResponse struct {
	Status               StatusCode `protobuf:"varint,1,opt,name=status,proto3,enum=agentpb.StatusCode" json:"status,omitempty"`
	StatusMessage        string     `protobuf:"bytes,2,opt,name=statusMessage,proto3" json:"statusMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *DeleteVaultRoleResponse) Reset()         { *m = DeleteVaultRoleResponse{} }
func (m *DeleteVaultRoleResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteVaultRoleResponse) ProtoMessage()    {}
func (*DeleteVaultRoleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{46}
}

func (m *DeleteVaultRoleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteVaultRoleResponse.Unmarshal(m, b)
}
func (m *DeleteVaultRoleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteVaultRoleResponse.Marshal(b, m, deterministic)
}
func (m *DeleteVaultRoleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteVaultRoleResponse.Merge(m, src)
}
func (m *DeleteVaultRoleResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteVaultRoleResponse.Size(m)
}
func (m *DeleteVaultRoleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteVaultRoleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteVaultRoleResponse proto.InternalMessageInfo

func (m *DeleteVaultRoleResponse) GetStatus() StatusCode {
	if m != nil {
		return m.Status
	}
	return StatusCode_OK
}

func (m *DeleteVaultRoleResponse) GetStatusMessage() string {
	if m != nil {
		return m.StatusMessage
	}
	return ""
}

func init() {
	proto.RegisterEnum("agentpb.StatusCode", StatusCode_name, StatusCode_value)
	proto.RegisterEnum("agentpb.SecretAccess", SecretAccess_name, SecretAccess_value)
	proto.RegisterType((*PingRequest)(nil), "agentpb.PingRequest")
	proto.RegisterType((*PingResponse)(nil), "agentpb.PingResponse")
	proto.RegisterType((*StoreCredentialRequest)(nil), "agentpb.StoreCredentialRequest")
	proto.RegisterMapType((map[string]string)(nil), "agentpb.StoreCredentialRequest.CredentialEntry")
	proto.RegisterType((*StoreCredentialResponse)(nil), "agentpb.StoreCredentialResponse")
	proto.RegisterType((*ClusterRequest)(nil), "agentpb.ClusterRequest")
	proto.RegisterType((*RepositoryAddRequest)(nil), "agentpb.RepositoryAddRequest")
	proto.RegisterType((*RepositoryDeleteRequest)(nil), "agentpb.RepositoryDeleteRequest")
	proto.RegisterType((*ProjectAddRequest)(nil), "agentpb.ProjectAddRequest")
	proto.RegisterType((*ProjectDeleteRequest)(nil), "agentpb.ProjectDeleteRequest")
	proto.RegisterType((*JobResponse)(nil), "agentpb.JobResponse")
	proto.RegisterType((*SyncAppRequest)(nil), "agentpb.SyncAppRequest")
	proto.RegisterType((*SyncAppResponse)(nil), "agentpb.SyncAppResponse")
	proto.RegisterType((*GetClusterAppsRequest)(nil), "agentpb.GetClusterAppsRequest")
	proto.RegisterType((*GetClusterAppsResponse)(nil), "agentpb.GetClusterAppsResponse")
	proto.RegisterType((*GetClusterAppLaunchesRequest)(nil), "agentpb.GetClusterAppLaunchesRequest")
	proto.RegisterType((*GetClusterAppLaunchesResponse)(nil), "agentpb.GetClusterAppLaunchesResponse")
	proto.RegisterType((*ConfigureAppSSORequest)(nil), "agentpb.ConfigureAppSSORequest")
	proto.RegisterType((*ConfigureAppSSOResponse)(nil), "agentpb.ConfigureAppSSOResponse")
	proto.RegisterType((*GetClusterAppConfigRequest)(nil), "agentpb.GetClusterAppConfigRequest")
	proto.RegisterType((*GetClusterAppConfigResponse)(nil), "agentpb.GetClusterAppConfigResponse")
	proto.RegisterType((*GetClusterAppValuesRequest)(nil), "agentpb.GetClusterAppValuesRequest")
	proto.RegisterType((*GetClusterAppValuesResponse)(nil), "agentpb.GetClusterAppValuesResponse")
	proto.RegisterType((*GetClusterGlobalValuesRequest)(nil), "agentpb.GetClusterGlobalValuesRequest")
	proto.RegisterType((*GetClusterGlobalValuesResponse)(nil), "agentpb.GetClusterGlobalValuesResponse")
	proto.RegisterType((*InstallAppRequest)(nil), "agentpb.InstallAppRequest")
	proto.RegisterType((*InstallAppResponse)(nil), "agentpb.InstallAppResponse")
	proto.RegisterType((*UnInstallAppRequest)(nil), "agentpb.UnInstallAppRequest")
	proto.RegisterType((*UnInstallAppResponse)(nil), "agentpb.UnInstallAppResponse")
	proto.RegisterType((*SyncAppData)(nil), "agentpb.SyncAppData")
	proto.RegisterType((*AppData)(nil), "agentpb.AppData")
	proto.RegisterType((*AppStatus)(nil), "agentpb.AppStatus")
	proto.RegisterType((*AppConfig)(nil), "agentpb.AppConfig")
	proto.RegisterType((*AppValues)(nil), "agentpb.AppValues")
	proto.RegisterType((*AppLaunchConfig)(nil), "agentpb.AppLaunchConfig")
	proto.RegisterType((*UpgradeAppRequest)(nil), "agentpb.UpgradeAppRequest")
	proto.RegisterType((*UpgradeAppResponse)(nil), "agentpb.UpgradeAppResponse")
	proto.RegisterType((*UpdateAppValuesRequest)(nil), "agentpb.UpdateAppValuesRequest")
	proto.RegisterType((*UpdateAppValuesResponse)(nil), "agentpb.UpdateAppValuesResponse")
	proto.RegisterType((*ConfigureVaultSecretRequest)(nil), "agentpb.ConfigureVaultSecretRequest")
	proto.RegisterType((*SecretPolicy)(nil), "agentpb.secretPolicy")
	proto.RegisterType((*ConfigureVaultSecretResponse)(nil), "agentpb.ConfigureVaultSecretResponse")
	proto.RegisterType((*CreateVaultRoleRequest)(nil), "agentpb.CreateVaultRoleRequest")
	proto.RegisterType((*CreateVaultRoleResponse)(nil), "agentpb.CreateVaultRoleResponse")
	proto.RegisterType((*UpdateVaultRoleRequest)(nil), "agentpb.UpdateVaultRoleRequest")
	proto.RegisterType((*UpdateVaultRoleResponse)(nil), "agentpb.UpdateVaultRoleResponse")
	proto.RegisterType((*DeleteVaultRoleRequest)(nil), "agentpb.DeleteVaultRoleRequest")
	proto.RegisterType((*DeleteVaultRoleResponse)(nil), "agentpb.DeleteVaultRoleResponse")
}

func init() { proto.RegisterFile("agent.proto", fileDescriptor_56ede974c0020f77) }

var fileDescriptor_56ede974c0020f77 = []byte{
	// 1762 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x59, 0x5b, 0x6f, 0x23, 0x49,
	0x15, 0x8e, 0xed, 0xdc, 0x7c, 0xec, 0x71, 0x3c, 0x15, 0x4f, 0xa6, 0xf1, 0xcc, 0x26, 0xd9, 0xde,
	0xd9, 0x25, 0x0a, 0x90, 0x5d, 0x02, 0x08, 0x58, 0xc4, 0x4a, 0xde, 0x38, 0x44, 0x06, 0x8f, 0x13,
	0xb5, 0x73, 0x91, 0x56, 0x42, 0x51, 0xa5, 0xbb, 0xe2, 0x34, 0xd3, 0xe9, 0x6e, 0xba, 0xcb, 0x19,
	0xf9, 0x99, 0x1f, 0xc1, 0x03, 0x08, 0x21, 0x5e, 0xf8, 0x01, 0xbc, 0xf0, 0x1b, 0x78, 0xe7, 0xff,
	0xa0, 0xba, 0x74, 0x77, 0xf5, 0x6d, 0x9c, 0xac, 0x30, 0xe2, 0xcd, 0x75, 0xea, 0xd4, 0xb9, 0xd5,
	0x77, 0x4e, 0x9f, 0x3a, 0x86, 0x06, 0x9e, 0x10, 0x97, 0x1e, 0xf8, 0x81, 0x47, 0x3d, 0xb4, 0xc6,
	0x17, 0xfe, 0x8d, 0xfe, 0x0c, 0x1a, 0x67, 0xb6, 0x3b, 0x31, 0xc8, 0xef, 0xa7, 0x24, 0xa4, 0xfa,
	0x2f, 0xa0, 0x29, 0x96, 0xa1, 0xef, 0xb9, 0x21, 0x41, 0xdf, 0x83, 0xd5, 0x90, 0x62, 0x3a, 0x0d,
	0xb5, 0xca, 0x6e, 0x65, 0xaf, 0x75, 0xb8, 0x79, 0x20, 0x0f, 0x1e, 0x8c, 0x39, 0xf9, 0xc8, 0xb3,
	0x88, 0x21, 0x59, 0xf4, 0xbf, 0x56, 0x61, 0x6b, 0x4c, 0xbd, 0x80, 0x1c, 0x05, 0xc4, 0x22, 0x2e,
	0xb5, 0xb1, 0x23, 0xe5, 0xa2, 0xcf, 0xa0, 0x65, 0xc6, 0xc4, 0xf3, 0x99, 0x4f, 0xb8, 0xbc, 0xba,
	0x91, 0xa1, 0x46, 0x7c, 0xc7, 0x2e, 0xb5, 0xe9, 0x6c, 0x84, 0xef, 0x89, 0x56, 0x4d, 0xf8, 0x12,
	0x6a, 0xc4, 0x37, 0xe0, 0x67, 0x6f, 0x6d, 0x12, 0x68, 0xb5, 0x84, 0x2f, 0xa1, 0xa2, 0x53, 0x80,
	0x44, 0x83, 0xb6, 0xbc, 0x5b, 0xdb, 0x6b, 0x1c, 0x7e, 0xae, 0xf8, 0x50, 0x64, 0xec, 0x41, 0x42,
	0x39, 0x76, 0x69, 0x30, 0x33, 0x14, 0x11, 0xdd, 0x5f, 0xc2, 0x46, 0x66, 0x1b, 0xb5, 0xa1, 0xf6,
	0x8e, 0xcc, 0xa4, 0x43, 0xec, 0x27, 0xea, 0xc0, 0xca, 0x03, 0x76, 0xa6, 0x91, 0xf1, 0x62, 0xf1,
	0x65, 0xf5, 0x67, 0x15, 0xdd, 0x81, 0x97, 0x39, 0xa5, 0xdf, 0x22, 0xd4, 0xe8, 0x0d, 0x3c, 0x13,
	0xbf, 0xde, 0x92, 0x30, 0xc4, 0x93, 0x48, 0x53, 0x9a, 0xa8, 0x9f, 0x43, 0xeb, 0xc8, 0x99, 0x86,
	0x94, 0x04, 0xd1, 0x3d, 0xec, 0x40, 0xc3, 0x77, 0xa6, 0x13, 0xdb, 0xbd, 0x76, 0x59, 0x70, 0x85,
	0xcd, 0x20, 0x48, 0x3c, 0xb0, 0x1f, 0x43, 0xd3, 0x14, 0x47, 0x04, 0x87, 0x90, 0xdb, 0x90, 0x34,
	0xc6, 0xa2, 0x7b, 0xd0, 0x31, 0x88, 0xef, 0x85, 0x36, 0xf5, 0x82, 0x59, 0xcf, 0xb2, 0x1e, 0x2d,
	0xfb, 0x15, 0xd4, 0x03, 0xe2, 0x7b, 0xaa, 0xe0, 0x75, 0x46, 0xe0, 0x9b, 0xdf, 0x01, 0xfe, 0xfb,
	0x7a, 0x1a, 0x38, 0xf2, 0x2e, 0xd7, 0xd8, 0xfa, 0x22, 0x70, 0xf4, 0x2b, 0x78, 0x99, 0x28, 0xec,
	0x13, 0x87, 0x50, 0xf2, 0x5f, 0xd1, 0xa9, 0x5f, 0xc1, 0xf3, 0xb3, 0xc0, 0xfb, 0x1d, 0x31, 0xe9,
	0x53, 0xdc, 0xf8, 0x18, 0x9a, 0xbe, 0x38, 0x95, 0x0a, 0x91, 0xa4, 0x71, 0xc1, 0xdf, 0x40, 0x47,
	0x0a, 0x7e, 0xa2, 0xb9, 0x8f, 0x90, 0x7d, 0x05, 0x8d, 0x5f, 0x7b, 0x37, 0x31, 0x6c, 0x5a, 0x50,
	0xb5, 0x2d, 0x29, 0xa9, 0x6a, 0x5b, 0x0c, 0x7b, 0xc1, 0xd4, 0x1d, 0xf4, 0x23, 0xec, 0xf1, 0x05,
	0xd2, 0xa1, 0xf9, 0xde, 0x0b, 0xde, 0xdd, 0x3a, 0xde, 0x7b, 0x9e, 0x55, 0x22, 0xc2, 0x29, 0x9a,
	0xfe, 0x25, 0xb4, 0xc6, 0x33, 0xd7, 0xec, 0xf9, 0x7e, 0x64, 0xee, 0x1e, 0x2c, 0x5b, 0x98, 0x62,
	0x2e, 0xbd, 0x71, 0xd8, 0x49, 0x00, 0x29, 0xd8, 0xfa, 0x98, 0x62, 0x83, 0x73, 0xe8, 0x16, 0x6c,
	0xc4, 0x67, 0x17, 0x87, 0xe7, 0x97, 0xf0, 0xe2, 0x84, 0x50, 0x09, 0xe9, 0x9e, 0xef, 0x87, 0x51,
	0xd9, 0xfa, 0x63, 0x05, 0xb6, 0xb2, 0x3b, 0x0b, 0x33, 0x03, 0xed, 0xc3, 0x1a, 0x16, 0xde, 0x6b,
	0x35, 0x5e, 0x51, 0xda, 0xb1, 0xcc, 0x28, 0x2a, 0x11, 0x83, 0xbe, 0x0d, 0xaf, 0x53, 0x86, 0x0d,
	0xf1, 0xd4, 0x35, 0xef, 0x48, 0x6c, 0xf9, 0x3f, 0x2b, 0xf0, 0x51, 0x09, 0xc3, 0xe2, 0x1c, 0xe8,
	0x43, 0xdb, 0xe1, 0x6a, 0x8e, 0x3c, 0xf7, 0xd6, 0x9e, 0x0c, 0xed, 0x90, 0x4a, 0x4f, 0x34, 0xd5,
	0x93, 0xa1, 0xc2, 0x63, 0xe4, 0x4e, 0xe8, 0x7f, 0xa9, 0xc0, 0x96, 0x58, 0x4e, 0x03, 0xd2, 0xf3,
	0xfd, 0xf1, 0xf8, 0x34, 0x02, 0xce, 0x2e, 0x34, 0x02, 0xe2, 0x10, 0x1c, 0x92, 0x51, 0x82, 0x73,
	0x95, 0x84, 0xba, 0xb0, 0x6e, 0x3a, 0x36, 0x71, 0xe9, 0xc0, 0x8a, 0xd2, 0x32, 0x5a, 0x33, 0xb0,
	0x8a, 0xdf, 0x63, 0x62, 0x06, 0x84, 0x46, 0x60, 0x55, 0x69, 0x8c, 0xc7, 0xeb, 0x4d, 0xe9, 0xdd,
	0xd7, 0x38, 0x24, 0x17, 0xc6, 0x50, 0x5b, 0x16, 0x3c, 0x2a, 0x8d, 0x15, 0xdb, 0x9c, 0x7d, 0x8b,
	0x03, 0xe7, 0x57, 0xd0, 0x4d, 0x5d, 0xa4, 0x8c, 0xdb, 0x63, 0x23, 0xa2, 0xff, 0xad, 0x02, 0xaf,
	0x0a, 0x05, 0x2c, 0x0e, 0x07, 0x5f, 0x40, 0x1d, 0x47, 0x7a, 0x78, 0x94, 0x1b, 0x87, 0x48, 0x05,
	0x80, 0xb4, 0x20, 0x61, 0xca, 0x39, 0x79, 0xc9, 0xbe, 0x6c, 0xe1, 0xe3, 0x9d, 0xfc, 0x73, 0xd6,
	0xc9, 0x48, 0xc0, 0x22, 0xb3, 0x75, 0x95, 0x7f, 0x7f, 0xc3, 0x22, 0x0f, 0xa5, 0x7a, 0xc9, 0xa1,
	0xef, 0xa8, 0xc9, 0x78, 0xe2, 0x78, 0x37, 0xd8, 0x49, 0x79, 0xc8, 0x0a, 0xcd, 0x76, 0x19, 0xc7,
	0xe2, 0x5c, 0xd0, 0xa1, 0x39, 0x51, 0x54, 0x71, 0x47, 0x9a, 0x46, 0x8a, 0xa6, 0xbf, 0x87, 0xe7,
	0x03, 0x37, 0xa4, 0xd8, 0x71, 0x94, 0x02, 0x9e, 0xba, 0xe0, 0xca, 0x23, 0x2e, 0x58, 0x9e, 0x90,
	0x7a, 0xaa, 0xa5, 0x01, 0x4b, 0x98, 0xf4, 0x09, 0x20, 0x55, 0xf1, 0xe2, 0x12, 0xec, 0xa7, 0xb0,
	0x79, 0xe1, 0xe6, 0x7d, 0xcc, 0x80, 0xae, 0x9a, 0x07, 0x9d, 0x0d, 0x9d, 0xf4, 0xc1, 0xc5, 0xd9,
	0x48, 0xa0, 0xa1, 0x7c, 0x1c, 0x19, 0xf6, 0xcc, 0x79, 0xc1, 0x97, 0x1c, 0x0a, 0x4e, 0xab, 0x73,
	0x71, 0x8a, 0x61, 0xed, 0x5b, 0xaa, 0x90, 0x0e, 0x17, 0xa8, 0x10, 0x3e, 0xc7, 0xcd, 0xfc, 0x0f,
	0xa1, 0x1e, 0x13, 0x99, 0xf3, 0xc1, 0xd4, 0xa5, 0xf6, 0x3d, 0x19, 0x27, 0x01, 0xab, 0x1b, 0x69,
	0xa2, 0xfe, 0x8f, 0x15, 0x7e, 0x46, 0x22, 0x69, 0xfe, 0x37, 0x40, 0xe3, 0xdf, 0x51, 0xe5, 0xd6,
	0xa2, 0x25, 0xdb, 0x79, 0x20, 0x41, 0x68, 0x7b, 0x6e, 0xd4, 0x0b, 0xca, 0x25, 0xff, 0x6e, 0x60,
	0x4a, 0x26, 0x5e, 0x30, 0x93, 0x35, 0x3f, 0x5e, 0x33, 0x8d, 0x16, 0x09, 0xcd, 0xc0, 0xf6, 0x29,
	0x3b, 0xb9, 0x22, 0x34, 0x2a, 0x24, 0xf4, 0x1a, 0xea, 0xe6, 0x1d, 0x0e, 0x78, 0x23, 0xa5, 0xad,
	0xf2, 0xfd, 0x84, 0xc0, 0x64, 0x47, 0xad, 0xa1, 0xb6, 0x96, 0x69, 0x4f, 0x35, 0x10, 0xed, 0xa8,
	0x31, 0xd4, 0xd6, 0x95, 0xee, 0xd4, 0x18, 0x32, 0x99, 0xac, 0x55, 0x0b, 0x7d, 0x6c, 0x12, 0xad,
	0x2e, 0x64, 0xc6, 0x04, 0xb4, 0x07, 0x1b, 0x66, 0x40, 0x30, 0xe5, 0x1e, 0x0b, 0x1e, 0xd8, 0xad,
	0xec, 0xad, 0x1b, 0x59, 0x32, 0xfa, 0x02, 0x36, 0xfd, 0xc0, 0x7e, 0xb0, 0x1d, 0x32, 0x21, 0x56,
	0xc2, 0xdd, 0xe0, 0xdc, 0x45, 0x5b, 0x08, 0xc1, 0xb2, 0x6d, 0x7a, 0xae, 0xd6, 0xe4, 0xe5, 0x80,
	0xff, 0x66, 0xd6, 0x88, 0x0f, 0x35, 0xb3, 0xf4, 0x99, 0xb0, 0x26, 0x26, 0x30, 0x1d, 0x72, 0x31,
	0xe8, 0x2b, 0x91, 0x6a, 0x71, 0xbe, 0xa2, 0x2d, 0x76, 0xf3, 0xb6, 0xc8, 0x1c, 0x79, 0xf3, 0x1b,
	0xe2, 0xe6, 0x53, 0xc4, 0x3c, 0x3e, 0xda, 0x05, 0xf8, 0x40, 0xdb, 0x00, 0x16, 0xb9, 0x9d, 0x62,
	0x87, 0xf6, 0x7c, 0x5f, 0x7b, 0xce, 0x1d, 0x53, 0x28, 0xec, 0x51, 0xe7, 0xe0, 0x90, 0x5e, 0xf8,
	0x16, 0xa6, 0xe4, 0xdc, 0xbe, 0x27, 0x1a, 0x12, 0x8f, 0xba, 0x34, 0x95, 0xc9, 0x49, 0x5a, 0x66,
	0x6d, 0x33, 0xd7, 0x44, 0x7f, 0x1f, 0x9e, 0x8b, 0x95, 0xea, 0x63, 0x87, 0xb3, 0xe5, 0x37, 0xf4,
	0x3f, 0x54, 0x38, 0x6a, 0x45, 0x86, 0x31, 0x1b, 0xbc, 0x07, 0x12, 0x04, 0xb6, 0x45, 0x64, 0x11,
	0xac, 0xf0, 0xe8, 0x66, 0xa8, 0xc2, 0x56, 0x11, 0x2e, 0xa5, 0x58, 0x36, 0x8d, 0x0c, 0x95, 0xf1,
	0x51, 0x72, 0xef, 0x3b, 0x98, 0x92, 0x54, 0xf1, 0xce, 0x50, 0xf5, 0x7f, 0x57, 0x60, 0x23, 0xd3,
	0x72, 0x3d, 0xb2, 0x8b, 0x8a, 0xb2, 0xa1, 0xfa, 0xe1, 0x6c, 0xa8, 0xe5, 0xb3, 0x21, 0xc2, 0xcf,
	0x72, 0x19, 0x7e, 0x56, 0x1e, 0x89, 0x9f, 0xd5, 0x52, 0xfc, 0xb0, 0xcf, 0xd2, 0x85, 0x3f, 0x09,
	0xb0, 0x45, 0xfe, 0xf7, 0x9f, 0x25, 0x55, 0xf1, 0xe2, 0x4a, 0xfe, 0x0d, 0x6c, 0x09, 0x6c, 0x3e,
	0xbd, 0x1d, 0x2a, 0x40, 0x5b, 0xad, 0x08, 0x6d, 0xac, 0x93, 0xcd, 0xe9, 0x58, 0x9c, 0x47, 0x7f,
	0xaf, 0xc0, 0xab, 0xb8, 0x71, 0xbe, 0xc4, 0x53, 0x47, 0x36, 0xdd, 0x91, 0x5f, 0xdb, 0x00, 0x21,
	0x27, 0x9c, 0x61, 0x7a, 0x17, 0x3d, 0x62, 0x13, 0x4a, 0xba, 0x22, 0x56, 0xb3, 0x15, 0x31, 0x3e,
	0xad, 0x3c, 0x44, 0x15, 0x0a, 0xda, 0x87, 0xf6, 0x3d, 0x76, 0xf1, 0x84, 0x58, 0xb2, 0xcb, 0x1a,
	0x58, 0xb2, 0xd2, 0xe7, 0xe8, 0xfa, 0x6f, 0xa1, 0x29, 0xf5, 0x7a, 0x8e, 0x6d, 0xce, 0xe6, 0x5a,
	0xf6, 0x03, 0x58, 0xc5, 0xa6, 0x49, 0x42, 0x81, 0xa1, 0xd6, 0xe1, 0x8b, 0x24, 0x58, 0x9c, 0xa9,
	0xc7, 0x37, 0x0d, 0xc9, 0xc4, 0x1e, 0x6f, 0xc5, 0x71, 0x10, 0xb1, 0xd7, 0xff, 0xc4, 0x5e, 0x40,
	0xbc, 0x8c, 0xf3, 0x5d, 0xc3, 0x73, 0xe2, 0x97, 0x3e, 0xfb, 0x96, 0x78, 0x8e, 0x7a, 0xf1, 0xf1,
	0x1a, 0xfd, 0x3c, 0x6d, 0xb5, 0x56, 0xe5, 0x4f, 0xaf, 0xc4, 0x16, 0x75, 0xd3, 0x48, 0x3b, 0x58,
	0x14, 0x9c, 0x5a, 0x49, 0x70, 0xd8, 0xf3, 0x27, 0x6b, 0xdc, 0xe2, 0x40, 0xc3, 0x62, 0x21, 0x30,
	0xfa, 0x7f, 0x1a, 0x8b, 0x9c, 0x71, 0x8b, 0x8b, 0xc5, 0x8f, 0x61, 0x4b, 0xcc, 0x7d, 0x9e, 0x12,
	0x0a, 0x66, 0x63, 0xee, 0xd4, 0xc2, 0x6c, 0xdc, 0x1f, 0x01, 0x24, 0x67, 0xd1, 0x2a, 0x54, 0x4f,
	0x7f, 0xd3, 0x5e, 0x42, 0x9b, 0xb0, 0x31, 0x18, 0x9d, 0x1f, 0x1b, 0x23, 0xa3, 0x37, 0xbc, 0x3e,
	0x36, 0x8c, 0x53, 0xa3, 0x5d, 0x41, 0x1d, 0x68, 0x0f, 0x46, 0x97, 0xbd, 0xe1, 0xa0, 0x7f, 0xdd,
	0x33, 0x4e, 0x2e, 0xde, 0x1e, 0x8f, 0xce, 0xdb, 0x55, 0xf4, 0x0c, 0xea, 0xa3, 0xd3, 0xf3, 0xeb,
	0x5f, 0x9d, 0x5e, 0x8c, 0xfa, 0xed, 0xda, 0xfe, 0x27, 0xd0, 0x54, 0x73, 0x08, 0xad, 0xc3, 0xb2,
	0x71, 0xdc, 0xeb, 0xb7, 0x97, 0x50, 0x1d, 0x56, 0xae, 0x8c, 0xc1, 0xf9, 0x71, 0xbb, 0x72, 0xf8,
	0xaf, 0x06, 0xac, 0xf4, 0x98, 0xe5, 0xe8, 0x27, 0xb0, 0x7c, 0x66, 0xbb, 0x13, 0x94, 0x0c, 0x95,
	0x94, 0x31, 0x74, 0xf7, 0x45, 0x86, 0x2a, 0xf3, 0x6d, 0x09, 0x5d, 0xc2, 0x46, 0x66, 0x7e, 0x8a,
	0x76, 0xe6, 0x8c, 0x73, 0xbb, 0xbb, 0xe5, 0x0c, 0xb1, 0x5c, 0x02, 0x9d, 0xa2, 0x4c, 0x47, 0x6f,
	0xe2, 0xb3, 0x1f, 0x28, 0x88, 0xdd, 0x4f, 0xe7, 0x70, 0xa9, 0xe6, 0x67, 0x52, 0x52, 0x31, 0xbf,
	0xb8, 0x92, 0x28, 0xe6, 0x97, 0x64, 0xb3, 0x90, 0x9b, 0x81, 0xb7, 0x22, 0xb7, 0x38, 0x2b, 0x15,
	0xb9, 0x25, 0x99, 0x21, 0xe4, 0x66, 0x20, 0xa9, 0xc8, 0x2d, 0x86, 0xb8, 0x22, 0xb7, 0x04, 0xcd,
	0xfa, 0x12, 0xfa, 0x0a, 0xd6, 0xe4, 0x33, 0x09, 0xbd, 0xcc, 0x4e, 0x15, 0x23, 0x39, 0x5a, 0x7e,
	0x23, 0x3e, 0x3f, 0x86, 0x56, 0x7a, 0xdc, 0x87, 0xb6, 0x63, 0xee, 0xc2, 0x09, 0x61, 0x77, 0xa7,
	0x74, 0x3f, 0x16, 0x7a, 0x97, 0x99, 0x2e, 0x46, 0x93, 0x38, 0xf4, 0x69, 0xf1, 0xd9, 0xcc, 0x28,
	0xaf, 0xfb, 0xd9, 0x3c, 0xb6, 0x14, 0x0c, 0xd2, 0x83, 0x29, 0x15, 0x06, 0x85, 0x23, 0x35, 0x15,
	0x06, 0xc5, 0x33, 0x2d, 0x7d, 0x09, 0xdd, 0xc0, 0x66, 0xc1, 0x04, 0x09, 0x7d, 0x52, 0x6c, 0x58,
	0x6a, 0x40, 0xd5, 0x7d, 0xf3, 0x61, 0xa6, 0x52, 0x1d, 0xb2, 0xcf, 0x2d, 0xd1, 0x91, 0x6a, 0x88,
	0xca, 0x74, 0xa4, 0x3b, 0x1a, 0x7d, 0x09, 0xbd, 0x53, 0xa7, 0xb9, 0xea, 0x90, 0x05, 0x15, 0xc5,
	0xb8, 0x60, 0x4e, 0xd3, 0xfd, 0xee, 0x5c, 0xbe, 0x58, 0xd9, 0x09, 0x40, 0x32, 0x1b, 0x40, 0xdd,
	0xf8, 0x60, 0x6e, 0xd2, 0xd0, 0x7d, 0x55, 0xb8, 0x17, 0x0b, 0x7a, 0x0b, 0x4d, 0x75, 0xcc, 0x80,
	0x5e, 0x27, 0x09, 0x96, 0x1f, 0x5b, 0x74, 0x3f, 0x2a, 0xd9, 0x55, 0xed, 0x4a, 0x1a, 0x58, 0xc5,
	0xae, 0x5c, 0x3b, 0xad, 0xd8, 0x95, 0xef, 0x78, 0xd5, 0xe2, 0x90, 0xdc, 0x56, 0xb6, 0x38, 0xe4,
	0x6e, 0x6a, 0xb7, 0x9c, 0x21, 0x92, 0xfb, 0x35, 0x7c, 0xb3, 0xfe, 0xb9, 0xe4, 0xba, 0x59, 0xe5,
	0x7f, 0x2b, 0xfe, 0xe8, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x24, 0x3a, 0x3d, 0x36, 0x65, 0x1c,
	0x00, 0x00,
}
