// Code generated by protoc-gen-go. DO NOT EDIT.
// source: agent.proto

package agentpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StatusCode int32

const (
	StatusCode_OK               StatusCode = 0
	StatusCode_INTERNRAL_ERROR  StatusCode = 1
	StatusCode_INVALID_ARGUMENT StatusCode = 2
	StatusCode_NOT_FOUND        StatusCode = 3
)

var StatusCode_name = map[int32]string{
	0: "OK",
	1: "INTERNRAL_ERROR",
	2: "INVALID_ARGUMENT",
	3: "NOT_FOUND",
}

var StatusCode_value = map[string]int32{
	"OK":               0,
	"INTERNRAL_ERROR":  1,
	"INVALID_ARGUMENT": 2,
	"NOT_FOUND":        3,
}

func (x StatusCode) String() string {
	return proto.EnumName(StatusCode_name, int32(x))
}

func (StatusCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{0}
}

type PingRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingRequest) Reset()         { *m = PingRequest{} }
func (m *PingRequest) String() string { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()    {}
func (*PingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{0}
}

func (m *PingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingRequest.Unmarshal(m, b)
}
func (m *PingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingRequest.Marshal(b, m, deterministic)
}
func (m *PingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingRequest.Merge(m, src)
}
func (m *PingRequest) XXX_Size() int {
	return xxx_messageInfo_PingRequest.Size(m)
}
func (m *PingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PingRequest proto.InternalMessageInfo

type PingResponse struct {
	Status               StatusCode `protobuf:"varint,1,opt,name=status,proto3,enum=agentpb.StatusCode" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PingResponse) Reset()         { *m = PingResponse{} }
func (m *PingResponse) String() string { return proto.CompactTextString(m) }
func (*PingResponse) ProtoMessage()    {}
func (*PingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{1}
}

func (m *PingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingResponse.Unmarshal(m, b)
}
func (m *PingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingResponse.Marshal(b, m, deterministic)
}
func (m *PingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingResponse.Merge(m, src)
}
func (m *PingResponse) XXX_Size() int {
	return xxx_messageInfo_PingResponse.Size(m)
}
func (m *PingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PingResponse proto.InternalMessageInfo

func (m *PingResponse) GetStatus() StatusCode {
	if m != nil {
		return m.Status
	}
	return StatusCode_OK
}

type StoreCredentialRequest struct {
	CredentialType       string            `protobuf:"bytes,1,opt,name=credentialType,proto3" json:"credentialType,omitempty"`
	CredEntityName       string            `protobuf:"bytes,2,opt,name=credEntityName,proto3" json:"credEntityName,omitempty"`
	CredIdentifier       string            `protobuf:"bytes,3,opt,name=credIdentifier,proto3" json:"credIdentifier,omitempty"`
	Credential           map[string]string `protobuf:"bytes,4,rep,name=credential,proto3" json:"credential,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *StoreCredentialRequest) Reset()         { *m = StoreCredentialRequest{} }
func (m *StoreCredentialRequest) String() string { return proto.CompactTextString(m) }
func (*StoreCredentialRequest) ProtoMessage()    {}
func (*StoreCredentialRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{2}
}

func (m *StoreCredentialRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoreCredentialRequest.Unmarshal(m, b)
}
func (m *StoreCredentialRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoreCredentialRequest.Marshal(b, m, deterministic)
}
func (m *StoreCredentialRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoreCredentialRequest.Merge(m, src)
}
func (m *StoreCredentialRequest) XXX_Size() int {
	return xxx_messageInfo_StoreCredentialRequest.Size(m)
}
func (m *StoreCredentialRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StoreCredentialRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StoreCredentialRequest proto.InternalMessageInfo

func (m *StoreCredentialRequest) GetCredentialType() string {
	if m != nil {
		return m.CredentialType
	}
	return ""
}

func (m *StoreCredentialRequest) GetCredEntityName() string {
	if m != nil {
		return m.CredEntityName
	}
	return ""
}

func (m *StoreCredentialRequest) GetCredIdentifier() string {
	if m != nil {
		return m.CredIdentifier
	}
	return ""
}

func (m *StoreCredentialRequest) GetCredential() map[string]string {
	if m != nil {
		return m.Credential
	}
	return nil
}

type StoreCredentialResponse struct {
	Status               StatusCode `protobuf:"varint,1,opt,name=status,proto3,enum=agentpb.StatusCode" json:"status,omitempty"`
	StatusMessage        string     `protobuf:"bytes,2,opt,name=statusMessage,proto3" json:"statusMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *StoreCredentialResponse) Reset()         { *m = StoreCredentialResponse{} }
func (m *StoreCredentialResponse) String() string { return proto.CompactTextString(m) }
func (*StoreCredentialResponse) ProtoMessage()    {}
func (*StoreCredentialResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{3}
}

func (m *StoreCredentialResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoreCredentialResponse.Unmarshal(m, b)
}
func (m *StoreCredentialResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoreCredentialResponse.Marshal(b, m, deterministic)
}
func (m *StoreCredentialResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoreCredentialResponse.Merge(m, src)
}
func (m *StoreCredentialResponse) XXX_Size() int {
	return xxx_messageInfo_StoreCredentialResponse.Size(m)
}
func (m *StoreCredentialResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StoreCredentialResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StoreCredentialResponse proto.InternalMessageInfo

func (m *StoreCredentialResponse) GetStatus() StatusCode {
	if m != nil {
		return m.Status
	}
	return StatusCode_OK
}

func (m *StoreCredentialResponse) GetStatusMessage() string {
	if m != nil {
		return m.StatusMessage
	}
	return ""
}

type ClusterRequest struct {
	PluginName           string   `protobuf:"bytes,1,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`
	ClusterName          string   `protobuf:"bytes,2,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClusterRequest) Reset()         { *m = ClusterRequest{} }
func (m *ClusterRequest) String() string { return proto.CompactTextString(m) }
func (*ClusterRequest) ProtoMessage()    {}
func (*ClusterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{4}
}

func (m *ClusterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterRequest.Unmarshal(m, b)
}
func (m *ClusterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterRequest.Marshal(b, m, deterministic)
}
func (m *ClusterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterRequest.Merge(m, src)
}
func (m *ClusterRequest) XXX_Size() int {
	return xxx_messageInfo_ClusterRequest.Size(m)
}
func (m *ClusterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterRequest proto.InternalMessageInfo

func (m *ClusterRequest) GetPluginName() string {
	if m != nil {
		return m.PluginName
	}
	return ""
}

func (m *ClusterRequest) GetClusterName() string {
	if m != nil {
		return m.ClusterName
	}
	return ""
}

type RepositoryAddRequest struct {
	PluginName           string   `protobuf:"bytes,1,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`
	RepoName             string   `protobuf:"bytes,2,opt,name=repo_name,json=repoName,proto3" json:"repo_name,omitempty"`
	RepoUrl              string   `protobuf:"bytes,3,opt,name=repo_url,json=repoUrl,proto3" json:"repo_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RepositoryAddRequest) Reset()         { *m = RepositoryAddRequest{} }
func (m *RepositoryAddRequest) String() string { return proto.CompactTextString(m) }
func (*RepositoryAddRequest) ProtoMessage()    {}
func (*RepositoryAddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{5}
}

func (m *RepositoryAddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RepositoryAddRequest.Unmarshal(m, b)
}
func (m *RepositoryAddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RepositoryAddRequest.Marshal(b, m, deterministic)
}
func (m *RepositoryAddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RepositoryAddRequest.Merge(m, src)
}
func (m *RepositoryAddRequest) XXX_Size() int {
	return xxx_messageInfo_RepositoryAddRequest.Size(m)
}
func (m *RepositoryAddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RepositoryAddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RepositoryAddRequest proto.InternalMessageInfo

func (m *RepositoryAddRequest) GetPluginName() string {
	if m != nil {
		return m.PluginName
	}
	return ""
}

func (m *RepositoryAddRequest) GetRepoName() string {
	if m != nil {
		return m.RepoName
	}
	return ""
}

func (m *RepositoryAddRequest) GetRepoUrl() string {
	if m != nil {
		return m.RepoUrl
	}
	return ""
}

type RepositoryDeleteRequest struct {
	PluginName           string   `protobuf:"bytes,1,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`
	RepoName             string   `protobuf:"bytes,2,opt,name=repo_name,json=repoName,proto3" json:"repo_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RepositoryDeleteRequest) Reset()         { *m = RepositoryDeleteRequest{} }
func (m *RepositoryDeleteRequest) String() string { return proto.CompactTextString(m) }
func (*RepositoryDeleteRequest) ProtoMessage()    {}
func (*RepositoryDeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{6}
}

func (m *RepositoryDeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RepositoryDeleteRequest.Unmarshal(m, b)
}
func (m *RepositoryDeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RepositoryDeleteRequest.Marshal(b, m, deterministic)
}
func (m *RepositoryDeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RepositoryDeleteRequest.Merge(m, src)
}
func (m *RepositoryDeleteRequest) XXX_Size() int {
	return xxx_messageInfo_RepositoryDeleteRequest.Size(m)
}
func (m *RepositoryDeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RepositoryDeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RepositoryDeleteRequest proto.InternalMessageInfo

func (m *RepositoryDeleteRequest) GetPluginName() string {
	if m != nil {
		return m.PluginName
	}
	return ""
}

func (m *RepositoryDeleteRequest) GetRepoName() string {
	if m != nil {
		return m.RepoName
	}
	return ""
}

type ProjectAddRequest struct {
	PluginName           string   `protobuf:"bytes,1,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`
	ProjectName          string   `protobuf:"bytes,2,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProjectAddRequest) Reset()         { *m = ProjectAddRequest{} }
func (m *ProjectAddRequest) String() string { return proto.CompactTextString(m) }
func (*ProjectAddRequest) ProtoMessage()    {}
func (*ProjectAddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{7}
}

func (m *ProjectAddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProjectAddRequest.Unmarshal(m, b)
}
func (m *ProjectAddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProjectAddRequest.Marshal(b, m, deterministic)
}
func (m *ProjectAddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProjectAddRequest.Merge(m, src)
}
func (m *ProjectAddRequest) XXX_Size() int {
	return xxx_messageInfo_ProjectAddRequest.Size(m)
}
func (m *ProjectAddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProjectAddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProjectAddRequest proto.InternalMessageInfo

func (m *ProjectAddRequest) GetPluginName() string {
	if m != nil {
		return m.PluginName
	}
	return ""
}

func (m *ProjectAddRequest) GetProjectName() string {
	if m != nil {
		return m.ProjectName
	}
	return ""
}

type ProjectDeleteRequest struct {
	PluginName           string   `protobuf:"bytes,1,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`
	ProjectName          string   `protobuf:"bytes,2,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProjectDeleteRequest) Reset()         { *m = ProjectDeleteRequest{} }
func (m *ProjectDeleteRequest) String() string { return proto.CompactTextString(m) }
func (*ProjectDeleteRequest) ProtoMessage()    {}
func (*ProjectDeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{8}
}

func (m *ProjectDeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProjectDeleteRequest.Unmarshal(m, b)
}
func (m *ProjectDeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProjectDeleteRequest.Marshal(b, m, deterministic)
}
func (m *ProjectDeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProjectDeleteRequest.Merge(m, src)
}
func (m *ProjectDeleteRequest) XXX_Size() int {
	return xxx_messageInfo_ProjectDeleteRequest.Size(m)
}
func (m *ProjectDeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProjectDeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProjectDeleteRequest proto.InternalMessageInfo

func (m *ProjectDeleteRequest) GetPluginName() string {
	if m != nil {
		return m.PluginName
	}
	return ""
}

func (m *ProjectDeleteRequest) GetProjectName() string {
	if m != nil {
		return m.ProjectName
	}
	return ""
}

type JobRequest struct {
	Operation            string   `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`
	Payload              *any.Any `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobRequest) Reset()         { *m = JobRequest{} }
func (m *JobRequest) String() string { return proto.CompactTextString(m) }
func (*JobRequest) ProtoMessage()    {}
func (*JobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{9}
}

func (m *JobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobRequest.Unmarshal(m, b)
}
func (m *JobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobRequest.Marshal(b, m, deterministic)
}
func (m *JobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobRequest.Merge(m, src)
}
func (m *JobRequest) XXX_Size() int {
	return xxx_messageInfo_JobRequest.Size(m)
}
func (m *JobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JobRequest proto.InternalMessageInfo

func (m *JobRequest) GetOperation() string {
	if m != nil {
		return m.Operation
	}
	return ""
}

func (m *JobRequest) GetPayload() *any.Any {
	if m != nil {
		return m.Payload
	}
	return nil
}

type JobResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RunID                string   `protobuf:"bytes,2,opt,name=runID,proto3" json:"runID,omitempty"`
	WorkflowName         string   `protobuf:"bytes,3,opt,name=workflowName,proto3" json:"workflowName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobResponse) Reset()         { *m = JobResponse{} }
func (m *JobResponse) String() string { return proto.CompactTextString(m) }
func (*JobResponse) ProtoMessage()    {}
func (*JobResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{10}
}

func (m *JobResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobResponse.Unmarshal(m, b)
}
func (m *JobResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobResponse.Marshal(b, m, deterministic)
}
func (m *JobResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobResponse.Merge(m, src)
}
func (m *JobResponse) XXX_Size() int {
	return xxx_messageInfo_JobResponse.Size(m)
}
func (m *JobResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JobResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JobResponse proto.InternalMessageInfo

func (m *JobResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *JobResponse) GetRunID() string {
	if m != nil {
		return m.RunID
	}
	return ""
}

func (m *JobResponse) GetWorkflowName() string {
	if m != nil {
		return m.WorkflowName
	}
	return ""
}

type SyncAppRequest struct {
	Data                 *SyncAppData `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SyncAppRequest) Reset()         { *m = SyncAppRequest{} }
func (m *SyncAppRequest) String() string { return proto.CompactTextString(m) }
func (*SyncAppRequest) ProtoMessage()    {}
func (*SyncAppRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{11}
}

func (m *SyncAppRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncAppRequest.Unmarshal(m, b)
}
func (m *SyncAppRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncAppRequest.Marshal(b, m, deterministic)
}
func (m *SyncAppRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncAppRequest.Merge(m, src)
}
func (m *SyncAppRequest) XXX_Size() int {
	return xxx_messageInfo_SyncAppRequest.Size(m)
}
func (m *SyncAppRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncAppRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SyncAppRequest proto.InternalMessageInfo

func (m *SyncAppRequest) GetData() *SyncAppData {
	if m != nil {
		return m.Data
	}
	return nil
}

type SyncAppResponse struct {
	Status               StatusCode `protobuf:"varint,1,opt,name=status,proto3,enum=agentpb.StatusCode" json:"status,omitempty"`
	StatusMessage        string     `protobuf:"bytes,2,opt,name=statusMessage,proto3" json:"statusMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SyncAppResponse) Reset()         { *m = SyncAppResponse{} }
func (m *SyncAppResponse) String() string { return proto.CompactTextString(m) }
func (*SyncAppResponse) ProtoMessage()    {}
func (*SyncAppResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{12}
}

func (m *SyncAppResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncAppResponse.Unmarshal(m, b)
}
func (m *SyncAppResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncAppResponse.Marshal(b, m, deterministic)
}
func (m *SyncAppResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncAppResponse.Merge(m, src)
}
func (m *SyncAppResponse) XXX_Size() int {
	return xxx_messageInfo_SyncAppResponse.Size(m)
}
func (m *SyncAppResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncAppResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SyncAppResponse proto.InternalMessageInfo

func (m *SyncAppResponse) GetStatus() StatusCode {
	if m != nil {
		return m.Status
	}
	return StatusCode_OK
}

func (m *SyncAppResponse) GetStatusMessage() string {
	if m != nil {
		return m.StatusMessage
	}
	return ""
}

type GetClusterAppsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetClusterAppsRequest) Reset()         { *m = GetClusterAppsRequest{} }
func (m *GetClusterAppsRequest) String() string { return proto.CompactTextString(m) }
func (*GetClusterAppsRequest) ProtoMessage()    {}
func (*GetClusterAppsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{13}
}

func (m *GetClusterAppsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetClusterAppsRequest.Unmarshal(m, b)
}
func (m *GetClusterAppsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetClusterAppsRequest.Marshal(b, m, deterministic)
}
func (m *GetClusterAppsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetClusterAppsRequest.Merge(m, src)
}
func (m *GetClusterAppsRequest) XXX_Size() int {
	return xxx_messageInfo_GetClusterAppsRequest.Size(m)
}
func (m *GetClusterAppsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetClusterAppsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetClusterAppsRequest proto.InternalMessageInfo

type GetClusterAppsResponse struct {
	Status               StatusCode `protobuf:"varint,1,opt,name=status,proto3,enum=agentpb.StatusCode" json:"status,omitempty"`
	StatusMessage        string     `protobuf:"bytes,2,opt,name=statusMessage,proto3" json:"statusMessage,omitempty"`
	AppData              []*AppData `protobuf:"bytes,3,rep,name=appData,proto3" json:"appData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetClusterAppsResponse) Reset()         { *m = GetClusterAppsResponse{} }
func (m *GetClusterAppsResponse) String() string { return proto.CompactTextString(m) }
func (*GetClusterAppsResponse) ProtoMessage()    {}
func (*GetClusterAppsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{14}
}

func (m *GetClusterAppsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetClusterAppsResponse.Unmarshal(m, b)
}
func (m *GetClusterAppsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetClusterAppsResponse.Marshal(b, m, deterministic)
}
func (m *GetClusterAppsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetClusterAppsResponse.Merge(m, src)
}
func (m *GetClusterAppsResponse) XXX_Size() int {
	return xxx_messageInfo_GetClusterAppsResponse.Size(m)
}
func (m *GetClusterAppsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetClusterAppsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetClusterAppsResponse proto.InternalMessageInfo

func (m *GetClusterAppsResponse) GetStatus() StatusCode {
	if m != nil {
		return m.Status
	}
	return StatusCode_OK
}

func (m *GetClusterAppsResponse) GetStatusMessage() string {
	if m != nil {
		return m.StatusMessage
	}
	return ""
}

func (m *GetClusterAppsResponse) GetAppData() []*AppData {
	if m != nil {
		return m.AppData
	}
	return nil
}

type GetClusterAppLaunchesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetClusterAppLaunchesRequest) Reset()         { *m = GetClusterAppLaunchesRequest{} }
func (m *GetClusterAppLaunchesRequest) String() string { return proto.CompactTextString(m) }
func (*GetClusterAppLaunchesRequest) ProtoMessage()    {}
func (*GetClusterAppLaunchesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{15}
}

func (m *GetClusterAppLaunchesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetClusterAppLaunchesRequest.Unmarshal(m, b)
}
func (m *GetClusterAppLaunchesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetClusterAppLaunchesRequest.Marshal(b, m, deterministic)
}
func (m *GetClusterAppLaunchesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetClusterAppLaunchesRequest.Merge(m, src)
}
func (m *GetClusterAppLaunchesRequest) XXX_Size() int {
	return xxx_messageInfo_GetClusterAppLaunchesRequest.Size(m)
}
func (m *GetClusterAppLaunchesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetClusterAppLaunchesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetClusterAppLaunchesRequest proto.InternalMessageInfo

type GetClusterAppLaunchesResponse struct {
	Status               StatusCode         `protobuf:"varint,1,opt,name=status,proto3,enum=agentpb.StatusCode" json:"status,omitempty"`
	StatusMessage        string             `protobuf:"bytes,2,opt,name=statusMessage,proto3" json:"statusMessage,omitempty"`
	LaunchConfigList     []*AppLaunchConfig `protobuf:"bytes,3,rep,name=launchConfigList,proto3" json:"launchConfigList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetClusterAppLaunchesResponse) Reset()         { *m = GetClusterAppLaunchesResponse{} }
func (m *GetClusterAppLaunchesResponse) String() string { return proto.CompactTextString(m) }
func (*GetClusterAppLaunchesResponse) ProtoMessage()    {}
func (*GetClusterAppLaunchesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{16}
}

func (m *GetClusterAppLaunchesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetClusterAppLaunchesResponse.Unmarshal(m, b)
}
func (m *GetClusterAppLaunchesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetClusterAppLaunchesResponse.Marshal(b, m, deterministic)
}
func (m *GetClusterAppLaunchesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetClusterAppLaunchesResponse.Merge(m, src)
}
func (m *GetClusterAppLaunchesResponse) XXX_Size() int {
	return xxx_messageInfo_GetClusterAppLaunchesResponse.Size(m)
}
func (m *GetClusterAppLaunchesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetClusterAppLaunchesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetClusterAppLaunchesResponse proto.InternalMessageInfo

func (m *GetClusterAppLaunchesResponse) GetStatus() StatusCode {
	if m != nil {
		return m.Status
	}
	return StatusCode_OK
}

func (m *GetClusterAppLaunchesResponse) GetStatusMessage() string {
	if m != nil {
		return m.StatusMessage
	}
	return ""
}

func (m *GetClusterAppLaunchesResponse) GetLaunchConfigList() []*AppLaunchConfig {
	if m != nil {
		return m.LaunchConfigList
	}
	return nil
}

type ConfigureAppSSORequest struct {
	ReleaseName          string   `protobuf:"bytes,1,opt,name=releaseName,proto3" json:"releaseName,omitempty"`
	ClientId             string   `protobuf:"bytes,2,opt,name=clientId,proto3" json:"clientId,omitempty"`
	ClientSecret         string   `protobuf:"bytes,3,opt,name=clientSecret,proto3" json:"clientSecret,omitempty"`
	OAuthBaseURL         string   `protobuf:"bytes,4,opt,name=oAuthBaseURL,proto3" json:"oAuthBaseURL,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigureAppSSORequest) Reset()         { *m = ConfigureAppSSORequest{} }
func (m *ConfigureAppSSORequest) String() string { return proto.CompactTextString(m) }
func (*ConfigureAppSSORequest) ProtoMessage()    {}
func (*ConfigureAppSSORequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{17}
}

func (m *ConfigureAppSSORequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigureAppSSORequest.Unmarshal(m, b)
}
func (m *ConfigureAppSSORequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigureAppSSORequest.Marshal(b, m, deterministic)
}
func (m *ConfigureAppSSORequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigureAppSSORequest.Merge(m, src)
}
func (m *ConfigureAppSSORequest) XXX_Size() int {
	return xxx_messageInfo_ConfigureAppSSORequest.Size(m)
}
func (m *ConfigureAppSSORequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigureAppSSORequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigureAppSSORequest proto.InternalMessageInfo

func (m *ConfigureAppSSORequest) GetReleaseName() string {
	if m != nil {
		return m.ReleaseName
	}
	return ""
}

func (m *ConfigureAppSSORequest) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *ConfigureAppSSORequest) GetClientSecret() string {
	if m != nil {
		return m.ClientSecret
	}
	return ""
}

func (m *ConfigureAppSSORequest) GetOAuthBaseURL() string {
	if m != nil {
		return m.OAuthBaseURL
	}
	return ""
}

type ConfigureAppSSOResponse struct {
	Status               StatusCode `protobuf:"varint,1,opt,name=status,proto3,enum=agentpb.StatusCode" json:"status,omitempty"`
	StatusMessage        string     `protobuf:"bytes,2,opt,name=statusMessage,proto3" json:"statusMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ConfigureAppSSOResponse) Reset()         { *m = ConfigureAppSSOResponse{} }
func (m *ConfigureAppSSOResponse) String() string { return proto.CompactTextString(m) }
func (*ConfigureAppSSOResponse) ProtoMessage()    {}
func (*ConfigureAppSSOResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{18}
}

func (m *ConfigureAppSSOResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigureAppSSOResponse.Unmarshal(m, b)
}
func (m *ConfigureAppSSOResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigureAppSSOResponse.Marshal(b, m, deterministic)
}
func (m *ConfigureAppSSOResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigureAppSSOResponse.Merge(m, src)
}
func (m *ConfigureAppSSOResponse) XXX_Size() int {
	return xxx_messageInfo_ConfigureAppSSOResponse.Size(m)
}
func (m *ConfigureAppSSOResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigureAppSSOResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigureAppSSOResponse proto.InternalMessageInfo

func (m *ConfigureAppSSOResponse) GetStatus() StatusCode {
	if m != nil {
		return m.Status
	}
	return StatusCode_OK
}

func (m *ConfigureAppSSOResponse) GetStatusMessage() string {
	if m != nil {
		return m.StatusMessage
	}
	return ""
}

type GetClusterAppConfigRequest struct {
	ReleaseName          string   `protobuf:"bytes,1,opt,name=releaseName,proto3" json:"releaseName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetClusterAppConfigRequest) Reset()         { *m = GetClusterAppConfigRequest{} }
func (m *GetClusterAppConfigRequest) String() string { return proto.CompactTextString(m) }
func (*GetClusterAppConfigRequest) ProtoMessage()    {}
func (*GetClusterAppConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{19}
}

func (m *GetClusterAppConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetClusterAppConfigRequest.Unmarshal(m, b)
}
func (m *GetClusterAppConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetClusterAppConfigRequest.Marshal(b, m, deterministic)
}
func (m *GetClusterAppConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetClusterAppConfigRequest.Merge(m, src)
}
func (m *GetClusterAppConfigRequest) XXX_Size() int {
	return xxx_messageInfo_GetClusterAppConfigRequest.Size(m)
}
func (m *GetClusterAppConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetClusterAppConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetClusterAppConfigRequest proto.InternalMessageInfo

func (m *GetClusterAppConfigRequest) GetReleaseName() string {
	if m != nil {
		return m.ReleaseName
	}
	return ""
}

type GetClusterAppConfigResponse struct {
	Status               StatusCode `protobuf:"varint,1,opt,name=status,proto3,enum=agentpb.StatusCode" json:"status,omitempty"`
	StatusMessage        string     `protobuf:"bytes,2,opt,name=statusMessage,proto3" json:"statusMessage,omitempty"`
	AppConfig            *AppConfig `protobuf:"bytes,3,opt,name=appConfig,proto3" json:"appConfig,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetClusterAppConfigResponse) Reset()         { *m = GetClusterAppConfigResponse{} }
func (m *GetClusterAppConfigResponse) String() string { return proto.CompactTextString(m) }
func (*GetClusterAppConfigResponse) ProtoMessage()    {}
func (*GetClusterAppConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{20}
}

func (m *GetClusterAppConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetClusterAppConfigResponse.Unmarshal(m, b)
}
func (m *GetClusterAppConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetClusterAppConfigResponse.Marshal(b, m, deterministic)
}
func (m *GetClusterAppConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetClusterAppConfigResponse.Merge(m, src)
}
func (m *GetClusterAppConfigResponse) XXX_Size() int {
	return xxx_messageInfo_GetClusterAppConfigResponse.Size(m)
}
func (m *GetClusterAppConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetClusterAppConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetClusterAppConfigResponse proto.InternalMessageInfo

func (m *GetClusterAppConfigResponse) GetStatus() StatusCode {
	if m != nil {
		return m.Status
	}
	return StatusCode_OK
}

func (m *GetClusterAppConfigResponse) GetStatusMessage() string {
	if m != nil {
		return m.StatusMessage
	}
	return ""
}

func (m *GetClusterAppConfigResponse) GetAppConfig() *AppConfig {
	if m != nil {
		return m.AppConfig
	}
	return nil
}

type GetClusterAppValuesRequest struct {
	ReleaseName          string   `protobuf:"bytes,1,opt,name=releaseName,proto3" json:"releaseName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetClusterAppValuesRequest) Reset()         { *m = GetClusterAppValuesRequest{} }
func (m *GetClusterAppValuesRequest) String() string { return proto.CompactTextString(m) }
func (*GetClusterAppValuesRequest) ProtoMessage()    {}
func (*GetClusterAppValuesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{21}
}

func (m *GetClusterAppValuesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetClusterAppValuesRequest.Unmarshal(m, b)
}
func (m *GetClusterAppValuesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetClusterAppValuesRequest.Marshal(b, m, deterministic)
}
func (m *GetClusterAppValuesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetClusterAppValuesRequest.Merge(m, src)
}
func (m *GetClusterAppValuesRequest) XXX_Size() int {
	return xxx_messageInfo_GetClusterAppValuesRequest.Size(m)
}
func (m *GetClusterAppValuesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetClusterAppValuesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetClusterAppValuesRequest proto.InternalMessageInfo

func (m *GetClusterAppValuesRequest) GetReleaseName() string {
	if m != nil {
		return m.ReleaseName
	}
	return ""
}

type GetClusterAppValuesResponse struct {
	Status               StatusCode `protobuf:"varint,1,opt,name=status,proto3,enum=agentpb.StatusCode" json:"status,omitempty"`
	StatusMessage        string     `protobuf:"bytes,2,opt,name=statusMessage,proto3" json:"statusMessage,omitempty"`
	Values               *AppValues `protobuf:"bytes,3,opt,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetClusterAppValuesResponse) Reset()         { *m = GetClusterAppValuesResponse{} }
func (m *GetClusterAppValuesResponse) String() string { return proto.CompactTextString(m) }
func (*GetClusterAppValuesResponse) ProtoMessage()    {}
func (*GetClusterAppValuesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{22}
}

func (m *GetClusterAppValuesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetClusterAppValuesResponse.Unmarshal(m, b)
}
func (m *GetClusterAppValuesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetClusterAppValuesResponse.Marshal(b, m, deterministic)
}
func (m *GetClusterAppValuesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetClusterAppValuesResponse.Merge(m, src)
}
func (m *GetClusterAppValuesResponse) XXX_Size() int {
	return xxx_messageInfo_GetClusterAppValuesResponse.Size(m)
}
func (m *GetClusterAppValuesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetClusterAppValuesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetClusterAppValuesResponse proto.InternalMessageInfo

func (m *GetClusterAppValuesResponse) GetStatus() StatusCode {
	if m != nil {
		return m.Status
	}
	return StatusCode_OK
}

func (m *GetClusterAppValuesResponse) GetStatusMessage() string {
	if m != nil {
		return m.StatusMessage
	}
	return ""
}

func (m *GetClusterAppValuesResponse) GetValues() *AppValues {
	if m != nil {
		return m.Values
	}
	return nil
}

type GetClusterGlobalValuesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetClusterGlobalValuesRequest) Reset()         { *m = GetClusterGlobalValuesRequest{} }
func (m *GetClusterGlobalValuesRequest) String() string { return proto.CompactTextString(m) }
func (*GetClusterGlobalValuesRequest) ProtoMessage()    {}
func (*GetClusterGlobalValuesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{23}
}

func (m *GetClusterGlobalValuesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetClusterGlobalValuesRequest.Unmarshal(m, b)
}
func (m *GetClusterGlobalValuesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetClusterGlobalValuesRequest.Marshal(b, m, deterministic)
}
func (m *GetClusterGlobalValuesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetClusterGlobalValuesRequest.Merge(m, src)
}
func (m *GetClusterGlobalValuesRequest) XXX_Size() int {
	return xxx_messageInfo_GetClusterGlobalValuesRequest.Size(m)
}
func (m *GetClusterGlobalValuesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetClusterGlobalValuesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetClusterGlobalValuesRequest proto.InternalMessageInfo

type GetClusterGlobalValuesResponse struct {
	Status               StatusCode `protobuf:"varint,1,opt,name=status,proto3,enum=agentpb.StatusCode" json:"status,omitempty"`
	StatusMessage        string     `protobuf:"bytes,2,opt,name=statusMessage,proto3" json:"statusMessage,omitempty"`
	GlobalValues         []byte     `protobuf:"bytes,3,opt,name=globalValues,proto3" json:"globalValues,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetClusterGlobalValuesResponse) Reset()         { *m = GetClusterGlobalValuesResponse{} }
func (m *GetClusterGlobalValuesResponse) String() string { return proto.CompactTextString(m) }
func (*GetClusterGlobalValuesResponse) ProtoMessage()    {}
func (*GetClusterGlobalValuesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{24}
}

func (m *GetClusterGlobalValuesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetClusterGlobalValuesResponse.Unmarshal(m, b)
}
func (m *GetClusterGlobalValuesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetClusterGlobalValuesResponse.Marshal(b, m, deterministic)
}
func (m *GetClusterGlobalValuesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetClusterGlobalValuesResponse.Merge(m, src)
}
func (m *GetClusterGlobalValuesResponse) XXX_Size() int {
	return xxx_messageInfo_GetClusterGlobalValuesResponse.Size(m)
}
func (m *GetClusterGlobalValuesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetClusterGlobalValuesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetClusterGlobalValuesResponse proto.InternalMessageInfo

func (m *GetClusterGlobalValuesResponse) GetStatus() StatusCode {
	if m != nil {
		return m.Status
	}
	return StatusCode_OK
}

func (m *GetClusterGlobalValuesResponse) GetStatusMessage() string {
	if m != nil {
		return m.StatusMessage
	}
	return ""
}

func (m *GetClusterGlobalValuesResponse) GetGlobalValues() []byte {
	if m != nil {
		return m.GlobalValues
	}
	return nil
}

type InstallAppRequest struct {
	AppConfig            *AppConfig `protobuf:"bytes,1,opt,name=appConfig,proto3" json:"appConfig,omitempty"`
	AppValues            *AppValues `protobuf:"bytes,2,opt,name=appValues,proto3" json:"appValues,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *InstallAppRequest) Reset()         { *m = InstallAppRequest{} }
func (m *InstallAppRequest) String() string { return proto.CompactTextString(m) }
func (*InstallAppRequest) ProtoMessage()    {}
func (*InstallAppRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{25}
}

func (m *InstallAppRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstallAppRequest.Unmarshal(m, b)
}
func (m *InstallAppRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstallAppRequest.Marshal(b, m, deterministic)
}
func (m *InstallAppRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstallAppRequest.Merge(m, src)
}
func (m *InstallAppRequest) XXX_Size() int {
	return xxx_messageInfo_InstallAppRequest.Size(m)
}
func (m *InstallAppRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InstallAppRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InstallAppRequest proto.InternalMessageInfo

func (m *InstallAppRequest) GetAppConfig() *AppConfig {
	if m != nil {
		return m.AppConfig
	}
	return nil
}

func (m *InstallAppRequest) GetAppValues() *AppValues {
	if m != nil {
		return m.AppValues
	}
	return nil
}

type InstallAppResponse struct {
	Status               StatusCode `protobuf:"varint,1,opt,name=status,proto3,enum=agentpb.StatusCode" json:"status,omitempty"`
	StatusMessage        string     `protobuf:"bytes,2,opt,name=statusMessage,proto3" json:"statusMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *InstallAppResponse) Reset()         { *m = InstallAppResponse{} }
func (m *InstallAppResponse) String() string { return proto.CompactTextString(m) }
func (*InstallAppResponse) ProtoMessage()    {}
func (*InstallAppResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{26}
}

func (m *InstallAppResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstallAppResponse.Unmarshal(m, b)
}
func (m *InstallAppResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstallAppResponse.Marshal(b, m, deterministic)
}
func (m *InstallAppResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstallAppResponse.Merge(m, src)
}
func (m *InstallAppResponse) XXX_Size() int {
	return xxx_messageInfo_InstallAppResponse.Size(m)
}
func (m *InstallAppResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InstallAppResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InstallAppResponse proto.InternalMessageInfo

func (m *InstallAppResponse) GetStatus() StatusCode {
	if m != nil {
		return m.Status
	}
	return StatusCode_OK
}

func (m *InstallAppResponse) GetStatusMessage() string {
	if m != nil {
		return m.StatusMessage
	}
	return ""
}

type UnInstallAppRequest struct {
	ReleaseName          string   `protobuf:"bytes,2,opt,name=releaseName,proto3" json:"releaseName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnInstallAppRequest) Reset()         { *m = UnInstallAppRequest{} }
func (m *UnInstallAppRequest) String() string { return proto.CompactTextString(m) }
func (*UnInstallAppRequest) ProtoMessage()    {}
func (*UnInstallAppRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{27}
}

func (m *UnInstallAppRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnInstallAppRequest.Unmarshal(m, b)
}
func (m *UnInstallAppRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnInstallAppRequest.Marshal(b, m, deterministic)
}
func (m *UnInstallAppRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnInstallAppRequest.Merge(m, src)
}
func (m *UnInstallAppRequest) XXX_Size() int {
	return xxx_messageInfo_UnInstallAppRequest.Size(m)
}
func (m *UnInstallAppRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnInstallAppRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnInstallAppRequest proto.InternalMessageInfo

func (m *UnInstallAppRequest) GetReleaseName() string {
	if m != nil {
		return m.ReleaseName
	}
	return ""
}

type UnInstallAppResponse struct {
	Status               StatusCode `protobuf:"varint,1,opt,name=status,proto3,enum=agentpb.StatusCode" json:"status,omitempty"`
	StatusMessage        string     `protobuf:"bytes,2,opt,name=statusMessage,proto3" json:"statusMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *UnInstallAppResponse) Reset()         { *m = UnInstallAppResponse{} }
func (m *UnInstallAppResponse) String() string { return proto.CompactTextString(m) }
func (*UnInstallAppResponse) ProtoMessage()    {}
func (*UnInstallAppResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{28}
}

func (m *UnInstallAppResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnInstallAppResponse.Unmarshal(m, b)
}
func (m *UnInstallAppResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnInstallAppResponse.Marshal(b, m, deterministic)
}
func (m *UnInstallAppResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnInstallAppResponse.Merge(m, src)
}
func (m *UnInstallAppResponse) XXX_Size() int {
	return xxx_messageInfo_UnInstallAppResponse.Size(m)
}
func (m *UnInstallAppResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UnInstallAppResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UnInstallAppResponse proto.InternalMessageInfo

func (m *UnInstallAppResponse) GetStatus() StatusCode {
	if m != nil {
		return m.Status
	}
	return StatusCode_OK
}

func (m *UnInstallAppResponse) GetStatusMessage() string {
	if m != nil {
		return m.StatusMessage
	}
	return ""
}

type SyncAppData struct {
	Config               *AppConfig `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	Values               *AppValues `protobuf:"bytes,2,opt,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SyncAppData) Reset()         { *m = SyncAppData{} }
func (m *SyncAppData) String() string { return proto.CompactTextString(m) }
func (*SyncAppData) ProtoMessage()    {}
func (*SyncAppData) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{29}
}

func (m *SyncAppData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncAppData.Unmarshal(m, b)
}
func (m *SyncAppData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncAppData.Marshal(b, m, deterministic)
}
func (m *SyncAppData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncAppData.Merge(m, src)
}
func (m *SyncAppData) XXX_Size() int {
	return xxx_messageInfo_SyncAppData.Size(m)
}
func (m *SyncAppData) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncAppData.DiscardUnknown(m)
}

var xxx_messageInfo_SyncAppData proto.InternalMessageInfo

func (m *SyncAppData) GetConfig() *AppConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *SyncAppData) GetValues() *AppValues {
	if m != nil {
		return m.Values
	}
	return nil
}

type AppData struct {
	Config               *AppConfig `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	Status               *AppStatus `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AppData) Reset()         { *m = AppData{} }
func (m *AppData) String() string { return proto.CompactTextString(m) }
func (*AppData) ProtoMessage()    {}
func (*AppData) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{30}
}

func (m *AppData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppData.Unmarshal(m, b)
}
func (m *AppData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppData.Marshal(b, m, deterministic)
}
func (m *AppData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppData.Merge(m, src)
}
func (m *AppData) XXX_Size() int {
	return xxx_messageInfo_AppData.Size(m)
}
func (m *AppData) XXX_DiscardUnknown() {
	xxx_messageInfo_AppData.DiscardUnknown(m)
}

var xxx_messageInfo_AppData proto.InternalMessageInfo

func (m *AppData) GetConfig() *AppConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *AppData) GetStatus() *AppStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type AppStatus struct {
	RuntimeStatus        string   `protobuf:"bytes,1,opt,name=runtimeStatus,proto3" json:"runtimeStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppStatus) Reset()         { *m = AppStatus{} }
func (m *AppStatus) String() string { return proto.CompactTextString(m) }
func (*AppStatus) ProtoMessage()    {}
func (*AppStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{31}
}

func (m *AppStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppStatus.Unmarshal(m, b)
}
func (m *AppStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppStatus.Marshal(b, m, deterministic)
}
func (m *AppStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppStatus.Merge(m, src)
}
func (m *AppStatus) XXX_Size() int {
	return xxx_messageInfo_AppStatus.Size(m)
}
func (m *AppStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_AppStatus.DiscardUnknown(m)
}

var xxx_messageInfo_AppStatus proto.InternalMessageInfo

func (m *AppStatus) GetRuntimeStatus() string {
	if m != nil {
		return m.RuntimeStatus
	}
	return ""
}

type AppConfig struct {
	ReleaseName          string   `protobuf:"bytes,1,opt,name=releaseName,proto3" json:"releaseName,omitempty"`
	AppName              string   `protobuf:"bytes,2,opt,name=appName,proto3" json:"appName,omitempty"`
	Version              string   `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Category             string   `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Description          string   `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	ChartName            string   `protobuf:"bytes,6,opt,name=chartName,proto3" json:"chartName,omitempty"`
	RepoName             string   `protobuf:"bytes,7,opt,name=repoName,proto3" json:"repoName,omitempty"`
	RepoURL              string   `protobuf:"bytes,8,opt,name=repoURL,proto3" json:"repoURL,omitempty"`
	Namespace            string   `protobuf:"bytes,9,opt,name=namespace,proto3" json:"namespace,omitempty"`
	CreateNamespace      bool     `protobuf:"varint,10,opt,name=createNamespace,proto3" json:"createNamespace,omitempty"`
	PrivilegedNamespace  bool     `protobuf:"varint,11,opt,name=privilegedNamespace,proto3" json:"privilegedNamespace,omitempty"`
	Icon                 []byte   `protobuf:"bytes,12,opt,name=icon,proto3" json:"icon,omitempty"`
	LaunchURL            string   `protobuf:"bytes,13,opt,name=launchURL,proto3" json:"launchURL,omitempty"`
	LaunchUIDescription  string   `protobuf:"bytes,14,opt,name=launchUIDescription,proto3" json:"launchUIDescription,omitempty"`
	InstallStatus        string   `protobuf:"bytes,15,opt,name=installStatus,proto3" json:"installStatus,omitempty"`
	RuntimeStatus        string   `protobuf:"bytes,16,opt,name=runtimeStatus,proto3" json:"runtimeStatus,omitempty"`
	DefualtApp           bool     `protobuf:"varint,17,opt,name=defualtApp,proto3" json:"defualtApp,omitempty"`
	LastUpdateTime       string   `protobuf:"bytes,18,opt,name=lastUpdateTime,proto3" json:"lastUpdateTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppConfig) Reset()         { *m = AppConfig{} }
func (m *AppConfig) String() string { return proto.CompactTextString(m) }
func (*AppConfig) ProtoMessage()    {}
func (*AppConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{32}
}

func (m *AppConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppConfig.Unmarshal(m, b)
}
func (m *AppConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppConfig.Marshal(b, m, deterministic)
}
func (m *AppConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppConfig.Merge(m, src)
}
func (m *AppConfig) XXX_Size() int {
	return xxx_messageInfo_AppConfig.Size(m)
}
func (m *AppConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_AppConfig.DiscardUnknown(m)
}

var xxx_messageInfo_AppConfig proto.InternalMessageInfo

func (m *AppConfig) GetReleaseName() string {
	if m != nil {
		return m.ReleaseName
	}
	return ""
}

func (m *AppConfig) GetAppName() string {
	if m != nil {
		return m.AppName
	}
	return ""
}

func (m *AppConfig) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *AppConfig) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *AppConfig) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *AppConfig) GetChartName() string {
	if m != nil {
		return m.ChartName
	}
	return ""
}

func (m *AppConfig) GetRepoName() string {
	if m != nil {
		return m.RepoName
	}
	return ""
}

func (m *AppConfig) GetRepoURL() string {
	if m != nil {
		return m.RepoURL
	}
	return ""
}

func (m *AppConfig) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *AppConfig) GetCreateNamespace() bool {
	if m != nil {
		return m.CreateNamespace
	}
	return false
}

func (m *AppConfig) GetPrivilegedNamespace() bool {
	if m != nil {
		return m.PrivilegedNamespace
	}
	return false
}

func (m *AppConfig) GetIcon() []byte {
	if m != nil {
		return m.Icon
	}
	return nil
}

func (m *AppConfig) GetLaunchURL() string {
	if m != nil {
		return m.LaunchURL
	}
	return ""
}

func (m *AppConfig) GetLaunchUIDescription() string {
	if m != nil {
		return m.LaunchUIDescription
	}
	return ""
}

func (m *AppConfig) GetInstallStatus() string {
	if m != nil {
		return m.InstallStatus
	}
	return ""
}

func (m *AppConfig) GetRuntimeStatus() string {
	if m != nil {
		return m.RuntimeStatus
	}
	return ""
}

func (m *AppConfig) GetDefualtApp() bool {
	if m != nil {
		return m.DefualtApp
	}
	return false
}

func (m *AppConfig) GetLastUpdateTime() string {
	if m != nil {
		return m.LastUpdateTime
	}
	return ""
}

type AppValues struct {
	OverrideValues       []byte   `protobuf:"bytes,1,opt,name=overrideValues,proto3" json:"overrideValues,omitempty"`
	LaunchUIValues       []byte   `protobuf:"bytes,2,opt,name=launchUIValues,proto3" json:"launchUIValues,omitempty"`
	TemplateValues       []byte   `protobuf:"bytes,3,opt,name=templateValues,proto3" json:"templateValues,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppValues) Reset()         { *m = AppValues{} }
func (m *AppValues) String() string { return proto.CompactTextString(m) }
func (*AppValues) ProtoMessage()    {}
func (*AppValues) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{33}
}

func (m *AppValues) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppValues.Unmarshal(m, b)
}
func (m *AppValues) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppValues.Marshal(b, m, deterministic)
}
func (m *AppValues) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppValues.Merge(m, src)
}
func (m *AppValues) XXX_Size() int {
	return xxx_messageInfo_AppValues.Size(m)
}
func (m *AppValues) XXX_DiscardUnknown() {
	xxx_messageInfo_AppValues.DiscardUnknown(m)
}

var xxx_messageInfo_AppValues proto.InternalMessageInfo

func (m *AppValues) GetOverrideValues() []byte {
	if m != nil {
		return m.OverrideValues
	}
	return nil
}

func (m *AppValues) GetLaunchUIValues() []byte {
	if m != nil {
		return m.LaunchUIValues
	}
	return nil
}

func (m *AppValues) GetTemplateValues() []byte {
	if m != nil {
		return m.TemplateValues
	}
	return nil
}

type AppLaunchConfig struct {
	ReleaseName          string   `protobuf:"bytes,1,opt,name=releaseName,proto3" json:"releaseName,omitempty"`
	Category             string   `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Icon                 []byte   `protobuf:"bytes,4,opt,name=icon,proto3" json:"icon,omitempty"`
	LaunchURL            string   `protobuf:"bytes,5,opt,name=launchURL,proto3" json:"launchURL,omitempty"`
	LaunchUIDescription  string   `protobuf:"bytes,6,opt,name=launchUIDescription,proto3" json:"launchUIDescription,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppLaunchConfig) Reset()         { *m = AppLaunchConfig{} }
func (m *AppLaunchConfig) String() string { return proto.CompactTextString(m) }
func (*AppLaunchConfig) ProtoMessage()    {}
func (*AppLaunchConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{34}
}

func (m *AppLaunchConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppLaunchConfig.Unmarshal(m, b)
}
func (m *AppLaunchConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppLaunchConfig.Marshal(b, m, deterministic)
}
func (m *AppLaunchConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppLaunchConfig.Merge(m, src)
}
func (m *AppLaunchConfig) XXX_Size() int {
	return xxx_messageInfo_AppLaunchConfig.Size(m)
}
func (m *AppLaunchConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_AppLaunchConfig.DiscardUnknown(m)
}

var xxx_messageInfo_AppLaunchConfig proto.InternalMessageInfo

func (m *AppLaunchConfig) GetReleaseName() string {
	if m != nil {
		return m.ReleaseName
	}
	return ""
}

func (m *AppLaunchConfig) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *AppLaunchConfig) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *AppLaunchConfig) GetIcon() []byte {
	if m != nil {
		return m.Icon
	}
	return nil
}

func (m *AppLaunchConfig) GetLaunchURL() string {
	if m != nil {
		return m.LaunchURL
	}
	return ""
}

func (m *AppLaunchConfig) GetLaunchUIDescription() string {
	if m != nil {
		return m.LaunchUIDescription
	}
	return ""
}

type ClusterGitoptsConfig struct {
	Usecase              string            `protobuf:"bytes,1,opt,name=usecase,proto3" json:"usecase,omitempty"`
	ProjectUrl           string            `protobuf:"bytes,2,opt,name=projectUrl,proto3" json:"projectUrl,omitempty"`
	Status               string            `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Credential           map[string]string `protobuf:"bytes,4,rep,name=credential,proto3" json:"credential,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ClusterGitoptsConfig) Reset()         { *m = ClusterGitoptsConfig{} }
func (m *ClusterGitoptsConfig) String() string { return proto.CompactTextString(m) }
func (*ClusterGitoptsConfig) ProtoMessage()    {}
func (*ClusterGitoptsConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{35}
}

func (m *ClusterGitoptsConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterGitoptsConfig.Unmarshal(m, b)
}
func (m *ClusterGitoptsConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterGitoptsConfig.Marshal(b, m, deterministic)
}
func (m *ClusterGitoptsConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterGitoptsConfig.Merge(m, src)
}
func (m *ClusterGitoptsConfig) XXX_Size() int {
	return xxx_messageInfo_ClusterGitoptsConfig.Size(m)
}
func (m *ClusterGitoptsConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterGitoptsConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterGitoptsConfig proto.InternalMessageInfo

func (m *ClusterGitoptsConfig) GetUsecase() string {
	if m != nil {
		return m.Usecase
	}
	return ""
}

func (m *ClusterGitoptsConfig) GetProjectUrl() string {
	if m != nil {
		return m.ProjectUrl
	}
	return ""
}

func (m *ClusterGitoptsConfig) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *ClusterGitoptsConfig) GetCredential() map[string]string {
	if m != nil {
		return m.Credential
	}
	return nil
}

type SetClusterGitoptsProjectRequest struct {
	Usecase              string            `protobuf:"bytes,1,opt,name=usecase,proto3" json:"usecase,omitempty"`
	ProjectUrl           string            `protobuf:"bytes,2,opt,name=projectUrl,proto3" json:"projectUrl,omitempty"`
	Credential           map[string]string `protobuf:"bytes,3,rep,name=credential,proto3" json:"credential,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SetClusterGitoptsProjectRequest) Reset()         { *m = SetClusterGitoptsProjectRequest{} }
func (m *SetClusterGitoptsProjectRequest) String() string { return proto.CompactTextString(m) }
func (*SetClusterGitoptsProjectRequest) ProtoMessage()    {}
func (*SetClusterGitoptsProjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{36}
}

func (m *SetClusterGitoptsProjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetClusterGitoptsProjectRequest.Unmarshal(m, b)
}
func (m *SetClusterGitoptsProjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetClusterGitoptsProjectRequest.Marshal(b, m, deterministic)
}
func (m *SetClusterGitoptsProjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetClusterGitoptsProjectRequest.Merge(m, src)
}
func (m *SetClusterGitoptsProjectRequest) XXX_Size() int {
	return xxx_messageInfo_SetClusterGitoptsProjectRequest.Size(m)
}
func (m *SetClusterGitoptsProjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetClusterGitoptsProjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetClusterGitoptsProjectRequest proto.InternalMessageInfo

func (m *SetClusterGitoptsProjectRequest) GetUsecase() string {
	if m != nil {
		return m.Usecase
	}
	return ""
}

func (m *SetClusterGitoptsProjectRequest) GetProjectUrl() string {
	if m != nil {
		return m.ProjectUrl
	}
	return ""
}

func (m *SetClusterGitoptsProjectRequest) GetCredential() map[string]string {
	if m != nil {
		return m.Credential
	}
	return nil
}

type SetClusterGitoptsProjectResponse struct {
	Status               StatusCode `protobuf:"varint,1,opt,name=status,proto3,enum=agentpb.StatusCode" json:"status,omitempty"`
	StatusMessage        string     `protobuf:"bytes,2,opt,name=statusMessage,proto3" json:"statusMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SetClusterGitoptsProjectResponse) Reset()         { *m = SetClusterGitoptsProjectResponse{} }
func (m *SetClusterGitoptsProjectResponse) String() string { return proto.CompactTextString(m) }
func (*SetClusterGitoptsProjectResponse) ProtoMessage()    {}
func (*SetClusterGitoptsProjectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{37}
}

func (m *SetClusterGitoptsProjectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetClusterGitoptsProjectResponse.Unmarshal(m, b)
}
func (m *SetClusterGitoptsProjectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetClusterGitoptsProjectResponse.Marshal(b, m, deterministic)
}
func (m *SetClusterGitoptsProjectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetClusterGitoptsProjectResponse.Merge(m, src)
}
func (m *SetClusterGitoptsProjectResponse) XXX_Size() int {
	return xxx_messageInfo_SetClusterGitoptsProjectResponse.Size(m)
}
func (m *SetClusterGitoptsProjectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetClusterGitoptsProjectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetClusterGitoptsProjectResponse proto.InternalMessageInfo

func (m *SetClusterGitoptsProjectResponse) GetStatus() StatusCode {
	if m != nil {
		return m.Status
	}
	return StatusCode_OK
}

func (m *SetClusterGitoptsProjectResponse) GetStatusMessage() string {
	if m != nil {
		return m.StatusMessage
	}
	return ""
}

type GetClusterGitoptsProjectRequest struct {
	Usecase              string   `protobuf:"bytes,1,opt,name=usecase,proto3" json:"usecase,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetClusterGitoptsProjectRequest) Reset()         { *m = GetClusterGitoptsProjectRequest{} }
func (m *GetClusterGitoptsProjectRequest) String() string { return proto.CompactTextString(m) }
func (*GetClusterGitoptsProjectRequest) ProtoMessage()    {}
func (*GetClusterGitoptsProjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{38}
}

func (m *GetClusterGitoptsProjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetClusterGitoptsProjectRequest.Unmarshal(m, b)
}
func (m *GetClusterGitoptsProjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetClusterGitoptsProjectRequest.Marshal(b, m, deterministic)
}
func (m *GetClusterGitoptsProjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetClusterGitoptsProjectRequest.Merge(m, src)
}
func (m *GetClusterGitoptsProjectRequest) XXX_Size() int {
	return xxx_messageInfo_GetClusterGitoptsProjectRequest.Size(m)
}
func (m *GetClusterGitoptsProjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetClusterGitoptsProjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetClusterGitoptsProjectRequest proto.InternalMessageInfo

func (m *GetClusterGitoptsProjectRequest) GetUsecase() string {
	if m != nil {
		return m.Usecase
	}
	return ""
}

type GetClusterGitoptsProjectResponse struct {
	Status               StatusCode            `protobuf:"varint,1,opt,name=status,proto3,enum=agentpb.StatusCode" json:"status,omitempty"`
	StatusMessage        string                `protobuf:"bytes,2,opt,name=statusMessage,proto3" json:"statusMessage,omitempty"`
	ClusterGitoptsConfig *ClusterGitoptsConfig `protobuf:"bytes,3,opt,name=clusterGitoptsConfig,proto3" json:"clusterGitoptsConfig,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *GetClusterGitoptsProjectResponse) Reset()         { *m = GetClusterGitoptsProjectResponse{} }
func (m *GetClusterGitoptsProjectResponse) String() string { return proto.CompactTextString(m) }
func (*GetClusterGitoptsProjectResponse) ProtoMessage()    {}
func (*GetClusterGitoptsProjectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{39}
}

func (m *GetClusterGitoptsProjectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetClusterGitoptsProjectResponse.Unmarshal(m, b)
}
func (m *GetClusterGitoptsProjectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetClusterGitoptsProjectResponse.Marshal(b, m, deterministic)
}
func (m *GetClusterGitoptsProjectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetClusterGitoptsProjectResponse.Merge(m, src)
}
func (m *GetClusterGitoptsProjectResponse) XXX_Size() int {
	return xxx_messageInfo_GetClusterGitoptsProjectResponse.Size(m)
}
func (m *GetClusterGitoptsProjectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetClusterGitoptsProjectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetClusterGitoptsProjectResponse proto.InternalMessageInfo

func (m *GetClusterGitoptsProjectResponse) GetStatus() StatusCode {
	if m != nil {
		return m.Status
	}
	return StatusCode_OK
}

func (m *GetClusterGitoptsProjectResponse) GetStatusMessage() string {
	if m != nil {
		return m.StatusMessage
	}
	return ""
}

func (m *GetClusterGitoptsProjectResponse) GetClusterGitoptsConfig() *ClusterGitoptsConfig {
	if m != nil {
		return m.ClusterGitoptsConfig
	}
	return nil
}

type DeleteClusterGitoptsProjectRequest struct {
	Usecase              string   `protobuf:"bytes,1,opt,name=usecase,proto3" json:"usecase,omitempty"`
	ProjectUrl           string   `protobuf:"bytes,2,opt,name=projectUrl,proto3" json:"projectUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteClusterGitoptsProjectRequest) Reset()         { *m = DeleteClusterGitoptsProjectRequest{} }
func (m *DeleteClusterGitoptsProjectRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteClusterGitoptsProjectRequest) ProtoMessage()    {}
func (*DeleteClusterGitoptsProjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{40}
}

func (m *DeleteClusterGitoptsProjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteClusterGitoptsProjectRequest.Unmarshal(m, b)
}
func (m *DeleteClusterGitoptsProjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteClusterGitoptsProjectRequest.Marshal(b, m, deterministic)
}
func (m *DeleteClusterGitoptsProjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteClusterGitoptsProjectRequest.Merge(m, src)
}
func (m *DeleteClusterGitoptsProjectRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteClusterGitoptsProjectRequest.Size(m)
}
func (m *DeleteClusterGitoptsProjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteClusterGitoptsProjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteClusterGitoptsProjectRequest proto.InternalMessageInfo

func (m *DeleteClusterGitoptsProjectRequest) GetUsecase() string {
	if m != nil {
		return m.Usecase
	}
	return ""
}

func (m *DeleteClusterGitoptsProjectRequest) GetProjectUrl() string {
	if m != nil {
		return m.ProjectUrl
	}
	return ""
}

type DeleteClusterGitoptsProjectResponse struct {
	Status               StatusCode `protobuf:"varint,1,opt,name=status,proto3,enum=agentpb.StatusCode" json:"status,omitempty"`
	StatusMessage        string     `protobuf:"bytes,2,opt,name=statusMessage,proto3" json:"statusMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *DeleteClusterGitoptsProjectResponse) Reset()         { *m = DeleteClusterGitoptsProjectResponse{} }
func (m *DeleteClusterGitoptsProjectResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteClusterGitoptsProjectResponse) ProtoMessage()    {}
func (*DeleteClusterGitoptsProjectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{41}
}

func (m *DeleteClusterGitoptsProjectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteClusterGitoptsProjectResponse.Unmarshal(m, b)
}
func (m *DeleteClusterGitoptsProjectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteClusterGitoptsProjectResponse.Marshal(b, m, deterministic)
}
func (m *DeleteClusterGitoptsProjectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteClusterGitoptsProjectResponse.Merge(m, src)
}
func (m *DeleteClusterGitoptsProjectResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteClusterGitoptsProjectResponse.Size(m)
}
func (m *DeleteClusterGitoptsProjectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteClusterGitoptsProjectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteClusterGitoptsProjectResponse proto.InternalMessageInfo

func (m *DeleteClusterGitoptsProjectResponse) GetStatus() StatusCode {
	if m != nil {
		return m.Status
	}
	return StatusCode_OK
}

func (m *DeleteClusterGitoptsProjectResponse) GetStatusMessage() string {
	if m != nil {
		return m.StatusMessage
	}
	return ""
}

type UpgradeAppRequest struct {
	AppConfig            *AppConfig `protobuf:"bytes,1,opt,name=appConfig,proto3" json:"appConfig,omitempty"`
	AppValues            *AppValues `protobuf:"bytes,2,opt,name=appValues,proto3" json:"appValues,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *UpgradeAppRequest) Reset()         { *m = UpgradeAppRequest{} }
func (m *UpgradeAppRequest) String() string { return proto.CompactTextString(m) }
func (*UpgradeAppRequest) ProtoMessage()    {}
func (*UpgradeAppRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{42}
}

func (m *UpgradeAppRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpgradeAppRequest.Unmarshal(m, b)
}
func (m *UpgradeAppRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpgradeAppRequest.Marshal(b, m, deterministic)
}
func (m *UpgradeAppRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpgradeAppRequest.Merge(m, src)
}
func (m *UpgradeAppRequest) XXX_Size() int {
	return xxx_messageInfo_UpgradeAppRequest.Size(m)
}
func (m *UpgradeAppRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpgradeAppRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpgradeAppRequest proto.InternalMessageInfo

func (m *UpgradeAppRequest) GetAppConfig() *AppConfig {
	if m != nil {
		return m.AppConfig
	}
	return nil
}

func (m *UpgradeAppRequest) GetAppValues() *AppValues {
	if m != nil {
		return m.AppValues
	}
	return nil
}

type UpgradeAppResponse struct {
	Status               StatusCode `protobuf:"varint,1,opt,name=status,proto3,enum=agentpb.StatusCode" json:"status,omitempty"`
	StatusMessage        string     `protobuf:"bytes,2,opt,name=statusMessage,proto3" json:"statusMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *UpgradeAppResponse) Reset()         { *m = UpgradeAppResponse{} }
func (m *UpgradeAppResponse) String() string { return proto.CompactTextString(m) }
func (*UpgradeAppResponse) ProtoMessage()    {}
func (*UpgradeAppResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{43}
}

func (m *UpgradeAppResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpgradeAppResponse.Unmarshal(m, b)
}
func (m *UpgradeAppResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpgradeAppResponse.Marshal(b, m, deterministic)
}
func (m *UpgradeAppResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpgradeAppResponse.Merge(m, src)
}
func (m *UpgradeAppResponse) XXX_Size() int {
	return xxx_messageInfo_UpgradeAppResponse.Size(m)
}
func (m *UpgradeAppResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpgradeAppResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpgradeAppResponse proto.InternalMessageInfo

func (m *UpgradeAppResponse) GetStatus() StatusCode {
	if m != nil {
		return m.Status
	}
	return StatusCode_OK
}

func (m *UpgradeAppResponse) GetStatusMessage() string {
	if m != nil {
		return m.StatusMessage
	}
	return ""
}

type UpdateAppValuesRequest struct {
	ReleaseName          string   `protobuf:"bytes,1,opt,name=releaseName,proto3" json:"releaseName,omitempty"`
	OverrideValues       []byte   `protobuf:"bytes,3,opt,name=overrideValues,proto3" json:"overrideValues,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateAppValuesRequest) Reset()         { *m = UpdateAppValuesRequest{} }
func (m *UpdateAppValuesRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateAppValuesRequest) ProtoMessage()    {}
func (*UpdateAppValuesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{44}
}

func (m *UpdateAppValuesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAppValuesRequest.Unmarshal(m, b)
}
func (m *UpdateAppValuesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAppValuesRequest.Marshal(b, m, deterministic)
}
func (m *UpdateAppValuesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAppValuesRequest.Merge(m, src)
}
func (m *UpdateAppValuesRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateAppValuesRequest.Size(m)
}
func (m *UpdateAppValuesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAppValuesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAppValuesRequest proto.InternalMessageInfo

func (m *UpdateAppValuesRequest) GetReleaseName() string {
	if m != nil {
		return m.ReleaseName
	}
	return ""
}

func (m *UpdateAppValuesRequest) GetOverrideValues() []byte {
	if m != nil {
		return m.OverrideValues
	}
	return nil
}

type UpdateAppValuesResponse struct {
	Status               StatusCode `protobuf:"varint,1,opt,name=status,proto3,enum=agentpb.StatusCode" json:"status,omitempty"`
	StatusMessage        string     `protobuf:"bytes,2,opt,name=statusMessage,proto3" json:"statusMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *UpdateAppValuesResponse) Reset()         { *m = UpdateAppValuesResponse{} }
func (m *UpdateAppValuesResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateAppValuesResponse) ProtoMessage()    {}
func (*UpdateAppValuesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{45}
}

func (m *UpdateAppValuesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAppValuesResponse.Unmarshal(m, b)
}
func (m *UpdateAppValuesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAppValuesResponse.Marshal(b, m, deterministic)
}
func (m *UpdateAppValuesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAppValuesResponse.Merge(m, src)
}
func (m *UpdateAppValuesResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateAppValuesResponse.Size(m)
}
func (m *UpdateAppValuesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAppValuesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAppValuesResponse proto.InternalMessageInfo

func (m *UpdateAppValuesResponse) GetStatus() StatusCode {
	if m != nil {
		return m.Status
	}
	return StatusCode_OK
}

func (m *UpdateAppValuesResponse) GetStatusMessage() string {
	if m != nil {
		return m.StatusMessage
	}
	return ""
}

func init() {
	proto.RegisterEnum("agentpb.StatusCode", StatusCode_name, StatusCode_value)
	proto.RegisterType((*PingRequest)(nil), "agentpb.PingRequest")
	proto.RegisterType((*PingResponse)(nil), "agentpb.PingResponse")
	proto.RegisterType((*StoreCredentialRequest)(nil), "agentpb.StoreCredentialRequest")
	proto.RegisterMapType((map[string]string)(nil), "agentpb.StoreCredentialRequest.CredentialEntry")
	proto.RegisterType((*StoreCredentialResponse)(nil), "agentpb.StoreCredentialResponse")
	proto.RegisterType((*ClusterRequest)(nil), "agentpb.ClusterRequest")
	proto.RegisterType((*RepositoryAddRequest)(nil), "agentpb.RepositoryAddRequest")
	proto.RegisterType((*RepositoryDeleteRequest)(nil), "agentpb.RepositoryDeleteRequest")
	proto.RegisterType((*ProjectAddRequest)(nil), "agentpb.ProjectAddRequest")
	proto.RegisterType((*ProjectDeleteRequest)(nil), "agentpb.ProjectDeleteRequest")
	proto.RegisterType((*JobRequest)(nil), "agentpb.JobRequest")
	proto.RegisterType((*JobResponse)(nil), "agentpb.JobResponse")
	proto.RegisterType((*SyncAppRequest)(nil), "agentpb.SyncAppRequest")
	proto.RegisterType((*SyncAppResponse)(nil), "agentpb.SyncAppResponse")
	proto.RegisterType((*GetClusterAppsRequest)(nil), "agentpb.GetClusterAppsRequest")
	proto.RegisterType((*GetClusterAppsResponse)(nil), "agentpb.GetClusterAppsResponse")
	proto.RegisterType((*GetClusterAppLaunchesRequest)(nil), "agentpb.GetClusterAppLaunchesRequest")
	proto.RegisterType((*GetClusterAppLaunchesResponse)(nil), "agentpb.GetClusterAppLaunchesResponse")
	proto.RegisterType((*ConfigureAppSSORequest)(nil), "agentpb.ConfigureAppSSORequest")
	proto.RegisterType((*ConfigureAppSSOResponse)(nil), "agentpb.ConfigureAppSSOResponse")
	proto.RegisterType((*GetClusterAppConfigRequest)(nil), "agentpb.GetClusterAppConfigRequest")
	proto.RegisterType((*GetClusterAppConfigResponse)(nil), "agentpb.GetClusterAppConfigResponse")
	proto.RegisterType((*GetClusterAppValuesRequest)(nil), "agentpb.GetClusterAppValuesRequest")
	proto.RegisterType((*GetClusterAppValuesResponse)(nil), "agentpb.GetClusterAppValuesResponse")
	proto.RegisterType((*GetClusterGlobalValuesRequest)(nil), "agentpb.GetClusterGlobalValuesRequest")
	proto.RegisterType((*GetClusterGlobalValuesResponse)(nil), "agentpb.GetClusterGlobalValuesResponse")
	proto.RegisterType((*InstallAppRequest)(nil), "agentpb.InstallAppRequest")
	proto.RegisterType((*InstallAppResponse)(nil), "agentpb.InstallAppResponse")
	proto.RegisterType((*UnInstallAppRequest)(nil), "agentpb.UnInstallAppRequest")
	proto.RegisterType((*UnInstallAppResponse)(nil), "agentpb.UnInstallAppResponse")
	proto.RegisterType((*SyncAppData)(nil), "agentpb.SyncAppData")
	proto.RegisterType((*AppData)(nil), "agentpb.AppData")
	proto.RegisterType((*AppStatus)(nil), "agentpb.AppStatus")
	proto.RegisterType((*AppConfig)(nil), "agentpb.AppConfig")
	proto.RegisterType((*AppValues)(nil), "agentpb.AppValues")
	proto.RegisterType((*AppLaunchConfig)(nil), "agentpb.AppLaunchConfig")
	proto.RegisterType((*ClusterGitoptsConfig)(nil), "agentpb.ClusterGitoptsConfig")
	proto.RegisterMapType((map[string]string)(nil), "agentpb.ClusterGitoptsConfig.CredentialEntry")
	proto.RegisterType((*SetClusterGitoptsProjectRequest)(nil), "agentpb.SetClusterGitoptsProjectRequest")
	proto.RegisterMapType((map[string]string)(nil), "agentpb.SetClusterGitoptsProjectRequest.CredentialEntry")
	proto.RegisterType((*SetClusterGitoptsProjectResponse)(nil), "agentpb.SetClusterGitoptsProjectResponse")
	proto.RegisterType((*GetClusterGitoptsProjectRequest)(nil), "agentpb.GetClusterGitoptsProjectRequest")
	proto.RegisterType((*GetClusterGitoptsProjectResponse)(nil), "agentpb.GetClusterGitoptsProjectResponse")
	proto.RegisterType((*DeleteClusterGitoptsProjectRequest)(nil), "agentpb.DeleteClusterGitoptsProjectRequest")
	proto.RegisterType((*DeleteClusterGitoptsProjectResponse)(nil), "agentpb.DeleteClusterGitoptsProjectResponse")
	proto.RegisterType((*UpgradeAppRequest)(nil), "agentpb.UpgradeAppRequest")
	proto.RegisterType((*UpgradeAppResponse)(nil), "agentpb.UpgradeAppResponse")
	proto.RegisterType((*UpdateAppValuesRequest)(nil), "agentpb.UpdateAppValuesRequest")
	proto.RegisterType((*UpdateAppValuesResponse)(nil), "agentpb.UpdateAppValuesResponse")
}

func init() { proto.RegisterFile("agent.proto", fileDescriptor_56ede974c0020f77) }

var fileDescriptor_56ede974c0020f77 = []byte{
	// 1835 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x59, 0xdd, 0x72, 0xdb, 0xc6,
	0x15, 0x16, 0x28, 0x59, 0x12, 0x0f, 0x29, 0x89, 0x5e, 0x31, 0x32, 0x02, 0xff, 0x48, 0x41, 0xd2,
	0x54, 0x4d, 0x5a, 0x39, 0x55, 0xa7, 0x53, 0x4f, 0x32, 0xc9, 0x94, 0xb1, 0x14, 0x0e, 0x53, 0x9a,
	0x72, 0x41, 0xd1, 0xee, 0xe4, 0xa2, 0x9a, 0x25, 0xb1, 0xa2, 0x51, 0x43, 0x00, 0x02, 0x2c, 0xec,
	0xb2, 0xb7, 0x7d, 0x88, 0xf6, 0xa2, 0xd3, 0xe9, 0xf4, 0x29, 0xfa, 0x08, 0x7d, 0x81, 0x3e, 0x42,
	0xdf, 0xa0, 0xd3, 0xeb, 0x0e, 0x76, 0x17, 0xc0, 0x02, 0x04, 0x48, 0xda, 0x53, 0xf8, 0x0e, 0x7b,
	0xf6, 0xdb, 0xf3, 0xbf, 0xbb, 0x67, 0x0f, 0xa0, 0x81, 0xa7, 0xc4, 0xa1, 0x27, 0x9e, 0xef, 0x52,
	0x17, 0x6d, 0xb1, 0x81, 0x37, 0xd6, 0xde, 0x9f, 0xba, 0xee, 0xd4, 0x26, 0x0f, 0x19, 0x79, 0x1c,
	0x5e, 0x3f, 0xc4, 0xce, 0x8c, 0x63, 0xf4, 0x1d, 0x68, 0x3c, 0xb5, 0x9c, 0xa9, 0x41, 0xbe, 0x0f,
	0x49, 0x40, 0xf5, 0x2f, 0xa0, 0xc9, 0x87, 0x81, 0xe7, 0x3a, 0x01, 0x41, 0x9f, 0xc2, 0x66, 0x40,
	0x31, 0x0d, 0x03, 0x55, 0x39, 0x52, 0x8e, 0x77, 0x4f, 0xf7, 0x4f, 0x04, 0xcf, 0x93, 0x21, 0x23,
	0x3f, 0x76, 0x4d, 0x62, 0x08, 0x88, 0xfe, 0xb7, 0x1a, 0x1c, 0x0c, 0xa9, 0xeb, 0x93, 0xc7, 0x3e,
	0x31, 0x89, 0x43, 0x2d, 0x6c, 0x0b, 0xbe, 0xe8, 0x63, 0xd8, 0x9d, 0x24, 0xc4, 0xcb, 0x99, 0x47,
	0x18, 0xbf, 0xba, 0x91, 0xa3, 0xc6, 0xb8, 0x73, 0x87, 0x5a, 0x74, 0x36, 0xc0, 0x37, 0x44, 0xad,
	0xa5, 0xb8, 0x94, 0x1a, 0xe3, 0x7a, 0x6c, 0xed, 0xb5, 0x45, 0x7c, 0x75, 0x3d, 0xc5, 0xa5, 0x54,
	0x74, 0x01, 0x90, 0x4a, 0x50, 0x37, 0x8e, 0xd6, 0x8f, 0x1b, 0xa7, 0x0f, 0x25, 0x1b, 0x8a, 0x94,
	0x3d, 0x49, 0x29, 0xe7, 0x0e, 0xf5, 0x67, 0x86, 0xc4, 0x42, 0xfb, 0x12, 0xf6, 0x72, 0xd3, 0xa8,
	0x05, 0xeb, 0x2f, 0xc9, 0x4c, 0x18, 0x14, 0x7d, 0xa2, 0x36, 0xdc, 0x7a, 0x85, 0xed, 0x30, 0x56,
	0x9e, 0x0f, 0x3e, 0xaf, 0x3d, 0x52, 0x74, 0x1b, 0xee, 0xcc, 0x09, 0x7d, 0x0b, 0x57, 0xa3, 0x8f,
	0x60, 0x87, 0x7f, 0x3d, 0x21, 0x41, 0x80, 0xa7, 0xb1, 0xa4, 0x2c, 0x51, 0xbf, 0x84, 0xdd, 0xc7,
	0x76, 0x18, 0x50, 0xe2, 0xc7, 0x71, 0x38, 0x84, 0x86, 0x67, 0x87, 0x53, 0xcb, 0xb9, 0x72, 0x22,
	0xe7, 0x72, 0x9d, 0x81, 0x93, 0x98, 0x63, 0x3f, 0x80, 0xe6, 0x84, 0x2f, 0xe1, 0x08, 0xce, 0xb7,
	0x21, 0x68, 0x11, 0x44, 0x77, 0xa1, 0x6d, 0x10, 0xcf, 0x0d, 0x2c, 0xea, 0xfa, 0xb3, 0x8e, 0x69,
	0xae, 0xcc, 0xfb, 0x2e, 0xd4, 0x7d, 0xe2, 0xb9, 0x32, 0xe3, 0xed, 0x88, 0xc0, 0x26, 0xdf, 0x07,
	0xf6, 0x7d, 0x15, 0xfa, 0xb6, 0x88, 0xe5, 0x56, 0x34, 0x1e, 0xf9, 0xb6, 0xfe, 0x1c, 0xee, 0xa4,
	0x02, 0xcf, 0x88, 0x4d, 0x28, 0xf9, 0xbf, 0xc8, 0xd4, 0x9f, 0xc3, 0xed, 0xa7, 0xbe, 0xfb, 0x3b,
	0x32, 0xa1, 0x6f, 0x62, 0xc6, 0x07, 0xd0, 0xf4, 0xf8, 0xaa, 0x8c, 0x8b, 0x04, 0x8d, 0x31, 0xfe,
	0x0e, 0xda, 0x82, 0xf1, 0x1b, 0xaa, 0xbb, 0x12, 0x6f, 0xf8, 0xd6, 0x1d, 0xc7, 0x1c, 0xef, 0x41,
	0xdd, 0xf5, 0x88, 0x8f, 0xa9, 0xe5, 0x3a, 0x82, 0x5f, 0x4a, 0x40, 0x27, 0xb0, 0xe5, 0xe1, 0x99,
	0xed, 0x62, 0x93, 0x71, 0x6a, 0x9c, 0xb6, 0x4f, 0xf8, 0x51, 0x70, 0x12, 0x1f, 0x05, 0x27, 0x1d,
	0x67, 0x66, 0xc4, 0x20, 0xfd, 0x39, 0x34, 0x18, 0x6f, 0x91, 0x92, 0xbb, 0x50, 0xb3, 0x4c, 0xc1,
	0xb5, 0x66, 0x99, 0x51, 0x5e, 0xfb, 0xa1, 0xd3, 0x3b, 0x8b, 0xf3, 0x9a, 0x0d, 0x90, 0x0e, 0xcd,
	0xd7, 0xae, 0xff, 0xf2, 0xda, 0x76, 0x5f, 0xb3, 0x1d, 0xcb, 0xa3, 0x97, 0xa1, 0xe9, 0x9f, 0xc3,
	0xee, 0x70, 0xe6, 0x4c, 0x3a, 0x9e, 0x17, 0x2b, 0x7e, 0x0c, 0x1b, 0x26, 0xa6, 0x98, 0x71, 0x8f,
	0xf4, 0x4a, 0x92, 0x9d, 0xc3, 0xce, 0x30, 0xc5, 0x06, 0x43, 0xe8, 0x26, 0xec, 0x25, 0x6b, 0xab,
	0xdb, 0x2b, 0x77, 0xe0, 0xbd, 0x2e, 0xa1, 0x62, 0xbb, 0x74, 0x3c, 0x2f, 0x88, 0x8f, 0xc4, 0x3f,
	0x29, 0x70, 0x90, 0x9f, 0xa9, 0x4c, 0x0d, 0xf4, 0x09, 0x6c, 0x61, 0x6e, 0xbd, 0xba, 0xce, 0x4e,
	0xab, 0x56, 0xc2, 0x33, 0xf6, 0x4a, 0x0c, 0xd0, 0x1f, 0xc0, 0xbd, 0x8c, 0x62, 0x7d, 0x1c, 0x3a,
	0x93, 0x17, 0x24, 0xd1, 0xfc, 0x1f, 0x0a, 0xdc, 0x2f, 0x01, 0x54, 0x67, 0xc0, 0x19, 0xb4, 0x6c,
	0x26, 0xe6, 0xb1, 0xeb, 0x5c, 0x5b, 0xd3, 0xbe, 0x15, 0x50, 0x61, 0x89, 0x2a, 0x5b, 0xd2, 0x97,
	0x30, 0xc6, 0xdc, 0x0a, 0xfd, 0xaf, 0x0a, 0x1c, 0xf0, 0x61, 0xe8, 0x93, 0x8e, 0xe7, 0x0d, 0x87,
	0x17, 0x71, 0xe2, 0x1c, 0x41, 0xc3, 0x27, 0x36, 0xc1, 0x01, 0x19, 0xa4, 0x7b, 0x48, 0x26, 0x21,
	0x0d, 0xb6, 0x27, 0xb6, 0x45, 0x1c, 0xda, 0x33, 0xe3, 0x2d, 0x1f, 0x8f, 0xa3, 0x64, 0xe5, 0xdf,
	0x43, 0x32, 0xf1, 0x09, 0x8d, 0x93, 0x55, 0xa6, 0x45, 0x18, 0xb7, 0x13, 0xd2, 0x17, 0x5f, 0xe3,
	0x80, 0x8c, 0x8c, 0xbe, 0xba, 0xc1, 0x31, 0x32, 0x2d, 0x3a, 0xc8, 0xe7, 0xf4, 0xab, 0x2e, 0x39,
	0xbf, 0x02, 0x2d, 0x13, 0x48, 0xe1, 0xb7, 0x55, 0x3d, 0xa2, 0xff, 0x5d, 0x81, 0xbb, 0x85, 0x0c,
	0xaa, 0xcb, 0x83, 0xcf, 0xa0, 0x8e, 0x63, 0x39, 0xcc, 0xcb, 0x8d, 0x53, 0x24, 0x27, 0x80, 0xd0,
	0x20, 0x05, 0xcd, 0x19, 0xf9, 0x2c, 0xba, 0x35, 0x83, 0xd5, 0x8d, 0xfc, 0x4b, 0xde, 0xc8, 0x98,
	0x41, 0x95, 0xbb, 0x75, 0x93, 0xdd, 0xed, 0x41, 0x91, 0x85, 0x42, 0xbc, 0x40, 0xe8, 0x87, 0xf2,
	0x66, 0xec, 0xda, 0xee, 0x18, 0xdb, 0x19, 0x0b, 0xa3, 0x83, 0xe6, 0x41, 0x19, 0xa2, 0x3a, 0x13,
	0x74, 0x68, 0x4e, 0x25, 0x51, 0xcc, 0x90, 0xa6, 0x91, 0xa1, 0xe9, 0xaf, 0xe1, 0x76, 0xcf, 0x09,
	0x28, 0xb6, 0x6d, 0xe9, 0x00, 0xcf, 0x04, 0x58, 0x59, 0x21, 0xc0, 0x62, 0x85, 0x90, 0x53, 0x2b,
	0x75, 0x58, 0x0a, 0xd2, 0xa7, 0x80, 0x64, 0xc1, 0xd5, 0x6d, 0xb0, 0x5f, 0xc0, 0xfe, 0xc8, 0x99,
	0xb7, 0x31, 0x97, 0x74, 0xb5, 0xf9, 0xa4, 0xb3, 0xa0, 0x9d, 0x5d, 0x58, 0x9d, 0x8e, 0x04, 0x1a,
	0xd2, 0xe5, 0x18, 0xe5, 0xde, 0x64, 0x99, 0xf3, 0x05, 0x42, 0xca, 0xd3, 0xda, 0xd2, 0x3c, 0xc5,
	0xb0, 0xf5, 0x96, 0x22, 0x84, 0xc1, 0x05, 0x22, 0xb8, 0xcd, 0xc9, 0x43, 0xe1, 0xa7, 0x50, 0x4f,
	0x88, 0x91, 0xf1, 0x7e, 0xe8, 0x50, 0xeb, 0x86, 0x0c, 0x53, 0x87, 0xd5, 0x8d, 0x2c, 0x51, 0xff,
	0xf7, 0x06, 0x5b, 0x23, 0x32, 0x69, 0xf9, 0x1d, 0xa0, 0xb2, 0x7b, 0x54, 0x8a, 0x5a, 0x3c, 0x8c,
	0x66, 0x5e, 0x11, 0x3f, 0x88, 0xea, 0x25, 0x51, 0x67, 0x8a, 0x21, 0xbb, 0x37, 0x30, 0x25, 0x53,
	0xd7, 0x9f, 0x89, 0x33, 0x3f, 0x19, 0x47, 0x12, 0x4d, 0x12, 0x4c, 0x7c, 0xcb, 0x63, 0x95, 0xd6,
	0x2d, 0x2e, 0x51, 0x22, 0x45, 0x95, 0xd8, 0xe4, 0x05, 0xf6, 0x59, 0x91, 0xa6, 0x6e, 0xf2, 0x4a,
	0x2c, 0x21, 0x44, 0xbc, 0xe3, 0xb2, 0x53, 0xdd, 0xca, 0x95, 0xbe, 0x2a, 0xf0, 0x52, 0xd7, 0xe8,
	0xab, 0xdb, 0x52, 0xe5, 0x6b, 0xf4, 0x23, 0x9e, 0x51, 0x19, 0x18, 0x78, 0x78, 0x42, 0xd4, 0x3a,
	0xe7, 0x99, 0x10, 0xd0, 0x31, 0xec, 0x4d, 0x7c, 0x82, 0x29, 0xb3, 0x98, 0x63, 0xe0, 0x48, 0x39,
	0xde, 0x36, 0xf2, 0x64, 0xf4, 0x19, 0xec, 0x7b, 0xbe, 0xf5, 0xca, 0xb2, 0xc9, 0x94, 0x98, 0x29,
	0xba, 0xc1, 0xd0, 0x45, 0x53, 0x08, 0xc1, 0x86, 0x35, 0x71, 0x1d, 0xb5, 0xc9, 0x8e, 0x03, 0xf6,
	0x1d, 0x69, 0xc3, 0x2f, 0xea, 0x48, 0xd3, 0x1d, 0xae, 0x4d, 0x42, 0x88, 0x64, 0x88, 0x41, 0xef,
	0x4c, 0xf2, 0xd4, 0x2e, 0xc3, 0x15, 0x4d, 0x45, 0x91, 0xb7, 0xf8, 0xce, 0x11, 0x91, 0xdf, 0xe3,
	0x91, 0xcf, 0x10, 0xe7, 0xf3, 0xa3, 0x55, 0x90, 0x1f, 0xe8, 0x01, 0x80, 0x49, 0xae, 0x43, 0x6c,
	0xd3, 0x8e, 0xe7, 0xa9, 0xb7, 0x99, 0x61, 0x12, 0x25, 0x7a, 0x30, 0xda, 0x38, 0xa0, 0x23, 0xcf,
	0xc4, 0x94, 0x5c, 0x5a, 0x37, 0x44, 0x45, 0xfc, 0xc1, 0x98, 0xa5, 0xea, 0x7f, 0x54, 0x58, 0x9e,
	0xf1, 0x3d, 0x11, 0xad, 0x72, 0x5f, 0x11, 0xdf, 0xb7, 0x4c, 0x22, 0x8e, 0x2d, 0x85, 0xf9, 0x23,
	0x47, 0xe5, 0xdc, 0xb9, 0x81, 0xd2, 0xf1, 0xd6, 0x34, 0x72, 0xd4, 0x08, 0x47, 0xc9, 0x8d, 0x67,
	0x63, 0x4a, 0x32, 0xc7, 0x6d, 0x8e, 0xaa, 0xff, 0x4b, 0x81, 0xbd, 0x5c, 0x91, 0xb4, 0x62, 0xdd,
	0x13, 0xe7, 0x6f, 0x6d, 0x71, 0xfe, 0xae, 0xcf, 0xe7, 0x6f, 0x1c, 0xf1, 0x8d, 0xb2, 0x88, 0xdf,
	0x5a, 0x31, 0xe2, 0x9b, 0xa5, 0x11, 0xd7, 0xff, 0xab, 0x40, 0x3b, 0xbe, 0xdf, 0x2c, 0xea, 0x7a,
	0x34, 0x10, 0xc6, 0xa9, 0xb0, 0x15, 0x06, 0x64, 0x82, 0x83, 0xd8, 0xb0, 0x78, 0x18, 0x05, 0x56,
	0xbc, 0x7e, 0x46, 0xbe, 0x2d, 0xcc, 0x92, 0x28, 0xe8, 0x20, 0x39, 0x77, 0xb8, 0x4d, 0xf1, 0x99,
	0xfa, 0xa4, 0xe0, 0xe5, 0xff, 0x93, 0xe4, 0x4c, 0x2a, 0x52, 0xa2, 0xca, 0x77, 0xff, 0x7f, 0x14,
	0x38, 0x1c, 0xa6, 0x77, 0x3b, 0x17, 0x2b, 0x9e, 0x88, 0xf1, 0x65, 0xf3, 0xf6, 0x3e, 0xf8, 0x4d,
	0xc6, 0x56, 0x5e, 0x6d, 0x3f, 0x4a, 0x2f, 0x9c, 0xc5, 0x72, 0xab, 0x34, 0x3b, 0x84, 0xa3, 0x72,
	0xe9, 0xd5, 0xdd, 0x94, 0x5f, 0xc0, 0x61, 0xf7, 0x6d, 0x9d, 0xad, 0xff, 0x53, 0x81, 0xa3, 0xee,
	0xbb, 0x57, 0x1a, 0xfd, 0x1a, 0xda, 0x93, 0x82, 0xac, 0x14, 0x95, 0xe5, 0xfd, 0x85, 0xa9, 0x6b,
	0x14, 0x2e, 0xd5, 0x7f, 0x0b, 0x3a, 0xef, 0x3f, 0x54, 0x93, 0x77, 0xfa, 0xef, 0xe1, 0xc3, 0x85,
	0xfc, 0xab, 0x8b, 0xf0, 0x6b, 0xb8, 0x3d, 0xf2, 0xa6, 0x3e, 0x36, 0xc9, 0xbb, 0xaf, 0x48, 0x65,
	0xc1, 0xd5, 0x59, 0x38, 0x86, 0x03, 0x7e, 0x2d, 0xbd, 0xf9, 0x4b, 0xa8, 0xe0, 0xda, 0x5a, 0x2f,
	0xba, 0xb6, 0xa2, 0x47, 0xec, 0x9c, 0x8c, 0xca, 0x2c, 0xfa, 0x64, 0x00, 0x90, 0xae, 0x45, 0x9b,
	0x50, 0xbb, 0xf8, 0x55, 0x6b, 0x0d, 0xed, 0xc3, 0x5e, 0x6f, 0x70, 0x79, 0x6e, 0x0c, 0x8c, 0x4e,
	0xff, 0xea, 0xdc, 0x30, 0x2e, 0x8c, 0x96, 0x82, 0xda, 0xd0, 0xea, 0x0d, 0x9e, 0x75, 0xfa, 0xbd,
	0xb3, 0xab, 0x8e, 0xd1, 0x1d, 0x3d, 0x39, 0x1f, 0x5c, 0xb6, 0x6a, 0x68, 0x07, 0xea, 0x83, 0x8b,
	0xcb, 0xab, 0x6f, 0x2e, 0x46, 0x83, 0xb3, 0xd6, 0xfa, 0xe9, 0x9f, 0xf7, 0xe0, 0x56, 0x27, 0x52,
	0x0a, 0x3d, 0x82, 0xfa, 0x30, 0x1c, 0xdf, 0x58, 0xf4, 0x5b, 0x77, 0x8c, 0x52, 0x4d, 0xd3, 0x36,
	0x99, 0xd6, 0xce, 0x12, 0xb9, 0x91, 0xfa, 0x1a, 0xfa, 0x12, 0x20, 0x7e, 0x2f, 0x9a, 0x26, 0xba,
	0x93, 0xdf, 0x64, 0xcb, 0x96, 0xff, 0x12, 0x76, 0x04, 0x92, 0xef, 0x83, 0x37, 0xe7, 0xf0, 0x0d,
	0xec, 0x64, 0x9a, 0xa9, 0x28, 0xdd, 0xe8, 0x45, 0x4d, 0xd6, 0x52, 0x3e, 0x7d, 0x68, 0xe5, 0x7b,
	0xa4, 0xe8, 0xa8, 0x80, 0x55, 0xa6, 0x1f, 0xb9, 0xc0, 0x2e, 0x48, 0x1b, 0xa3, 0x48, 0x4b, 0x50,
	0x73, 0xdd, 0xd2, 0x45, 0x76, 0x65, 0x3a, 0xa0, 0x92, 0x5d, 0x45, 0x9d, 0xd1, 0x52, 0x3e, 0x3f,
	0x87, 0x8d, 0xa7, 0x96, 0x33, 0x45, 0xe9, 0xbc, 0xf4, 0xbb, 0x42, 0x7b, 0x2f, 0x47, 0x4d, 0x96,
	0x3d, 0x83, 0xbd, 0x5c, 0x9f, 0x1d, 0x1d, 0x2e, 0x69, 0xfb, 0x6b, 0x47, 0xe5, 0x80, 0x84, 0xef,
	0x57, 0xb0, 0x25, 0xde, 0x60, 0x52, 0xa8, 0xb3, 0x9d, 0x4d, 0x4d, 0x9d, 0x9f, 0x48, 0xd6, 0x0f,
	0x61, 0x37, 0xdb, 0x4b, 0x44, 0x0f, 0x12, 0x74, 0x61, 0xfb, 0x51, 0x3b, 0x2c, 0x9d, 0x4f, 0x98,
	0xbe, 0xc8, 0xb5, 0x2e, 0xe3, 0x36, 0x1f, 0xfa, 0x41, 0xf1, 0xda, 0x5c, 0x9f, 0x50, 0xfb, 0x78,
	0x19, 0x4c, 0x76, 0x6b, 0xae, 0xeb, 0x25, 0xb9, 0xb5, 0xb8, 0x5f, 0x27, 0xb9, 0xb5, 0xa4, 0x61,
	0xa6, 0xaf, 0xa1, 0x31, 0xec, 0x17, 0xb4, 0xa7, 0xd0, 0x87, 0xc5, 0x8a, 0x65, 0xba, 0x5f, 0xda,
	0x47, 0x8b, 0x41, 0xa5, 0x32, 0x44, 0x49, 0x5e, 0x22, 0x23, 0x73, 0xe4, 0x96, 0xc9, 0xc8, 0x9e,
	0x99, 0xfa, 0x1a, 0x7a, 0x29, 0xb7, 0x8a, 0xe5, 0x0e, 0x0e, 0x2a, 0xf2, 0x71, 0x41, 0x13, 0x48,
	0xfb, 0xe1, 0x52, 0x5c, 0x22, 0xac, 0x0b, 0x90, 0x36, 0x1e, 0xa4, 0x4d, 0x3a, 0xd7, 0xc6, 0xd0,
	0xee, 0x16, 0xce, 0x25, 0x8c, 0x9e, 0x40, 0x53, 0xee, 0x61, 0xa0, 0x7b, 0x09, 0xbc, 0xa0, 0x27,
	0xa2, 0xdd, 0x2f, 0x99, 0x4d, 0xd8, 0x7d, 0x0f, 0x6a, 0x59, 0xd1, 0x87, 0x8e, 0x57, 0xad, 0x4a,
	0xb5, 0x1f, 0xad, 0x80, 0x94, 0x45, 0x76, 0x97, 0x8b, 0xec, 0xae, 0x2c, 0xb2, 0xbb, 0x5c, 0xe4,
	0x1f, 0xe0, 0xee, 0x82, 0xda, 0x07, 0x7d, 0x9a, 0xf0, 0x5a, 0x5e, 0x81, 0x69, 0x3f, 0x5e, 0x0d,
	0x2c, 0x47, 0x3e, 0x2d, 0x42, 0xa4, 0xc8, 0xcf, 0x95, 0x44, 0x52, 0xe4, 0xe7, 0xab, 0x16, 0xbe,
	0x9f, 0x73, 0x05, 0x80, 0xb4, 0x9f, 0x8b, 0xcb, 0x0f, 0x69, 0x3f, 0x97, 0xd4, 0x0e, 0xfa, 0xda,
	0xd7, 0xf0, 0xdd, 0xf6, 0x43, 0x81, 0x1a, 0x6f, 0xb2, 0x5f, 0x4d, 0x3f, 0xfb, 0x5f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x80, 0x29, 0x3d, 0x71, 0x9b, 0x1e, 0x00, 0x00,
}
